// #3390 — the auto-draft-and-apply description scenario. `descriptionStatus` (issue #3401) is
// produced automatically by the server's own terminal-run hook once the live run's head is
// stable; applying it never happens through that hook (#3401 correction 1: "never applies a
// description") -- it goes through #3399's EXISTING PR preview/approve/apply flow, exactly what
// the standalone `GovernedPullRequestCard` window already drives in the scripted
// `git-change-chat-3400.spec.ts` sibling ("qualifies the governed PR Description panel"). This
// module reuses that SAME card/testids against the real created draft PR instead of a second
// description-apply surface.
//
// Review 3941762922: applying the RETAINED automatic draft (the exact artifact #3401 already
// generated -- `proposalId`/`snapshotDigest`/`draftDigest`) is the #3390 acceptance criterion, not
// a fresh description generated by this scenario's own manual "Preview" click. The card's own
// retained-proposal path (`GovernedPullRequestCard`'s `descriptionProposal` prop ->
// `useRetainedDescriptionProposal` -> `prDescriptionReview`, reached in production through
// `CodingWorkbenchWindow`'s "Review description" control) is reused here by opening the window
// with the SAME cfg fields that control populates (`descriptionOwnerAndRepo`/`descriptionPrNumber`/
// `descriptionProposalId`/`descriptionSnapshotDigest`, `widgets/index.tsx`'s `governedPullRequest`
// render), instead of filling the create/update form and clicking the manual preview button.

import { expect, type Locator, type Page, type Response } from "@playwright/test";
import { APPLIED_PR_DESCRIPTION_STATES } from "@oscharko-dev/keiko-contracts/runtime/git-journey-freshness";
import { waitWhileAnsweringApprovals, raiseWindow } from "./coding-issue-journey-live.js";
import type { DeliveredPullRequest } from "./coding-issue-journey-live.js";
import {
  observedDescriptionStatus,
  type ObservedDescriptionStatus,
} from "./coding-issue-journey-live-observed.js";

const REVIEW_ENDPOINT = "/api/git-delivery/pr-description/review";
const APPLY_ENDPOINT = "/api/git-delivery/pr-description/apply";
const STATUS_ENDPOINT = "/api/git-delivery/pr-description/status";

/** The exact retained artifact identity #3401 already generated, as the card's OWN review request
 * resolved it -- read back from that response rather than restated by this lane, then carried
 * through approve/apply/refresh so every later step is checked against the SAME draft. `projectId`
 * is the scope production resolved the click to; the lane pins every later description request to
 * it, which is how it holds the #3401 regression without scraping a workspace path the product
 * deliberately never displays. */
export interface RetainedDescriptionBinding {
  readonly proposalId: string;
  readonly snapshotDigest: string;
  readonly draftDigest: string;
  readonly projectId: string;
}

interface PrDescriptionReviewWireBody {
  readonly preview: {
    readonly proposalId: string;
    readonly status: {
      readonly binding: {
        readonly snapshotDigest: string;
        readonly draftDigest: string;
        readonly headSha: string;
      };
    };
  };
}

/** The target fields every description request carries (`GitDeliveryPrDescriptionTarget`, api.ts)
 * -- read back from the network request (never constructed by this test) to confirm production
 * resolved the click to the run's task workspace root and the delivered pull request, not merely to
 * a proposal whose digests happen to match. */
interface PrDescriptionRequestBody {
  readonly projectId: string;
  readonly ownerAndRepo: string;
  readonly prNumber: number;
}

interface PrDescriptionApplyWireBody {
  readonly outcome: string;
  readonly status?: { readonly binding: { readonly draftDigest: string } };
}

interface PrDescriptionStatusBinding {
  readonly repository: string;
  readonly prNumber: number;
  readonly headRef: string;
  readonly headSha: string;
  readonly isDraft: boolean;
}

interface PrDescriptionStatusWireBody {
  readonly outcome: string;
  readonly reason?: string;
  readonly status?: {
    readonly state: string;
    readonly effect: string;
    readonly binding: PrDescriptionStatusBinding;
  };
}

// The wire body reports `state` as a string; the contract's closed set is consulted through a
// string-typed view so membership is checked, never narrowed by assertion.
const APPLIED_STATES: ReadonlySet<string> = APPLIED_PR_DESCRIPTION_STATES;
const APPLIED_DESCRIPTION_STATE = new RegExp(
  `^(${[...APPLIED_PR_DESCRIPTION_STATES].join("|")})$`,
  "u",
);

/** Body-free summary of a status response for a failure message: outcome, closed reason/state
 * words and the binding identity facts -- never the description text. Rehearsal run-12 failed here
 * with only the assertion's name to go on; the response had said `blocked`/`authority-denied`. */
function describeDescriptionStatus(body: PrDescriptionStatusWireBody): string {
  const status = body.status;
  if (status === undefined) return `outcome=${body.outcome} reason=${body.reason ?? "none"}`;
  const binding = status.binding;
  return (
    `outcome=${body.outcome} state=${status.state} effect=${status.effect} ` +
    `pr=#${String(binding.prNumber)} head=${binding.headSha.slice(0, 12)} ` +
    `draft=${String(binding.isDraft)}`
  );
}

function readyDescriptionBindingMatches(
  binding: PrDescriptionStatusBinding | undefined,
  pullRequest: DeliveredPullRequest,
): boolean {
  return (
    binding?.repository === pullRequest.repository &&
    binding.prNumber === pullRequest.number &&
    binding.headRef === pullRequest.headRef &&
    binding.headSha === pullRequest.headSha &&
    !binding.isDraft
  );
}

function descriptionReconciledToReadyPullRequest(
  body: PrDescriptionStatusWireBody,
  pullRequest: DeliveredPullRequest,
): boolean {
  return (
    body.outcome === "observed" &&
    body.status !== undefined &&
    APPLIED_STATES.has(body.status.state) &&
    (body.status.effect === "confirmed" || body.status.effect === "reconciled") &&
    readyDescriptionBindingMatches(body.status.binding, pullRequest)
  );
}

/**
 * Waits for the run's own terminal-run hook to produce a GENERATED retained description proposal
 * (issue #3401), observed the way the operator observes it: the description card offers its
 * "Review exact draft" control. That control is rendered ONLY once the status carries a proposal id
 * AND a snapshot digest against an open pull request (`descriptionReviewTarget`,
 * CodingWorkbenchDraftDelivery.tsx), so its presence is the interface's own proof that a real draft
 * exists -- and, unlike a recorded field, that the operator can actually act on it.
 */
export async function waitForAutoDraftDescription(page: Page): Promise<ObservedDescriptionStatus> {
  const status = await waitWhileAnsweringApprovals(
    page,
    () => observedDescriptionStatus(page),
    (value) => value?.reviewable === true,
    {
      timeoutMs: 20 * 60_000,
      message: "expected the Code task to offer a generated retained description draft to review",
    },
  );
  if (status === undefined) {
    throw new Error("expected a displayed retained description proposal");
  }
  return status;
}

// The desktop assigns the opened window's id, and `governedPullRequest` is not a singleton window
// type -- but exactly one instance is ever opened per flow (from `applyAndRecordDescription`), and
// the Coding Workbench itself is a WindowsRegistry singleton, so this accessible region name
// (`window.type.governedPullRequest.title`) is unambiguous for the lifetime of one flow.
function governedPullRequestWindow(page: Page): Locator {
  // A WINDOW, matched by prefix. The Git window renders its own pane named exactly "Pull Request"
  // (`gitClientWindow.panel.pullRequest`), and that window is open from the base update onward for
  // every flow after the first -- so an unscoped region name could match two elements and fail
  // strict mode. Only real windows carry `data-window-id`. The prefix also survives the
  // " — selected" suffix `accessibleWindowLabel` appends to the selected window's label.
  return page.locator('section[data-window-id][aria-label^="Pull Request"]');
}

/** The independent cross-check that the reviewed proposal IS the draft the card is displaying:
 * the reviewed artifact must be bound to the exact head the description card shows. The digests
 * themselves are never rendered, so this compares the one binding fact that is -- card against
 * response, two sources, neither derived from the other. */
function assertReviewMatchesDisplayedDraft(
  body: PrDescriptionReviewWireBody,
  displayed: ObservedDescriptionStatus,
): void {
  if (body.preview.status.binding.headSha !== displayed.headSha) {
    throw new Error("retained description review did not resolve to the displayed draft");
  }
}

/** The target fields the card itself put on the wire, read back from its own request. */
function descriptionRequestTarget(response: Response): Partial<PrDescriptionRequestBody> {
  const raw = response.request().postData();
  return raw === null ? {} : (JSON.parse(raw) as Partial<PrDescriptionRequestBody>);
}

/**
 * The #3401 regression this scenario exists to pin: opening the card on the REPOSITORY root instead
 * of the run's own task workspace root resolved an empty proposal holder and answered 409 unknown
 * proposal, with every digest otherwise matching.
 *
 * The lane used to hold that by comparing against the task workspace root read from
 * `/api/task-workspaces/active`. It no longer does, and not for convenience: the product
 * deliberately never displays that path (the workspace chip was explicitly stripped of the raw
 * filesystem root, and `BoundRootTarget` is content-free by construction), so asserting against it
 * would have meant scraping a value back out of a hidden route to check something no operator can
 * see. What is checked instead is exactly what the regression was about, from the card's own
 * traffic: the scope production resolved is NOT the repository root, it names the delivered pull
 * request, and — through `assertDescriptionScopeUnchanged` below — every later description request
 * resolves that same scope. A card that fell back to the repository root fails the first check; one
 * that drifted between calls fails the second.
 */
function assertDescriptionOpenedOffRepositoryRoot(
  response: Response,
  repositoryRoot: string,
  pullRequest: DeliveredPullRequest,
): string {
  const body = descriptionRequestTarget(response);
  const { projectId } = body;
  if (
    projectId === undefined ||
    projectId.length === 0 ||
    projectId === repositoryRoot ||
    body.ownerAndRepo !== pullRequest.repository ||
    body.prNumber !== pullRequest.number
  ) {
    throw new Error(
      "retained description review did not resolve to the run's own task workspace and delivered pull request",
    );
  }
  return projectId;
}

/** Every later description request must resolve the SAME scope the review did — the scope holding
 * the retained proposal. */
function assertDescriptionScopeUnchanged(
  response: Response,
  retained: RetainedDescriptionBinding,
  action: string,
): void {
  if (descriptionRequestTarget(response).projectId !== retained.projectId) {
    throw new Error(`the description ${action} resolved a different scope than the review did`);
  }
}

/** Opens the real `governedPullRequest` window bound to the delivered PR's exact retained
 * proposal by clicking the SAME "Review exact draft" control production users click
 * (`CodingWorkbenchDraftDelivery.tsx`'s `DescriptionReviewButton`, i18n
 * "codingWorkbench.descriptionStatus.review") -- which calls `onReviewDescription` ->
 * `onOpenGit({ root, binding: "task-workspace", descriptionReview })` (`CodingWorkbenchWindow.tsx`,
 * resolving `root` from the run's OWN task workspace, never the repository root) ->
 * `widgets/index.tsx`'s "coding" registerWindowRender opening `governedPullRequest` with that
 * exact cfg, so the card's `useRetainedDescriptionProposal` effect calls the retained-review route
 * itself -- this never fills the create/update form or clicks the manual preview button. Returns
 * the retained binding once the automatic `prDescriptionReview` request has confirmed it targeted
 * the expected task workspace root and delivered pull request, and reviewed that EXACT draft (not
 * one it generated fresh). A unit test in CodingWorkbenchWindow.test.tsx ("opens the retained
 * description review on the run's task workspace root") pins the exact payload this mirrors. */
export async function mountGovernedPullRequestCard(
  page: Page,
  repositoryRoot: string,
  pullRequest: DeliveredPullRequest,
  displayed: ObservedDescriptionStatus,
): Promise<RetainedDescriptionBinding> {
  // Each of these fronts a real GitHub read or write; none may inherit the 30s action timeout.
  const reviewed = page.waitForResponse(
    (response) =>
      response.request().method() === "POST" && response.url().endsWith(REVIEW_ENDPOINT),
    { timeout: 5 * 60_000 },
  );
  await page.getByRole("button", { name: "Review exact draft", exact: true }).click();
  await expect(governedPullRequestWindow(page)).toBeVisible({ timeout: 60_000 });
  const response = await reviewed;
  const projectId = assertDescriptionOpenedOffRepositoryRoot(response, repositoryRoot, pullRequest);
  const body = (await response.json()) as PrDescriptionReviewWireBody;
  assertReviewMatchesDisplayedDraft(body, displayed);
  return {
    proposalId: body.preview.proposalId,
    snapshotDigest: body.preview.status.binding.snapshotDigest,
    draftDigest: body.preview.status.binding.draftDigest,
    projectId,
  };
}

/** Drives the real approve -> apply sequence through the governed PR card against the ALREADY
 * loaded retained proposal -- the SAME real GitHub PATCH the card issues in production -- and
 * confirms the applied artifact is the exact retained draft (`draftDigest` match), never one
 * generated anew by this scenario. */
export async function applyAutoDraftDescriptionThroughPrCard(
  page: Page,
  retained: RetainedDescriptionBinding,
): Promise<void> {
  const prWindow = governedPullRequestWindow(page);
  const card = prWindow.getByTestId("gpr-description");
  await expect(card.getByTestId("gpr-description-preview")).toBeVisible({ timeout: 60_000 });
  // The Coding Workbench window can sit over the Pull Request window it opened; an operator clicks
  // the window to bring it forward before working in it.
  await raiseWindow(page, prWindow, "Pull Request");
  await card.getByTestId("gpr-description-approve-button").click();
  await expect(card.getByTestId("gpr-description-apply-button")).toBeEnabled();
  const applied = page.waitForResponse(
    (response) => response.request().method() === "POST" && response.url().endsWith(APPLY_ENDPOINT),
    { timeout: 5 * 60_000 },
  );
  await card.getByTestId("gpr-description-apply-button").click();
  const response = await applied;
  assertDescriptionScopeUnchanged(response, retained, "apply");
  const body = (await response.json()) as PrDescriptionApplyWireBody;
  if (body.outcome !== "observed" || body.status?.binding.draftDigest !== retained.draftDigest) {
    throw new Error("applied description artifact did not match the retained automatic draft");
  }
  // Applied is any of the product's own applied states -- the exact model text, a partial one, or
  // the deterministic fallback the renderer substitutes when the model's text asserts what the
  // snapshot cannot back. The fallback is correct behaviour (rehearsal run-10 applied one), so the
  // accepted set is the contract's, never a restated "current".
  await expect(card.getByTestId("gpr-description-state")).toHaveAttribute(
    "data-state",
    APPLIED_DESCRIPTION_STATE,
    { timeout: 60_000 },
  );
}

/** Reconciles the already-applied description after the governed draft-to-ready transition. The
 * transition changes the provider's `isDraft` identity, so the pre-transition applied status is
 * deliberately stale until the status owner re-reads the remote body and persists the same
 * confirmed content against the ready PR identity.
 *
 * Driven through the REAL control a user clicks -- the governed PR card's Description panel
 * "Refresh status" button (`gpr-description-status-button`, i18n
 * "governedPullRequestCard.description.action.status"), on the card this flow already opened in
 * `mountGovernedPullRequestCard`. Until that control existed the panel could CHANGE a description
 * but never OBSERVE one: the only path to a fresh status was "Preview description", which
 * regenerates the artifact through the Model Gateway -- a paid model call to answer a read-only
 * question -- so this step reached past the UI and posted the status route itself. The window is
 * raised by its own title bar first, exactly as a user raises a window the Coding Workbench has
 * since covered. The request is read back from the network to confirm production resolved it into
 * the SAME scope the review did -- the scope holding the retained status -- where the direct call
 * this replaced targeted the repository root instead. */
export async function reconcileAppliedDescriptionAfterMarkReady(
  page: Page,
  retained: RetainedDescriptionBinding,
  pullRequest: DeliveredPullRequest,
): Promise<void> {
  const prWindow = governedPullRequestWindow(page);
  await raiseWindow(page, prWindow, "Pull Request");
  const card = prWindow.getByTestId("gpr-description");
  const refresh = card.getByTestId("gpr-description-status-button");
  await expect(refresh).toBeEnabled({ timeout: 60_000 });
  const reconciled = page.waitForResponse(
    (response) =>
      response.request().method() === "POST" && response.url().endsWith(STATUS_ENDPOINT),
    { timeout: 5 * 60_000 },
  );
  await refresh.click();
  const response = await reconciled;
  expect(
    response.ok(),
    `description reconciliation failed with HTTP ${String(response.status())}`,
  ).toBe(true);
  assertDescriptionScopeUnchanged(response, retained, "refresh");
  const body = (await response.json()) as PrDescriptionStatusWireBody;
  if (!descriptionReconciledToReadyPullRequest(body, pullRequest)) {
    throw new Error(
      "description was not reconciled to the exact ready pull request identity: " +
        describeDescriptionStatus(body),
    );
  }
  // Applied is any of the product's own applied states -- the exact model text, a partial one, or
  // the deterministic fallback the renderer substitutes when the model's text asserts what the
  // snapshot cannot back. The fallback is correct behaviour (rehearsal run-10 applied one), so the
  // accepted set is the contract's, never a restated "current".
  await expect(card.getByTestId("gpr-description-state")).toHaveAttribute(
    "data-state",
    APPLIED_DESCRIPTION_STATE,
    { timeout: 60_000 },
  );
}
