// #3390 — the auto-draft-and-apply description scenario. `descriptionStatus` (issue #3401) is
// produced automatically by the server's own terminal-run hook once the live run's head is
// stable; applying it never happens through that hook (#3401 correction 1: "never applies a
// description") -- it goes through #3399's EXISTING PR preview/approve/apply flow, exactly what
// the standalone `GovernedPullRequestCard` window already drives in the scripted
// `git-change-chat-3400.spec.ts` sibling ("qualifies the governed PR Description panel"). This
// module reuses that SAME card/testids against the real created draft PR instead of a second
// description-apply surface.
//
// Review 3941762922: applying the RETAINED automatic draft (the exact artifact #3401 already
// generated -- `proposalId`/`snapshotDigest`/`draftDigest`) is the #3390 acceptance criterion, not
// a fresh description generated by this scenario's own manual "Preview" click. The card's own
// retained-proposal path (`GovernedPullRequestCard`'s `descriptionProposal` prop ->
// `useRetainedDescriptionProposal` -> `prDescriptionReview`, reached in production through
// `CodingWorkbenchWindow`'s "Review description" control) is reused here by opening the window
// with the SAME cfg fields that control populates (`descriptionOwnerAndRepo`/`descriptionPrNumber`/
// `descriptionProposalId`/`descriptionSnapshotDigest`, `widgets/index.tsx`'s `governedPullRequest`
// render), instead of filling the create/update form and clicking the manual preview button.

import { expect, type Page } from "@playwright/test";
import type { WorkbenchDescriptionStatus } from "@oscharko-dev/keiko-contracts";
import { runtimeSnapshot, waitWhileAnsweringApprovals } from "./coding-issue-journey-live.js";
import type { DeliveredPullRequest } from "./coding-issue-journey-live.js";

const GOVERNED_PR_WINDOW_ID = "coding-issue-journey-governed-pr";
const REVIEW_ENDPOINT = "/api/git-delivery/pr-description/review";
const APPLY_ENDPOINT = "/api/git-delivery/pr-description/apply";

/** The exact retained artifact identity #3401 already generated -- captured once from the
 * automatic status and carried through review/approve/apply so every step can be checked against
 * the SAME draft rather than one this scenario generated itself. */
export interface RetainedDescriptionBinding {
  readonly proposalId: string;
  readonly snapshotDigest: string;
  readonly draftDigest: string;
}

interface PrDescriptionReviewWireBody {
  readonly preview: {
    readonly proposalId: string;
    readonly status: {
      readonly binding: { readonly snapshotDigest: string; readonly draftDigest: string };
    };
  };
}

interface PrDescriptionApplyWireBody {
  readonly outcome: string;
  readonly status?: { readonly binding: { readonly draftDigest: string } };
}

/** Waits for the run's own terminal-run hook to record a GENERATED retained description proposal
 * (issue #3401) -- never any recorded status, and never a blocked attempt. `proposalId` is present
 * only for the `current | partial | fallback` states (`WorkbenchDescriptionStatus`'s own
 * `validProposal` invariant), which is exactly "a real draft exists to review", so waiting on it
 * rather than mere presence of `descriptionStatus` is what proves a draft was actually produced. */
export async function waitForAutoDraftDescription(page: Page): Promise<WorkbenchDescriptionStatus> {
  const snapshot = await waitWhileAnsweringApprovals(
    page,
    () => runtimeSnapshot(page),
    (value) => value.descriptionStatus?.proposalId !== undefined,
    {
      timeoutMs: 20 * 60_000,
      message: "expected a generated retained description proposal to be recorded",
    },
  );
  const status = snapshot.descriptionStatus;
  if (status?.proposalId === undefined) {
    throw new Error("expected a recorded retained description proposal");
  }
  return status;
}

function retainedBindingOf(status: WorkbenchDescriptionStatus): RetainedDescriptionBinding {
  if (
    status.proposalId === undefined ||
    status.snapshotDigest === null ||
    status.draftDigest === null
  ) {
    throw new Error("expected a generated retained description proposal to mount");
  }
  return {
    proposalId: status.proposalId,
    snapshotDigest: status.snapshotDigest,
    draftDigest: status.draftDigest,
  };
}

interface GovernedPullRequestWindowInput {
  readonly repositoryRoot: string;
  readonly pullRequest: DeliveredPullRequest;
  readonly retained: RetainedDescriptionBinding;
}

/** The window-seeding half of `mountGovernedPullRequestCard`, extracted only to keep that
 * function under the function-size bar (AGENTS.md §6) -- pushes the SAME cfg shape
 * `CodingWorkbenchWindow`'s "Review description" control produces. */
async function pushGovernedPullRequestWindow(
  page: Page,
  input: GovernedPullRequestWindowInput,
): Promise<void> {
  await page.evaluate(
    ({
      windowId,
      projectPath,
      headBranchName,
      ownerAndRepo,
      prNumber,
      proposalId,
      snapshotDigest,
    }) => {
      const raw = window.localStorage.getItem("keiko.workspace.v4");
      const windows: unknown[] = raw === null ? [] : (JSON.parse(raw) as unknown[]);
      windows.push({
        id: windowId,
        type: "governedPullRequest",
        x: 60,
        y: 60,
        w: 760,
        h: 900,
        z: 30,
        cfg: {
          projectPath,
          headBranchName,
          descriptionOwnerAndRepo: ownerAndRepo,
          descriptionPrNumber: prNumber,
          descriptionProposalId: proposalId,
          descriptionSnapshotDigest: snapshotDigest,
        },
        max: false,
      });
      window.localStorage.setItem("keiko.workspace.v4", JSON.stringify(windows));
    },
    {
      windowId: GOVERNED_PR_WINDOW_ID,
      projectPath: input.repositoryRoot,
      headBranchName: input.pullRequest.headRef,
      ownerAndRepo: input.pullRequest.repository,
      prNumber: input.pullRequest.number,
      proposalId: input.retained.proposalId,
      snapshotDigest: input.retained.snapshotDigest,
    },
  );
}

function assertReviewMatchesRetained(
  body: PrDescriptionReviewWireBody,
  retained: RetainedDescriptionBinding,
): void {
  if (
    body.preview.proposalId !== retained.proposalId ||
    body.preview.status.binding.snapshotDigest !== retained.snapshotDigest ||
    body.preview.status.binding.draftDigest !== retained.draftDigest
  ) {
    throw new Error("retained description review did not resolve to the automatic draft");
  }
}

/** Adds a real `governedPullRequest` window to the live desktop session bound to the delivered
 * PR's exact retained proposal, mirroring `CodingWorkbenchWindow`'s own "Review description"
 * control (`onOpenGit({ ..., descriptionReview })` -> `widgets/index.tsx`'s `governedPullRequest`
 * cfg) so the card's `useRetainedDescriptionProposal` effect calls the retained-review route
 * itself -- this never fills the create/update form or clicks the manual preview button. Returns
 * the retained binding once the automatic `prDescriptionReview` response has confirmed it reviewed
 * that EXACT draft (not one it generated fresh). */
export async function mountGovernedPullRequestCard(
  page: Page,
  repositoryRoot: string,
  pullRequest: DeliveredPullRequest,
  status: WorkbenchDescriptionStatus,
): Promise<RetainedDescriptionBinding> {
  const retained = retainedBindingOf(status);
  const reviewed = page.waitForResponse(
    (response) =>
      response.request().method() === "POST" && response.url().endsWith(REVIEW_ENDPOINT),
  );
  await pushGovernedPullRequestWindow(page, { repositoryRoot, pullRequest, retained });
  await page.reload();
  await expect(page.locator(`[data-window-id="${GOVERNED_PR_WINDOW_ID}"]`)).toBeVisible();
  const response = await reviewed;
  assertReviewMatchesRetained((await response.json()) as PrDescriptionReviewWireBody, retained);
  return retained;
}

/** Drives the real approve -> apply sequence through the governed PR card against the ALREADY
 * loaded retained proposal -- the SAME real GitHub PATCH the card issues in production -- and
 * confirms the applied artifact is the exact retained draft (`draftDigest` match), never one
 * generated anew by this scenario. */
export async function applyAutoDraftDescriptionThroughPrCard(
  page: Page,
  retained: RetainedDescriptionBinding,
): Promise<void> {
  const card = page
    .locator(`[data-window-id="${GOVERNED_PR_WINDOW_ID}"]`)
    .getByTestId("gpr-description");
  await expect(card.getByTestId("gpr-description-preview")).toBeVisible({ timeout: 60_000 });
  await card.getByTestId("gpr-description-approve-button").click();
  await expect(card.getByTestId("gpr-description-apply-button")).toBeEnabled();
  const applied = page.waitForResponse(
    (response) => response.request().method() === "POST" && response.url().endsWith(APPLY_ENDPOINT),
  );
  await card.getByTestId("gpr-description-apply-button").click();
  const response = await applied;
  const body = (await response.json()) as PrDescriptionApplyWireBody;
  if (body.outcome !== "observed" || body.status?.binding.draftDigest !== retained.draftDigest) {
    throw new Error("applied description artifact did not match the retained automatic draft");
  }
  await expect(card.getByTestId("gpr-description-state")).toHaveAttribute("data-state", "current", {
    timeout: 60_000,
  });
}
