// #3390 — the auto-draft-and-apply description scenario. `descriptionStatus` (issue #3401) is
// produced automatically by the server's own terminal-run hook once the live run's head is
// stable; applying it never happens through that hook (#3401 correction 1: "never applies a
// description") -- it goes through #3399's EXISTING PR preview/approve/apply flow, exactly what
// the standalone `GovernedPullRequestCard` window already drives in the scripted
// `git-change-chat-3400.spec.ts` sibling ("qualifies the governed PR Description panel"). This
// module reuses that SAME card/testids against the real created draft PR instead of a second
// description-apply surface.
//
// Review 3941762922: applying the RETAINED automatic draft (the exact artifact #3401 already
// generated -- `proposalId`/`snapshotDigest`/`draftDigest`) is the #3390 acceptance criterion, not
// a fresh description generated by this scenario's own manual "Preview" click. The card's own
// retained-proposal path (`GovernedPullRequestCard`'s `descriptionProposal` prop ->
// `useRetainedDescriptionProposal` -> `prDescriptionReview`, reached in production through
// `CodingWorkbenchWindow`'s "Review description" control) is reused here by opening the window
// with the SAME cfg fields that control populates (`descriptionOwnerAndRepo`/`descriptionPrNumber`/
// `descriptionProposalId`/`descriptionSnapshotDigest`, `widgets/index.tsx`'s `governedPullRequest`
// render), instead of filling the create/update form and clicking the manual preview button.

import { expect, type Locator, type Page, type Response } from "@playwright/test";
import type { WorkbenchDescriptionStatus } from "@oscharko-dev/keiko-contracts";
import { runtimeSnapshot, waitWhileAnsweringApprovals } from "./coding-issue-journey-live.js";
import type { DeliveredPullRequest } from "./coding-issue-journey-live.js";

const REVIEW_ENDPOINT = "/api/git-delivery/pr-description/review";
const APPLY_ENDPOINT = "/api/git-delivery/pr-description/apply";
const STATUS_ENDPOINT = "/api/git-delivery/pr-description/status";

/** The exact retained artifact identity #3401 already generated -- captured once from the
 * automatic status and carried through review/approve/apply so every step can be checked against
 * the SAME draft rather than one this scenario generated itself. */
export interface RetainedDescriptionBinding {
  readonly proposalId: string;
  readonly snapshotDigest: string;
  readonly draftDigest: string;
}

interface PrDescriptionReviewWireBody {
  readonly preview: {
    readonly proposalId: string;
    readonly status: {
      readonly binding: { readonly snapshotDigest: string; readonly draftDigest: string };
    };
  };
}

/** The target fields every description request carries (`GitDeliveryPrDescriptionTarget`, api.ts)
 * -- read back from the network request (never constructed by this test) to confirm production
 * resolved the click to the run's task workspace root and the delivered pull request, not merely to
 * a proposal whose digests happen to match. */
interface PrDescriptionRequestBody {
  readonly projectId: string;
  readonly ownerAndRepo: string;
  readonly prNumber: number;
}

interface PrDescriptionApplyWireBody {
  readonly outcome: string;
  readonly status?: { readonly binding: { readonly draftDigest: string } };
}

interface PrDescriptionStatusBinding {
  readonly repository: string;
  readonly prNumber: number;
  readonly headRef: string;
  readonly headSha: string;
  readonly isDraft: boolean;
}

interface PrDescriptionStatusWireBody {
  readonly outcome: string;
  readonly status?: {
    readonly state: string;
    readonly effect: string;
    readonly binding: PrDescriptionStatusBinding;
  };
}

function readyDescriptionBindingMatches(
  binding: PrDescriptionStatusBinding | undefined,
  pullRequest: DeliveredPullRequest,
): boolean {
  return (
    binding?.repository === pullRequest.repository &&
    binding.prNumber === pullRequest.number &&
    binding.headRef === pullRequest.headRef &&
    binding.headSha === pullRequest.headSha &&
    !binding.isDraft
  );
}

function descriptionReconciledToReadyPullRequest(
  body: PrDescriptionStatusWireBody,
  pullRequest: DeliveredPullRequest,
): boolean {
  return (
    body.outcome === "observed" &&
    body.status?.state === "current" &&
    (body.status.effect === "confirmed" || body.status.effect === "reconciled") &&
    readyDescriptionBindingMatches(body.status.binding, pullRequest)
  );
}

/** Waits for the run's own terminal-run hook to record a GENERATED retained description proposal
 * (issue #3401) -- never any recorded status, and never a blocked attempt. `proposalId` is present
 * only for the `current | partial | fallback` states (`WorkbenchDescriptionStatus`'s own
 * `validProposal` invariant), which is exactly "a real draft exists to review", so waiting on it
 * rather than mere presence of `descriptionStatus` is what proves a draft was actually produced. */
export async function waitForAutoDraftDescription(page: Page): Promise<WorkbenchDescriptionStatus> {
  const snapshot = await waitWhileAnsweringApprovals(
    page,
    () => runtimeSnapshot(page),
    (value) => value.descriptionStatus?.proposalId !== undefined,
    {
      timeoutMs: 20 * 60_000,
      message: "expected a generated retained description proposal to be recorded",
    },
  );
  const status = snapshot.descriptionStatus;
  if (status?.proposalId === undefined) {
    throw new Error("expected a recorded retained description proposal");
  }
  return status;
}

function retainedBindingOf(status: WorkbenchDescriptionStatus): RetainedDescriptionBinding {
  if (
    status.proposalId === undefined ||
    status.snapshotDigest === null ||
    status.draftDigest === null
  ) {
    throw new Error("expected a generated retained description proposal to mount");
  }
  return {
    proposalId: status.proposalId,
    snapshotDigest: status.snapshotDigest,
    draftDigest: status.draftDigest,
  };
}

// The desktop assigns the opened window's id, and `governedPullRequest` is not a singleton window
// type -- but exactly one instance is ever opened per flow (from `applyAndRecordDescription`), and
// the Coding Workbench itself is a WindowsRegistry singleton, so this accessible region name
// (`window.type.governedPullRequest.title`) is unambiguous for the lifetime of one flow.
function governedPullRequestWindow(page: Page): Locator {
  return page.getByRole("region", { name: "Pull Request", exact: true });
}

function assertReviewMatchesRetained(
  body: PrDescriptionReviewWireBody,
  retained: RetainedDescriptionBinding,
): void {
  if (
    body.preview.proposalId !== retained.proposalId ||
    body.preview.status.binding.snapshotDigest !== retained.snapshotDigest ||
    body.preview.status.binding.draftDigest !== retained.draftDigest
  ) {
    throw new Error("retained description review did not resolve to the automatic draft");
  }
}

/** Confirms the REAL click resolved `root`/PR the same way `descriptionReviewTarget`
 * (CodingWorkbenchDraftDelivery.tsx) and `onReviewDescription` (CodingWorkbenchWindow.tsx) compute
 * it in production -- read from the request the card actually issued, never constructed by this
 * test. This is the #3401 regression this scenario exists to pin: opening the card on the
 * repository root instead of the run's task workspace root resolved an empty proposal holder and
 * answered 409 unknown proposal with the SAME digests otherwise matching. The status refresh below
 * is held to the identical binding, because it reads the status the SAME retained scope owns. */
function assertDescriptionRequestTargetedTaskWorkspace(
  response: Response,
  expectedRoot: string,
  pullRequest: DeliveredPullRequest,
  action: string,
): void {
  const raw = response.request().postData();
  const body: Partial<PrDescriptionRequestBody> =
    raw === null ? {} : (JSON.parse(raw) as Partial<PrDescriptionRequestBody>);
  if (
    body.projectId !== expectedRoot ||
    body.ownerAndRepo !== pullRequest.repository ||
    body.prNumber !== pullRequest.number
  ) {
    throw new Error(
      `retained description ${action} did not resolve to the run's task workspace root and delivered pull request`,
    );
  }
}

/** Opens the real `governedPullRequest` window bound to the delivered PR's exact retained
 * proposal by clicking the SAME "Review exact draft" control production users click
 * (`CodingWorkbenchDraftDelivery.tsx`'s `DescriptionReviewButton`, i18n
 * "codingWorkbench.descriptionStatus.review") -- which calls `onReviewDescription` ->
 * `onOpenGit({ root, binding: "task-workspace", descriptionReview })` (`CodingWorkbenchWindow.tsx`,
 * resolving `root` from the run's OWN task workspace, never the repository root) ->
 * `widgets/index.tsx`'s "coding" registerWindowRender opening `governedPullRequest` with that
 * exact cfg, so the card's `useRetainedDescriptionProposal` effect calls the retained-review route
 * itself -- this never fills the create/update form or clicks the manual preview button. Returns
 * the retained binding once the automatic `prDescriptionReview` request has confirmed it targeted
 * the expected task workspace root and delivered pull request, and reviewed that EXACT draft (not
 * one it generated fresh). A unit test in CodingWorkbenchWindow.test.tsx ("opens the retained
 * description review on the run's task workspace root") pins the exact payload this mirrors. */
export async function mountGovernedPullRequestCard(
  page: Page,
  repositoryRoot: string,
  pullRequest: DeliveredPullRequest,
  status: WorkbenchDescriptionStatus,
): Promise<RetainedDescriptionBinding> {
  const retained = retainedBindingOf(status);
  const reviewed = page.waitForResponse(
    (response) =>
      response.request().method() === "POST" && response.url().endsWith(REVIEW_ENDPOINT),
  );
  await page.getByRole("button", { name: "Review exact draft", exact: true }).click();
  await expect(governedPullRequestWindow(page)).toBeVisible({ timeout: 60_000 });
  const response = await reviewed;
  assertDescriptionRequestTargetedTaskWorkspace(response, repositoryRoot, pullRequest, "review");
  assertReviewMatchesRetained((await response.json()) as PrDescriptionReviewWireBody, retained);
  return retained;
}

/** Drives the real approve -> apply sequence through the governed PR card against the ALREADY
 * loaded retained proposal -- the SAME real GitHub PATCH the card issues in production -- and
 * confirms the applied artifact is the exact retained draft (`draftDigest` match), never one
 * generated anew by this scenario. */
export async function applyAutoDraftDescriptionThroughPrCard(
  page: Page,
  retained: RetainedDescriptionBinding,
): Promise<void> {
  const card = governedPullRequestWindow(page).getByTestId("gpr-description");
  await expect(card.getByTestId("gpr-description-preview")).toBeVisible({ timeout: 60_000 });
  await card.getByTestId("gpr-description-approve-button").click();
  await expect(card.getByTestId("gpr-description-apply-button")).toBeEnabled();
  const applied = page.waitForResponse(
    (response) => response.request().method() === "POST" && response.url().endsWith(APPLY_ENDPOINT),
  );
  await card.getByTestId("gpr-description-apply-button").click();
  const response = await applied;
  const body = (await response.json()) as PrDescriptionApplyWireBody;
  if (body.outcome !== "observed" || body.status?.binding.draftDigest !== retained.draftDigest) {
    throw new Error("applied description artifact did not match the retained automatic draft");
  }
  await expect(card.getByTestId("gpr-description-state")).toHaveAttribute("data-state", "current", {
    timeout: 60_000,
  });
}

/** Reconciles the already-applied description after the governed draft-to-ready transition. The
 * transition changes the provider's `isDraft` identity, so the pre-transition applied status is
 * deliberately stale until the status owner re-reads the remote body and persists the same
 * confirmed content against the ready PR identity.
 *
 * Driven through the REAL control a user clicks -- the governed PR card's Description panel
 * "Refresh status" button (`gpr-description-status-button`, i18n
 * "governedPullRequestCard.description.action.status"), on the card this flow already opened in
 * `mountGovernedPullRequestCard`. Until that control existed the panel could CHANGE a description
 * but never OBSERVE one: the only path to a fresh status was "Preview description", which
 * regenerates the artifact through the Model Gateway -- a paid model call to answer a read-only
 * question -- so this step reached past the UI and posted the status route itself. The window is
 * raised by its own title bar first, exactly as a user raises a window the Coding Workbench has
 * since covered. The request is read back from the network to confirm production resolved the click
 * to the run's task workspace root, which is the scope holding the retained status -- the previous
 * direct call targeted the repository root instead. */
export async function reconcileAppliedDescriptionAfterMarkReady(
  page: Page,
  workspaceRoot: string,
  pullRequest: DeliveredPullRequest,
): Promise<void> {
  const prWindow = governedPullRequestWindow(page);
  await prWindow.locator("header.win-head").click();
  const card = prWindow.getByTestId("gpr-description");
  const refresh = card.getByTestId("gpr-description-status-button");
  await expect(refresh).toBeEnabled({ timeout: 60_000 });
  const reconciled = page.waitForResponse(
    (response) =>
      response.request().method() === "POST" && response.url().endsWith(STATUS_ENDPOINT),
  );
  await refresh.click();
  const response = await reconciled;
  expect(
    response.ok(),
    `description reconciliation failed with HTTP ${String(response.status())}`,
  ).toBe(true);
  assertDescriptionRequestTargetedTaskWorkspace(response, workspaceRoot, pullRequest, "refresh");
  const body = (await response.json()) as PrDescriptionStatusWireBody;
  if (!descriptionReconciledToReadyPullRequest(body, pullRequest)) {
    throw new Error("description was not reconciled to the exact ready pull request identity");
  }
  await expect(card.getByTestId("gpr-description-state")).toHaveAttribute("data-state", "current", {
    timeout: 60_000,
  });
}
