import { defineConfig, devices } from "@playwright/test";
import { realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const root = process.cwd();
const publicPort = Number(process.env.KEIKO_LK_E2E_UI_PORT ?? "42183");
const bffPort = Number(process.env.KEIKO_LK_E2E_BFF_PORT ?? "42184");
const nextPort = Number(process.env.KEIKO_LK_E2E_NEXT_PORT ?? "42185");
// GEN-TEST-E2E-007: the corpus is regenerated by the spec's ensureCorpus(), so it only needs a
// writable root. Default to a portable temp path instead of a hardcoded owner-machine home
// directory, and publish it via process.env BEFORE Playwright forks worker processes so the spec
// (which reads the same var) resolves the identical root. A curated real corpus is still honored via
// KEIKO_LK_E2E_CORPUS.
process.env.KEIKO_LK_E2E_CORPUS ??= join(realpathSync(tmpdir()), "keiko-local-knowledge-e2e");
const corpusRoot = process.env.KEIKO_LK_E2E_CORPUS;
const corpusDataRoot = join(corpusRoot, "fixtures");
const stateDir = process.env.KEIKO_LK_E2E_STATE_DIR ?? join(corpusRoot, "state");

// #2485: hand the server a COPY of the checked-in fixture config, mirroring the generic e2e
// config. The BFF's credential migration rewrites the config file it is given (apiKey →
// apiKeySecretRef + vault sibling directory); pointed at the repository file it mutates the
// working tree on every boot.
const fixtureConfigPath = join(
  root,
  "tests",
  "e2e",
  "fixtures",
  "keiko.local-knowledge.e2e.config.json",
);
const runtimeConfigPath = join(stateDir, "keiko.local-knowledge.e2e.config.json");
const prepareRuntimeConfig = [
  "const fs = require('node:fs');",
  `fs.mkdirSync(${JSON.stringify(stateDir)}, { recursive: true });`,
  `fs.copyFileSync(${JSON.stringify(fixtureConfigPath)}, ${JSON.stringify(runtimeConfigPath)});`,
].join(" ");

export default defineConfig({
  testDir: join(root, "tests", "e2e"),
  testMatch: /local-knowledge-regression\.spec\.ts/u,
  fullyParallel: false,
  workers: 1,
  timeout: 90 * 60_000,
  expect: {
    timeout: 30_000,
  },
  reporter: process.env.CI ? [["github"], ["line"]] : "line",
  use: {
    baseURL: `http://127.0.0.1:${String(publicPort)}`,
    trace: "retain-on-failure",
    video: "retain-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    cwd: root,
    command:
      `node -e ${JSON.stringify(prepareRuntimeConfig)} && ` +
      "npm run build:packages && node tests/e2e/fixtures/local-knowledge-e2e-server.js",
    url: `http://127.0.0.1:${String(publicPort)}`,
    reuseExistingServer: false,
    timeout: 180_000,
    env: {
      KEIKO_DEV_UI_PORT: String(publicPort),
      KEIKO_DEV_BFF_PORT: String(bffPort),
      KEIKO_DEV_NEXT_PORT: String(nextPort),
      KEIKO_DEV_MAX_RESTARTS: "0",
      // #2485: same hermetic-boot flags as the generic e2e config — the dev runner's package
      // watch can rewrite packages/*/dist while the BFF serves, producing transient API 502s
      // (observed as a 502 on the first capsule-create POST of the campaign), and a BFF watch
      // restart leaves the proxy claiming ready while the port is briefly unavailable.
      KEIKO_DEV_TEST_SKIP_PACKAGE_WATCH: "1",
      KEIKO_DEV_TEST_SKIP_BFF_WATCH: "1",
      KEIKO_DEV_NEXT_BUNDLER: "webpack",
      KEIKO_STATE_DIR: stateDir,
      KEIKO_UI_DATA_DIR: join(stateDir, "ui"),
      KEIKO_MEMORY_DIR: join(stateDir, "memory"),
      KEIKO_INITIAL_PROJECT_PATH: corpusDataRoot,
      KEIKO_CONFIG_FILE: runtimeConfigPath,
      KEIKO_LK_E2E_MOCK_GATEWAY_PORT: "42186",
      // Issue #1286: drive the bounded large-document path for any PDF so the regression exercises
      // progressive extraction + bounded chunk/embed + the large-document health UI without needing
      // a multi-hundred-MiB binary fixture.
      KEIKO_LK_LARGE_DOC_THRESHOLD_BYTES: process.env.KEIKO_LK_LARGE_DOC_THRESHOLD_BYTES ?? "1024",
    },
  },
});
