// Re-export shim: the workflows layer now lives in @oscharko-dev/keiko-workflows
// (issue #165, ADR-0019). Existing consumers (`src/cli`, `src/sdk`, `src/evaluations`,
// `src/ui`) import from the legacy path; this shim preserves those import paths.
// Explicit-named re-exports (no `export *`) keep the surface auditable.

export {
  generateUnitTests,
  investigateBug,
  renderMarkdownReport,
  renderBugMarkdownReport,
  assembleReport,
  assembleBugReport,
  detectConventions,
  isTestPath,
  isSensitivePath,
  isElevatedReviewPath,
  parseFailureEvidence,
  MAX_FRAMES,
  UNIT_TEST_WORKFLOW_DESCRIPTOR,
  BUG_INVESTIGATION_WORKFLOW_DESCRIPTOR,
  DEFAULT_WORKFLOW_LIMITS,
  DEFAULT_BUG_WORKFLOW_LIMITS,
} from "@oscharko-dev/keiko-workflows";

export type {
  WorkflowDescriptor,
  WorkflowInputSpec,
  ReportParts,
  BugReportParts,
  AddedTestFile,
  FileNamingStyle,
  TestConventions,
  UnitTestTarget,
  UnitTestWorkflowDeps,
  UnitTestWorkflowInput,
  UnitTestWorkflowReport,
  WorkflowLimits,
  WorkflowStatus,
  BugInvestigationInput,
  BugInvestigationDeps,
  BugInvestigationReport,
  BugReportInput,
  BugWorkflowLimits,
  BugWorkflowStatus,
  ChangedFile,
  FailureEvidence,
  FailureFrame,
  Hypothesis,
  ParsedBugOutput,
  VerifiedFindings,
  ConventionsDetectedEvent,
  ContextSelectedEvent,
  ModelCallCompletedEvent,
  ModelCallStartedEvent,
  PatchAppliedEvent,
  PatchValidatedEvent,
  VerificationResultEvent,
  WorkflowCompletedEvent,
  WorkflowEvent,
  WorkflowEventSink,
  WorkflowFailedEvent,
  WorkflowStartedEvent,
  BugContextSelectedEvent,
  BugInvestigationCompletedEvent,
  BugInvestigationEvent,
  BugInvestigationFailedEvent,
  BugInvestigationStartedEvent,
  BugModelCallCompletedEvent,
  BugModelCallStartedEvent,
  BugPatchAppliedEvent,
  BugPatchValidatedEvent,
  BugVerificationResultEvent,
  BugWorkflowEventSink,
  FailureParsedEvent,
  RootCauseProposedEvent,
} from "@oscharko-dev/keiko-workflows";
