import { defineActivityLogOperation } from "@oscharko-dev/keiko-contracts/runtime/observability";

export const CODING_RUNTIME_TOOL_RESULT_OPERATION = defineActivityLogOperation({
  contractKind: "activity-log-operation",
  schemaVersion: 1,
  op: "coding-runtime.tool-result",
  category: "process",
  owner: "keiko-server",
  emitter: "coding-runtime.shared.codingRuntimeToolResult",
  fields: {
    actionKind: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: [
        "read",
        "discover",
        "search",
        "edit",
        "command",
        "verification",
        "git",
        "delivery",
        "connector",
        "egress",
        "skill",
        "skill-discover",
        "child-agent",
        "git-stage",
        "commit",
        "push",
        "pull-request",
      ],
    },
    state: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: ["discarded", "proposal-ready", "approval-wait-settled", "approval-wait-failed"],
    },
    reason: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: [
        "authority-denied",
        "policy-authorized",
        "approved",
        "cancelled",
        "expired",
        "unavailable",
        "authority-resolution-failed",
      ],
    },
    proposalId: {
      type: "string",
      dataClass: "opaque-id",
      required: false,
      maxLength: 128,
    },
    waitCeilingMs: { type: "integer", dataClass: "duration", required: false },
    frames: {
      type: "string-array",
      dataClass: "opaque-id",
      required: false,
      maxLength: 512,
      maxItems: 8,
    },
    causeChain: {
      type: "string-array",
      dataClass: "error-kind",
      required: false,
      maxLength: 128,
      maxItems: 5,
    },
  },
  causal: "correlation",
  lifecycle: "state",
  analyzerProjection: "process-lifecycle",
  failureClasses: ["coding-runtime-tool-result"],
  proofIds: ["coding-runtime.tool-result.emitted-line"],
  releaseImpact: "patch",
});

export const RUNTIME_CONFINEMENT_FAILED_OPERATION = defineActivityLogOperation({
  contractKind: "activity-log-operation",
  schemaVersion: 1,
  op: "runtime.confinement.failed",
  category: "process",
  owner: "keiko-server",
  emitter: "coding-runtime.shared.runtimeConfinementFailed",
  fields: {
    backend: {
      type: "string",
      dataClass: "closed-enum",
      required: false,
      values: ["bubblewrap", "unshare", "seatbelt", "none"],
    },
    diagnosticSource: {
      type: "string",
      dataClass: "closed-enum",
      required: false,
      values: ["linux-gateway-launcher"],
    },
    diagnosticKind: {
      type: "string",
      dataClass: "closed-enum",
      required: false,
      values: [
        "cleanup-failed",
        "host-relay-failed",
        "internal-failure",
        "invalid-backend",
        "invalid-command",
        "invalid-cwd",
        "invalid-gateway-host",
        "invalid-gateway-port",
        "invalid-mode",
        "loopback-setup-failed",
        "loopback-tool-unavailable",
        "namespace-relay-failed",
        "unsupported-platform",
      ],
    },
    frames: {
      type: "string-array",
      dataClass: "opaque-id",
      required: true,
      maxLength: 512,
      maxItems: 8,
    },
    causeChain: {
      type: "string-array",
      dataClass: "error-kind",
      required: true,
      maxLength: 128,
      maxItems: 5,
    },
  },
  causal: "correlation",
  lifecycle: "failure",
  analyzerProjection: "failure-cluster",
  failureClasses: ["runtime-confinement"],
  proofIds: ["runtime.confinement.failed.emitted-line"],
  releaseImpact: "patch",
});

export const RUNTIME_CONFINEMENT_UNAVAILABLE_OPERATION = defineActivityLogOperation({
  contractKind: "activity-log-operation",
  schemaVersion: 1,
  op: "runtime.confinement.unavailable",
  category: "process",
  owner: "keiko-server",
  emitter: "coding-runtime.shared.runtimeConfinementUnavailable",
  fields: {
    platform: {
      type: "string",
      dataClass: "safe-platform-class",
      required: true,
      values: ["darwin", "linux", "win32"],
    },
    arch: {
      type: "string",
      dataClass: "safe-platform-class",
      required: true,
      values: ["arm64", "x64"],
    },
    backend: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: [
        "linux-namespace-gateway",
        "macos-app-sandbox",
        "macos-endpoint-security",
        "windows-job-object",
      ],
    },
  },
  causal: "correlation",
  lifecycle: "state",
  analyzerProjection: "capability",
  failureClasses: ["runtime-confinement-unavailable"],
  proofIds: ["runtime.confinement.unavailable.emitted-line"],
  releaseImpact: "patch",
});

export const RUNTIME_CONFINEMENT_SPAWNED_OPERATION = defineActivityLogOperation({
  contractKind: "activity-log-operation",
  schemaVersion: 1,
  op: "runtime.confinement.spawned",
  category: "process",
  owner: "keiko-server",
  emitter: "coding-runtime.shared.runtimeConfinementSpawned",
  fields: {
    backend: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: ["bubblewrap", "unshare", "seatbelt"],
    },
    policyDigest: { type: "string", dataClass: "digest", required: true, maxLength: 64 },
    authorityDigest: { type: "string", dataClass: "digest", required: true, maxLength: 64 },
    runtimeArtifactDigest: {
      type: "string",
      dataClass: "digest",
      required: true,
      maxLength: 64,
    },
    modelProfileDigest: { type: "string", dataClass: "digest", required: true, maxLength: 64 },
    treeBindingId: { type: "string", dataClass: "opaque-id", required: true, maxLength: 128 },
    profile: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: ["keiko-gateway"],
    },
    childExecutablePolicy: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: ["namespace-inherited", "runtime-and-attested-git-only"],
    },
    childExecutableDigest: {
      type: "string",
      dataClass: "digest",
      required: false,
      maxLength: 64,
    },
  },
  causal: "correlation",
  lifecycle: "start",
  analyzerProjection: "process-lifecycle",
  failureClasses: ["runtime-confinement"],
  proofIds: ["runtime.confinement.spawned.emitted-line"],
  releaseImpact: "patch",
});

export const GIT_VERIFIED_COMMIT_AUTHORITY_OPERATION = defineActivityLogOperation({
  contractKind: "activity-log-operation",
  schemaVersion: 1,
  op: "git.verified-commit.authority",
  category: "process",
  owner: "keiko-server",
  emitter: "coding-runtime.shared.gitVerifiedCommitAuthority",
  fields: {
    phase: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: ["retained", "read"],
    },
    runId: { type: "string", dataClass: "opaque-id", required: true, maxLength: 128 },
    proposalId: {
      type: "string",
      dataClass: "opaque-id",
      required: false,
      maxLength: 128,
    },
    headSha: { type: "string", dataClass: "digest", required: false, maxLength: 64 },
    frames: {
      type: "string-array",
      dataClass: "opaque-id",
      required: false,
      maxLength: 512,
      maxItems: 8,
    },
    causeChain: {
      type: "string-array",
      dataClass: "error-kind",
      required: false,
      maxLength: 128,
      maxItems: 5,
    },
  },
  causal: "correlation",
  lifecycle: "state",
  analyzerProjection: "timeline",
  failureClasses: ["verified-commit-authority"],
  proofIds: ["git.verified-commit.authority.emitted-line"],
  releaseImpact: "patch",
});
