import { defineActivityLogOperation } from "@oscharko-dev/keiko-contracts/runtime/observability";

export const CODING_RUNTIME_TOOL_RESULT_OPERATION = defineActivityLogOperation({
  contractKind: "activity-log-operation",
  schemaVersion: 1,
  op: "coding-runtime.tool-result",
  category: "process",
  owner: "keiko-server",
  emitter: "coding-runtime.shared.codingRuntimeToolResult",
  fields: {
    actionKind: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: [
        "read",
        "discover",
        "search",
        "edit",
        "command",
        "verification",
        "git",
        "delivery",
        "connector",
        "egress",
        "skill",
        "skill-discover",
        "child-agent",
        "git-stage",
        "commit",
        "push",
        "pull-request",
      ],
    },
    state: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: ["discarded", "proposal-ready", "approval-wait-settled", "approval-wait-failed"],
    },
    reason: {
      type: "string",
      dataClass: "closed-enum",
      required: true,
      values: [
        "authority-denied",
        "policy-authorized",
        "approved",
        "cancelled",
        "expired",
        "unavailable",
        "authority-resolution-failed",
      ],
    },
    proposalId: {
      type: "string",
      dataClass: "opaque-id",
      required: false,
      maxLength: 128,
    },
    waitCeilingMs: { type: "integer", dataClass: "duration", required: false },
    frames: {
      type: "string-array",
      dataClass: "opaque-id",
      required: false,
      maxLength: 512,
      maxItems: 8,
    },
    causeChain: {
      type: "string-array",
      dataClass: "error-kind",
      required: false,
      maxLength: 128,
      maxItems: 5,
    },
  },
  causal: "correlation",
  lifecycle: "state",
  analyzerProjection: "process-lifecycle",
  failureClasses: ["coding-runtime-tool-result"],
  proofIds: ["coding-runtime.tool-result.emitted-line"],
  releaseImpact: "patch",
});
