// Re-export shim: harness contract types live in @oscharko-dev/keiko-contracts (issue #158).
// `verbatimModuleSyntax` is on, so type-only names use `export type` and value-emitting frozen
// tables use `export`. This shim is independent of the @oscharko-dev/keiko-harness extraction
// (issue #164): contracts has been the canonical source of these types since issue #158, and the
// direct-from-contracts form keeps the type graph shallow for downstream consumers.

export type {
  HarnessStateName,
  TerminalState,
  StateTransition,
  HarnessLimits,
  TaskType,
  GenerateUnitTestsInput,
  InvestigateBugInput,
  ExplainPlanInput,
  VerifyInput,
  TaskInput,
  RunCounters,
  RunOutcome,
  RunResult,
  RunManifest,
  HarnessCode,
  HarnessFailure,
  RunStartedEvent,
  StateTransitionEvent,
  ModelCallStartedEvent,
  ModelCallCompletedEvent,
  ModelCallFailedEvent,
  ToolCallStartedEvent,
  ToolCallCompletedEvent,
  ToolCallFailedEvent,
  CommandExecutedEvent,
  SandboxConfiguredEvent,
  PatchAppliedEvent,
  ReasoningTraceEvent,
  PatchProposedEvent,
  VerificationResultEvent,
  RunCompletedEvent,
  RunCancelledEvent,
  RunFailedEvent,
  BrowserSessionCloseReason,
  BrowserSessionOpenedEvent,
  BrowserNavigatedEvent,
  BrowserScreenshotCapturedEvent,
  BrowserPageContentCapturedEvent,
  BrowserSessionClosedEvent,
  BrowserTrustWarningEvent,
  BrowserErrorEvent,
  BrowserEvent,
  HarnessEvent,
} from "@oscharko-dev/keiko-contracts";
export { TERMINAL_STATES, DEFAULT_LIMITS, HARNESS_CODES } from "@oscharko-dev/keiko-contracts";
