-- Human-readable snapshot of the schema baked into keiko-ui.db (Schema v2 — current).
-- Mirrors packages/keiko-server/src/store/schema.ts. Regenerated by build-fixture.mjs.
-- A reviewer can read this without opening sqlite3; the binary is the source of truth.

PRAGMA user_version = 2;

CREATE TABLE projects (
  path TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  favorite INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  last_opened_at INTEGER NOT NULL
) STRICT;

CREATE TABLE chats (
  id TEXT NOT NULL PRIMARY KEY,
  project_path TEXT NOT NULL REFERENCES projects(path) ON DELETE CASCADE,
  title TEXT NOT NULL,
  selected_model TEXT NOT NULL,
  branch_label TEXT,
  status TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE chat_messages (
  id TEXT NOT NULL PRIMARY KEY,
  chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  timestamp INTEGER NOT NULL,
  run_id TEXT,
  workflow_id TEXT,
  workflow_status TEXT,
  short_result TEXT,
  task_type TEXT
) STRICT;

CREATE INDEX idx_chats_project_path ON chats(project_path);
CREATE INDEX idx_messages_chat_id ON chat_messages(chat_id);
CREATE INDEX idx_messages_chat_ts ON chat_messages(chat_id, timestamp);

-- Seeded rows used by tests/upgrade-smoke/upgrade-compatibility.test.ts.
-- build-fixture.mjs seeds the literal placeholder path `/keiko-fixture-project` so the
-- committed binary is byte-stable across rebuilds. The smoke test reads this row through
-- the store API without re-validating the project path (the path-on-disk check is exercised
-- separately by keiko-server's own unit tests).
