// a11y smoke tests for the governed GitHub pull request command center (Issue #477, AC parity with
// #475). jest-axe scans the empty state, the default flow, the loaded readiness panel, and an outcome
// banner; asserts the polite live region exists for async outcome announcements; and asserts readiness /
// outcome are conveyed by TEXT, not colour alone.

import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { axe } from "jest-axe";
import { describe, expect, it, vi } from "vitest";
import { GovernedPullRequestCard, type GovernedPullRequestClient } from "./GovernedPullRequestCard";
import type {
  GitDeliveryPrExecuteResponse,
  GitDeliveryPrPreviewResponse,
  PrDescriptionApplicationResultWire,
  PrDescriptionApplicationStatus,
} from "@/lib/api";

const PREVIEW: GitDeliveryPrPreviewResponse = {
  schemaVersion: "1",
  actionKind: "pr-create",
  headBranchName: "claude/issue-477-x",
  baseBranchName: "dev",
  riskClass: "protected-or-merge",
  riskSeverity: 3,
  isDraft: false,
  policyOutcome: "allowed",
  composedTitle: "feat(keiko-server): github pr command center",
  composedBody: "## Summary\nfeat",
  riskNarrative: "This change is classified protected-or-merge (severity 3).",
  recommendation: "create-as-ready",
  readiness: { objectExists: false, reviewReady: false, blockerCodes: ["head-unpublished"] },
  suggestedLabels: ["enhancement"],
  suggestedIssueRefs: ["#477"],
  titleByteLength: 10,
  bodyByteLength: 20,
};

const OUTCOME: GitDeliveryPrExecuteResponse = {
  schemaVersion: "1",
  status: "blocked",
  actionKind: "pr-create",
  blockReason: "policy-pack-blocked",
};

function makeClient(): GovernedPullRequestClient {
  return {
    prPreview: vi.fn(async () => PREVIEW),
    prApprove: vi.fn(async () => ({
      schemaVersion: "1" as const,
      approval: {
        schemaVersion: "1" as const,
        approvalId: "approval-1",
        approvalToken: "token-1",
      },
      expiresAt: "2026-01-01T00:00:30.000Z",
    })),
    prExecute: vi.fn(async () => OUTCOME),
  };
}

function descriptionStatusFixture(
  overrides: Partial<PrDescriptionApplicationStatus> = {},
): PrDescriptionApplicationStatus {
  return {
    schemaVersion: "1",
    state: "current",
    reason: "applied",
    binding: {
      repositoryId: "repo-1",
      remoteDigest: "a".repeat(64),
      repository: "oscharko-dev/Keiko",
      prNumber: 1499,
      prExternalId: "1499",
      baseRef: "dev",
      baseSha: "b".repeat(40),
      headRepository: "oscharko-dev/Keiko",
      headRef: "feature/x",
      headSha: "c".repeat(40),
      isDraft: false,
      snapshotDigest: "d".repeat(64),
      draftDigest: "e".repeat(64),
      renderingVersion: "1",
      expectedBodyDigest: "f".repeat(64),
      outsideRegionDigest: "0".repeat(64),
      finalBodyDigest: "1".repeat(64),
      providerUpdatedAt: "2026-01-01T00:00:00.000Z",
    },
    observedAt: "2026-01-01T00:00:00.000Z",
    expiresAt: "2026-01-01T00:00:30.000Z",
    completeness: "complete",
    effect: "confirmed",
    concurrency: "read-check-write-verify",
    ...overrides,
  } as PrDescriptionApplicationStatus;
}

function descriptionPreviewResult(): PrDescriptionApplicationResultWire {
  return {
    outcome: "preview",
    preview: {
      proposalId: "prop-1",
      expiresAt: "2026-01-01T00:00:30.000Z",
      status: descriptionStatusFixture(),
      finalBody: "<!-- keiko:managed:v1:start -->generated by Keiko<!-- keiko:managed:v1:end -->",
      managedRegion: "generated by Keiko",
      concurrencyLimitation: "GitHub cannot lock the PR body during this update.",
    },
  };
}

function makeDescriptionClient(): GovernedPullRequestClient {
  return {
    ...makeClient(),
    prDescriptionPreview: vi.fn(async () => descriptionPreviewResult()),
    prDescriptionApprove: vi.fn(async () => ({
      schemaVersion: "1" as const,
      proposalId: "prop-1",
      expiresAt: "2026-01-01T00:00:30.000Z",
    })),
    prDescriptionApply: vi.fn(async () => ({
      outcome: "observed" as const,
      status: descriptionStatusFixture(),
    })),
  };
}

function fillDescriptionForm(): void {
  fireEvent.change(screen.getByLabelText("Description repository (owner/repo)"), {
    target: { value: "oscharko-dev/Keiko" },
  });
  fireEvent.change(screen.getByLabelText("Description pull request number"), {
    target: { value: "1499" },
  });
}

const PROJECT = "/home/me/repo";

function fillForm(): void {
  fireEvent.change(screen.getByLabelText("Repository (owner/repo)"), {
    target: { value: "oscharko-dev/Keiko" },
  });
  fireEvent.change(screen.getByLabelText("Base branch"), { target: { value: "dev" } });
  fireEvent.change(screen.getByLabelText("Head branch"), {
    target: { value: "claude/issue-477-x" },
  });
  fireEvent.change(screen.getByLabelText("Pull Request title"), { target: { value: "feat: x" } });
}

describe("GovernedPullRequestCard — a11y (WCAG 2.2 AA)", () => {
  it("has no violations in the empty state", async () => {
    const { container } = render(<GovernedPullRequestCard client={makeClient()} />);
    expect(await axe(container)).toHaveNoViolations();
  });

  it("has no violations in the default flow state", async () => {
    const { container } = render(
      <GovernedPullRequestCard projectId={PROJECT} client={makeClient()} />,
    );
    expect(await axe(container)).toHaveNoViolations();
  });

  it("has no violations once the readiness panel is loaded", async () => {
    const { container } = render(
      <GovernedPullRequestCard projectId={PROJECT} client={makeClient()} />,
    );
    fillForm();
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    expect(await screen.findByTestId("gpr-readiness")).toBeInTheDocument();
    expect(await axe(container)).toHaveNoViolations();
  });

  it("has no violations with a rendered outcome banner", async () => {
    const { container } = render(
      <GovernedPullRequestCard projectId={PROJECT} client={makeClient()} />,
    );
    fillForm();
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(await axe(container)).toHaveNoViolations();
  });

  it("exposes a polite live region for async outcome announcements", () => {
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient()} />);
    const live = screen.getByTestId("gpr-live");
    expect(live).toHaveAttribute("aria-live", "polite");
    expect(live).toHaveAttribute("role", "status");
  });

  it("conveys readiness and outcome with text labels, not colour alone", async () => {
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient()} />);
    fillForm();
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    expect(await screen.findByTestId("gpr-readiness")).toBeInTheDocument();
    expect(screen.getByTestId("gpr-readiness")).toHaveTextContent("Ready for review: no");
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("pr-create: blocked");
  });

  // #3399: the PR-description panel adds new interactive controls (fields, Preview/Approve/Apply
  // buttons, the rendered preview body, the status badge) — each lifecycle stage is scanned.
  it("has no violations once the description preview is loaded", async () => {
    const { container } = render(
      <GovernedPullRequestCard projectId={PROJECT} client={makeDescriptionClient()} />,
    );
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    expect(await screen.findByTestId("gpr-description-preview")).toBeInTheDocument();
    expect(await axe(container)).toHaveNoViolations();
  });

  it("has no violations after approving and applying the description", async () => {
    const client = makeDescriptionClient();
    const { container } = render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    await screen.findByTestId("gpr-description-preview");
    fireEvent.click(screen.getByTestId("gpr-description-approve-button"));
    await waitFor(() =>
      expect(screen.getByTestId("gpr-description-apply-button")).not.toBeDisabled(),
    );
    fireEvent.click(screen.getByTestId("gpr-description-apply-button"));
    expect(await screen.findByTestId("gpr-description-state")).toBeInTheDocument();
    expect(await axe(container)).toHaveNoViolations();
  });

  it("conveys the description status with text, not colour alone, and keeps every action keyboard-reachable", async () => {
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeDescriptionClient()} />);
    fillDescriptionForm();
    const previewButton = screen.getByTestId("gpr-description-preview-button");
    previewButton.focus();
    expect(previewButton).toHaveFocus();
    fireEvent.click(previewButton);
    expect(await screen.findByTestId("gpr-description-preview")).toBeInTheDocument();
    expect(screen.getByTestId("gpr-description-state")).toHaveTextContent("Applied and confirmed");
    const approveButton = screen.getByTestId("gpr-description-approve-button");
    expect(approveButton.tagName).toBe("BUTTON");
    expect(approveButton).not.toHaveAttribute("tabindex", "-1");
  });
});
