// Behavioural tests for the governed GitHub pull request command center (Issue #477, Epic #470).
// Exercises the metadata editor + readiness/recommendation panel + open/update dispatch with a fully
// mocked api client: empty state, synthesized-draft seeding, mutation payloads, the readable outcome
// banner (created PR / blocked / normalized rejection), and readable API errors.

import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  I18N_STORAGE_KEY,
  I18nProvider,
  loadLocaleMessages,
  resetLoadedMessageCatalogs,
} from "@/lib/i18n";
import { GovernedPullRequestCard, type GovernedPullRequestClient } from "./GovernedPullRequestCard";
import {
  ApiError,
  type GitDeliveryPrApproveResponse,
  type GitDeliveryPrExecuteResponse,
  type GitDeliveryPrPreviewResponse,
  type GitDeliveryPrDescriptionApproveResponse,
  type PrDescriptionApplicationResultWire,
  type PrDescriptionApplicationStatus,
} from "@/lib/api";

function makePreview(
  overrides: Partial<GitDeliveryPrPreviewResponse> = {},
): GitDeliveryPrPreviewResponse {
  return {
    schemaVersion: "1",
    actionKind: "pr-create",
    headBranchName: "claude/issue-477-x",
    baseBranchName: "dev",
    riskClass: "protected-or-merge",
    riskSeverity: 3,
    isDraft: false,
    policyOutcome: "allowed",
    composedTitle: "feat(keiko-server): github pr command center",
    composedBody: "## Summary\nfeat: github pr command center",
    riskNarrative: "This change is classified protected-or-merge (severity 3).",
    recommendation: "create-as-ready",
    readiness: { objectExists: false, reviewReady: false, blockerCodes: [] },
    suggestedLabels: ["enhancement"],
    suggestedIssueRefs: ["#477"],
    titleByteLength: 10,
    bodyByteLength: 20,
    ...overrides,
  };
}

function makeExecute(
  overrides: Partial<GitDeliveryPrExecuteResponse> = {},
): GitDeliveryPrExecuteResponse {
  return {
    schemaVersion: "1",
    status: "succeeded",
    actionKind: "pr-create",
    ...overrides,
  };
}

function makeApprove(
  overrides: Partial<GitDeliveryPrApproveResponse> = {},
): GitDeliveryPrApproveResponse {
  return {
    schemaVersion: "1",
    approval: { schemaVersion: "1", approvalId: "gda_test", approvalToken: "token-test" },
    expiresAt: "2026-01-01T00:00:00.000Z",
    ...overrides,
  };
}

function makeClient(overrides: Partial<GovernedPullRequestClient> = {}): GovernedPullRequestClient {
  return {
    prPreview: vi.fn(async () => makePreview()),
    prApprove: vi.fn(async () => makeApprove()),
    prExecute: vi.fn(async () => makeExecute({ createdPrExternalId: "1499" })),
    ...overrides,
  };
}

// ─── PR-description fixtures (#3399) ───────────────────────────────────────────────────────────────

function descriptionStatusFixture(
  overrides: Partial<PrDescriptionApplicationStatus> = {},
): PrDescriptionApplicationStatus {
  return {
    schemaVersion: "1",
    state: "current",
    reason: "applied",
    binding: {
      repositoryId: "repo-1",
      remoteDigest: "a".repeat(64),
      repository: "oscharko-dev/Keiko",
      prNumber: 1499,
      prExternalId: "1499",
      baseRef: "dev",
      baseSha: "b".repeat(40),
      headRepository: "oscharko-dev/Keiko",
      headRef: "feature/x",
      headSha: "c".repeat(40),
      isDraft: false,
      snapshotDigest: "d".repeat(64),
      draftDigest: "e".repeat(64),
      renderingVersion: "1",
      expectedBodyDigest: "f".repeat(64),
      outsideRegionDigest: "0".repeat(64),
      finalBodyDigest: "1".repeat(64),
      providerUpdatedAt: "2026-01-01T00:00:00.000Z",
    },
    observedAt: "2026-01-01T00:00:00.000Z",
    expiresAt: "2026-01-01T00:00:30.000Z",
    completeness: "complete",
    effect: "confirmed",
    concurrency: "read-check-write-verify",
    ...overrides,
  } as PrDescriptionApplicationStatus;
}

function descriptionPreviewResult(
  statusOverrides: Partial<PrDescriptionApplicationStatus> = {},
): PrDescriptionApplicationResultWire {
  return {
    outcome: "preview",
    preview: {
      proposalId: "prop-1",
      expiresAt: "2026-01-01T00:00:30.000Z",
      status: descriptionStatusFixture(statusOverrides),
      finalBody: "<!-- keiko:managed:v1:start -->generated by Keiko<!-- keiko:managed:v1:end -->",
      managedRegion: "generated by Keiko",
      concurrencyLimitation: "GitHub cannot lock the PR body during this update.",
    },
  };
}

function descriptionObservedResult(
  statusOverrides: Partial<PrDescriptionApplicationStatus> = {},
): PrDescriptionApplicationResultWire {
  return { outcome: "observed", status: descriptionStatusFixture(statusOverrides) };
}

function descriptionBlockedResult(
  reason: PrDescriptionApplicationStatus["reason"],
): PrDescriptionApplicationResultWire {
  return { outcome: "blocked", reason };
}

function makeDescriptionApprove(): GitDeliveryPrDescriptionApproveResponse {
  return { schemaVersion: "1", proposalId: "prop-1", expiresAt: "2026-01-01T00:00:30.000Z" };
}

function makeDescriptionClient(
  overrides: Partial<GovernedPullRequestClient> = {},
): GovernedPullRequestClient {
  return {
    ...makeClient(),
    prDescriptionPreview: vi.fn(async () => descriptionPreviewResult()),
    prDescriptionApprove: vi.fn(async () => makeDescriptionApprove()),
    prDescriptionApply: vi.fn(async () => descriptionObservedResult()),
    ...overrides,
  };
}

function fillDescriptionForm(prNumber = "1499"): void {
  fireEvent.change(screen.getByLabelText("Description repository (owner/repo)"), {
    target: { value: "oscharko-dev/Keiko" },
  });
  fireEvent.change(screen.getByLabelText("Description pull request number"), {
    target: { value: prNumber },
  });
}

const PROJECT = "/home/me/repo";

function fillForm(): void {
  fireEvent.change(screen.getByLabelText("Repository (owner/repo)"), {
    target: { value: "oscharko-dev/Keiko" },
  });
  fireEvent.change(screen.getByLabelText("Base branch"), { target: { value: "dev" } });
  fireEvent.change(screen.getByLabelText("Pull Request title"), {
    target: { value: "feat: x" },
  });
}

describe("GovernedPullRequestCard", () => {
  it("renders an empty state when no project root is provided", () => {
    render(<GovernedPullRequestCard client={makeClient()} />);
    expect(screen.getByTestId("gpr-empty")).toBeInTheDocument();
  });

  it("previews and renders the readiness panel distinguishing object-exists from review-ready", async () => {
    render(
      <GovernedPullRequestCard
        projectId={PROJECT}
        headBranchName="claude/issue-477-x"
        client={makeClient()}
      />,
    );
    fillForm();
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    expect(await screen.findByTestId("gpr-readiness")).toBeInTheDocument();
    const panel = screen.getByTestId("gpr-readiness");
    expect(panel).toHaveTextContent("Remote PR object: not created yet");
    expect(panel).toHaveTextContent("Ready for review: no");
    expect(panel).toHaveTextContent("Recommendation: create-as-ready");
    expect(panel).toHaveTextContent("Linked issues: #477");
  });

  it("seeds the editable title/body from the synthesized draft when empty", async () => {
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient()} />);
    fillForm();
    // Clear the title so the draft seeds it.
    fireEvent.change(screen.getByLabelText("Pull Request title"), { target: { value: "" } });
    fireEvent.change(screen.getByLabelText("Repository (owner/repo)"), {
      target: { value: "oscharko-dev/Keiko" },
    });
    fireEvent.change(screen.getByLabelText("Head branch"), {
      target: { value: "claude/issue-477-x" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    await waitFor(() =>
      expect(screen.getByLabelText("Pull Request title")).toHaveValue(
        "feat(keiko-server): github pr command center",
      ),
    );
  });

  it("dispatches a governed create with the right payload and surfaces the provider PR number", async () => {
    const prExecute = vi.fn(async () => makeExecute({ createdPrExternalId: "1499" }));
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient({ prExecute })} />);
    fillForm();
    fireEvent.change(screen.getByLabelText("Head branch"), {
      target: { value: "claude/issue-477-x" },
    });
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(prExecute).toHaveBeenCalledWith(
      expect.objectContaining({
        projectId: PROJECT,
        kind: "pr-create",
        ownerAndRepo: "oscharko-dev/Keiko",
        baseBranchName: "dev",
      }),
    );
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("pr: #1499");
  });

  it("dispatches a governed update with the selected PR number and draft transition", async () => {
    const prExecute = vi.fn(async () => makeExecute({ actionKind: "pr-update" }));
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient({ prExecute })} />);
    fillForm();
    fireEvent.click(screen.getByLabelText("Update"));
    fireEvent.change(screen.getByLabelText("Head branch"), {
      target: { value: "claude/issue-477-x" },
    });
    fireEvent.change(screen.getByLabelText("Pull Request number"), { target: { value: "1499" } });
    fireEvent.change(screen.getByLabelText("Draft state"), { target: { value: "to-draft" } });

    fireEvent.click(screen.getByTestId("gpr-submit"));

    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(prExecute).toHaveBeenCalledWith(
      expect.objectContaining({
        projectId: PROJECT,
        kind: "pr-update",
        prExternalId: "1499",
        convertFromDraft: false,
        convertToDraft: true,
      }),
    );
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("pr-update: succeeded");
  });

  // #3389 (epic #3384 correction 1): the approval-less draft->ready transition through this generic
  // command center is closed. "Mark ready" is no longer an option in the Draft state select — the
  // failing-before-fix case is exactly the removed test above, which selected "to-ready" and
  // asserted `convertFromDraft: true` reached the generic pr-update execute call.
  it("does not offer Mark ready — the draft->ready transition moved to the dedicated pr-mark-ready intent", () => {
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient({})} />);
    fireEvent.click(screen.getByLabelText("Update"));
    const select = screen.getByLabelText("Draft state");
    const optionValues = [...select.querySelectorAll("option")].map((option) => option.value);
    expect(optionValues).toEqual(["none", "to-draft"]);
    expect(screen.getByTestId("gpr-mark-ready-hint")).toHaveTextContent("Propose ready");
  });

  it("surfaces a policy-blocked outcome with its reason", async () => {
    const prExecute = vi.fn(async () =>
      makeExecute({
        status: "blocked",
        blockReason: "policy-pack-blocked",
      }),
    );
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient({ prExecute })} />);
    fillForm();
    fireEvent.change(screen.getByLabelText("Head branch"), {
      target: { value: "claude/issue-477-x" },
    });
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("pr-create: blocked");
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("reason: policy-pack-blocked");
  });

  it("normalizes a provider rejection into a typed reason + recovery disposition", async () => {
    const prExecute = vi.fn(async () =>
      makeExecute({
        status: "failed",
        executionErrorCode: "provider-rejected",
        prRejectionReason: "validation-error",
        recoveryDisposition: "user-fixable",
      }),
    );
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient({ prExecute })} />);
    fillForm();
    fireEvent.change(screen.getByLabelText("Head branch"), {
      target: { value: "claude/issue-477-x" },
    });
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("rejected: validation-error");
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("recover: user-fixable");
  });

  it("surfaces provider-auth failures without raw provider details", async () => {
    const prExecute = vi.fn(async () =>
      makeExecute({
        status: "failed",
        executionErrorCode: "provider-rejected",
        prRejectionReason: "provider-auth",
        recoveryDisposition: "user-fixable",
        recoveryActionHint: "Reconnect provider access.",
      }),
    );
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient({ prExecute })} />);
    fillForm();
    fireEvent.change(screen.getByLabelText("Head branch"), {
      target: { value: "claude/issue-477-x" },
    });
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("rejected: provider-auth");
    expect(screen.getByTestId("gpr-outcome")).toHaveTextContent("hint: Reconnect provider access.");
    expect(screen.getByTestId("gpr-outcome")).not.toHaveTextContent(/token|secret|authorization/i);
  });

  it("renders API failures as a readable alert", async () => {
    const prExecute = vi.fn(() =>
      Promise.reject(
        new ApiError("GIT_DELIVERY_PR_WORKTREE_UNAVAILABLE", "worktree unavailable", 409),
      ),
    );
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient({ prExecute })} />);
    fillForm();
    fireEvent.change(screen.getByLabelText("Head branch"), {
      target: { value: "claude/issue-477-x" },
    });
    fireEvent.click(screen.getByTestId("gpr-submit"));
    await waitFor(() =>
      expect(screen.getByRole("alert")).toHaveTextContent(
        "worktree unavailable (GIT_DELIVERY_PR_WORKTREE_UNAVAILABLE)",
      ),
    );
  });

  it("hides a finished outcome when the action kind or target changes", async () => {
    render(
      <GovernedPullRequestCard
        projectId={PROJECT}
        headBranchName="claude/issue-477-x"
        client={makeClient()}
      />,
    );
    fillForm();
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    // Switching Create → Update retargets the form: the old "created" banner must disappear —
    // it describes a different action than the one the form now names.
    fireEvent.click(screen.getByRole("radio", { name: "Update" }));
    expect(screen.queryByTestId("gpr-outcome")).not.toBeInTheDocument();
    expect(screen.getByTestId("gpr-live")).toHaveTextContent("");
    // Returning to the executed target restores the still-valid outcome.
    fireEvent.click(screen.getByRole("radio", { name: "Create" }));
    expect(screen.getByTestId("gpr-outcome")).toBeInTheDocument();
  });

  it("hides a stale readiness panel when a target field changes after a preview", async () => {
    render(
      <GovernedPullRequestCard
        projectId={PROJECT}
        headBranchName="claude/issue-477-x"
        client={makeClient()}
      />,
    );
    fillForm();
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    expect(await screen.findByTestId("gpr-readiness")).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText("Base branch"), { target: { value: "main" } });
    expect(screen.queryByTestId("gpr-readiness")).not.toBeInTheDocument();
  });

  it("gates the update flow on a numeric PR number and explains the format", () => {
    const client = makeClient();
    render(
      <GovernedPullRequestCard
        projectId={PROJECT}
        headBranchName="claude/issue-477-x"
        client={client}
      />,
    );
    fillForm();
    fireEvent.click(screen.getByRole("radio", { name: "Update" }));
    fireEvent.change(screen.getByLabelText("Pull Request number"), {
      target: { value: "PR#12" },
    });
    expect(screen.getByTestId("gpr-pr-number-hint")).toHaveTextContent(
      "numeric Pull Request number",
    );
    expect(screen.getByLabelText("Pull Request number")).toHaveAttribute("aria-invalid", "true");
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(client.prPreview).not.toHaveBeenCalled();
    expect(client.prExecute).not.toHaveBeenCalled();
  });

  // #3387: the create/update mutation now requires an actually consumed, server-issued approval
  // claim unconditionally. Before `prApprove` existed on this client and `runExecute` minted it,
  // `prExecute` was called directly with no `approval` field, and the real BFF route
  // (`createHandlePrExecute`) would have returned `approval-required` forever — this test's second
  // assertion (`approval` present on the execute call) would have failed against that prior code.
  it("mints a pull-request approval claim and attaches it to execute (#3387)", async () => {
    const prApprove = vi.fn(async () => makeApprove());
    const prExecute = vi.fn(async () => makeExecute({ createdPrExternalId: "1499" }));
    render(
      <GovernedPullRequestCard
        projectId={PROJECT}
        headBranchName="claude/issue-477-x"
        client={makeClient({ prApprove, prExecute })}
      />,
    );
    fillForm();
    fireEvent.click(screen.getByTestId("gpr-submit"));
    expect(await screen.findByTestId("gpr-outcome")).toBeInTheDocument();
    expect(prApprove).toHaveBeenCalledTimes(1);
    expect(prExecute).toHaveBeenCalledWith(
      expect.objectContaining({ approval: makeApprove().approval }),
    );
  });

  it("fails closed before execute when the injected client has no approval capability", async () => {
    const prExecute = vi.fn(async () => makeExecute());
    const client = makeClient({ prApprove: undefined, prExecute });
    render(
      <GovernedPullRequestCard
        projectId={PROJECT}
        headBranchName="claude/issue-477-x"
        client={client}
      />,
    );
    fillForm();
    fireEvent.click(screen.getByTestId("gpr-submit"));
    await waitFor(() =>
      expect(screen.getByTestId("gpr-live")).toHaveTextContent(
        "Pull request action failed: pr-approval-client-unavailable",
      ),
    );
    expect(prExecute).not.toHaveBeenCalled();
  });
});

// #3399: the governed PR-description preview -> approve -> apply lifecycle rendered by
// GovernedPullRequestCard's Description panel.
describe("GovernedPullRequestCard — PR description application (#3399)", () => {
  it("renders no description panel when the injected client omits any of the three methods", () => {
    render(<GovernedPullRequestCard projectId={PROJECT} client={makeClient()} />);
    expect(screen.queryByTestId("gpr-description")).not.toBeInTheDocument();
  });

  it("previews, approves, and applies, rendering the confirmed 'current' state", async () => {
    const client = makeDescriptionClient();
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();

    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    expect(await screen.findByTestId("gpr-description-preview")).toHaveTextContent(
      "generated by Keiko",
    );
    // The server-rendered final body — including the trusted "by Keiko" attribution and the
    // managed-region markers — is shown byte-for-byte, never recomposed here.
    expect(screen.getByTestId("gpr-description-preview")).toHaveTextContent(
      "<!-- keiko:managed:v1:start -->",
    );

    const approveButton = screen.getByTestId("gpr-description-approve-button");
    const applyButton = screen.getByTestId("gpr-description-apply-button");
    expect(approveButton).not.toBeDisabled();
    expect(applyButton).toBeDisabled();

    fireEvent.click(approveButton);
    await waitFor(() => expect(client.prDescriptionApprove).toHaveBeenCalledTimes(1));
    expect(client.prDescriptionApprove).toHaveBeenCalledWith(
      expect.objectContaining({
        projectId: PROJECT,
        ownerAndRepo: "oscharko-dev/Keiko",
        prNumber: 1499,
        proposalId: "prop-1",
      }),
    );
    expect(await screen.findByTestId("gpr-description-apply-button")).not.toBeDisabled();

    fireEvent.click(screen.getByTestId("gpr-description-apply-button"));
    expect(await screen.findByTestId("gpr-description-state")).toHaveAttribute(
      "data-state",
      "current",
    );
    expect(screen.getByTestId("gpr-description-state")).toHaveTextContent("Applied and confirmed");
  });

  it("reviews the exact Workbench proposal without generating a second preview", async () => {
    const review = vi.fn(async () => descriptionPreviewResult());
    const client = makeDescriptionClient({ prDescriptionReview: review });
    const descriptionProposal = {
      projectId: PROJECT,
      ownerAndRepo: "oscharko-dev/Keiko",
      prNumber: 1499,
      proposalId: "prop-1",
      snapshotDigest: "d".repeat(64),
    };
    render(
      <GovernedPullRequestCard
        projectId={PROJECT}
        client={client}
        descriptionProposal={descriptionProposal}
      />,
    );

    expect(await screen.findByTestId("gpr-description-preview")).toHaveTextContent(
      "generated by Keiko",
    );
    expect(review).toHaveBeenCalledExactlyOnceWith(descriptionProposal);
    expect(client.prDescriptionPreview).not.toHaveBeenCalled();
    fireEvent.click(screen.getByTestId("gpr-description-approve-button"));
    await waitFor(() => expect(client.prDescriptionApprove).toHaveBeenCalledOnce());
    expect(client.prDescriptionApprove).toHaveBeenCalledWith(descriptionProposal);
  });

  it("one-use approval: applying clears the approval, so a second Apply click is disabled again", async () => {
    const client = makeDescriptionClient();
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    await screen.findByTestId("gpr-description-preview");
    fireEvent.click(screen.getByTestId("gpr-description-approve-button"));
    await waitFor(() =>
      expect(screen.getByTestId("gpr-description-apply-button")).not.toBeDisabled(),
    );

    fireEvent.click(screen.getByTestId("gpr-description-apply-button"));
    await screen.findByTestId("gpr-description-state");

    expect(client.prDescriptionApply).toHaveBeenCalledTimes(1);
    expect(screen.getByTestId("gpr-description-apply-button")).toBeDisabled();
    expect(screen.getByTestId("gpr-description-approve-button")).toBeDisabled();
  });

  it.each([
    ["stale", "Stale — refresh the preview"],
    ["partial", "Applied — partially generated"],
    ["fallback", "Applied — generated without the model"],
    ["failed", "Failed — not applied"],
  ] as const)("renders the distinct '%s' status after apply", async (state, label) => {
    const client = makeDescriptionClient({
      prDescriptionApply: vi.fn(async () =>
        descriptionObservedResult({
          state,
          reason:
            state === "stale"
              ? "stale-pr"
              : state === "partial"
                ? "partial-applied"
                : state === "fallback"
                  ? "fallback-applied"
                  : "provider-failed",
          completeness: state === "partial" || state === "fallback" ? state : "complete",
          effect: state === "partial" || state === "fallback" ? "confirmed" : "none",
        }),
      ),
    });
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    await screen.findByTestId("gpr-description-preview");
    fireEvent.click(screen.getByTestId("gpr-description-approve-button"));
    await waitFor(() =>
      expect(screen.getByTestId("gpr-description-apply-button")).not.toBeDisabled(),
    );
    fireEvent.click(screen.getByTestId("gpr-description-apply-button"));

    expect(await screen.findByTestId("gpr-description-state")).toHaveAttribute("data-state", state);
    expect(screen.getByTestId("gpr-description-state")).toHaveTextContent(label);
  });

  it("renders a blocked outcome by reason without ever calling apply", async () => {
    const client = makeDescriptionClient({
      prDescriptionPreview: vi.fn(async () => descriptionBlockedResult("approval-required")),
    });
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    expect(await screen.findByTestId("gpr-description-state")).toHaveAttribute(
      "data-state",
      "blocked",
    );
    expect(screen.getByTestId("gpr-description-approve-button")).toBeDisabled();
    expect(client.prDescriptionApply).not.toHaveBeenCalled();
  });

  it("disables approve/apply and shows refresh guidance on a stale preview", async () => {
    const client = makeDescriptionClient({
      prDescriptionPreview: vi.fn(async () =>
        descriptionPreviewResult({ state: "stale", reason: "stale-pr" }),
      ),
    });
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    expect(await screen.findByTestId("gpr-description-refresh-hint")).toHaveTextContent(
      "Preview again",
    );
    expect(screen.getByTestId("gpr-description-approve-button")).toBeDisabled();
    expect(screen.getByTestId("gpr-description-apply-button")).toBeDisabled();
  });

  it("hides the stale preview/approval and shows refresh guidance when the target changes after preview", async () => {
    const client = makeDescriptionClient();
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    await screen.findByTestId("gpr-description-preview");

    fireEvent.change(screen.getByLabelText("Description pull request number"), {
      target: { value: "1500" },
    });

    expect(screen.queryByTestId("gpr-description-preview")).not.toBeInTheDocument();
    expect(screen.queryByTestId("gpr-description-state")).not.toBeInTheDocument();
    expect(screen.getByTestId("gpr-description-refresh-hint")).toHaveTextContent(
      "changed since the last preview",
    );
    expect(screen.getByTestId("gpr-description-approve-button")).toBeDisabled();
  });

  it("surfaces a readable API error without touching apply", async () => {
    const client = makeDescriptionClient({
      prDescriptionPreview: vi.fn(() =>
        Promise.reject(new ApiError("GIT_DELIVERY_PR_DESCRIPTION_UNAVAILABLE", "unavailable", 503)),
      ),
    });
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm();
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    await waitFor(() =>
      expect(
        screen.getByText("unavailable (GIT_DELIVERY_PR_DESCRIPTION_UNAVAILABLE)"),
      ).toBeInTheDocument(),
    );
    expect(client.prDescriptionApply).not.toHaveBeenCalled();
  });

  // Owner audit b1-15 — the previewedKey/targetKey comparison compared the raw form string against
  // `String(async.target.prNumber)` (the server-issued number, which never has leading zeros), so a
  // PR number typed with leading zeros never matched its own just-completed preview. Failing-before:
  // `gpr-description-preview` was absent and the approve button stayed disabled after this exact
  // click sequence.
  it("keeps a successful preview visible when the PR number was typed with leading zeros", async () => {
    const client = makeDescriptionClient({
      prDescriptionPreview: vi.fn(async (input) => {
        expect(input.prNumber).toBe(42);
        return descriptionPreviewResult();
      }),
    });
    render(<GovernedPullRequestCard projectId={PROJECT} client={client} />);
    fillDescriptionForm("0042");
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));

    expect(await screen.findByTestId("gpr-description-preview")).toHaveTextContent(
      "generated by Keiko",
    );
    expect(screen.getByTestId("gpr-description-approve-button")).not.toBeDisabled();
    expect(screen.queryByTestId("gpr-description-refresh-hint")).not.toBeInTheDocument();
  });
});

// Locale review residual: the Description panel was 100% hardcoded English (no i18n hook at all)
// even though the task brief for this surface lists EN/DE strings as a deliverable. Every string is
// now routed through the site-wide i18n mechanism (@/lib/i18n + i18n-messages.en/de.ts) that this
// card's siblings in the git-client widget family already use (GitChangeScopePill.tsx,
// GitClientWindow.tsx) — asserting the DE rendering for the state labels and the action buttons.
describe("GovernedPullRequestCard — Description panel localization (DE)", () => {
  afterEach(() => {
    window.localStorage.clear();
    resetLoadedMessageCatalogs();
  });

  function renderDescriptionPanelInGerman(
    client: GovernedPullRequestClient,
  ): ReturnType<typeof render> {
    window.localStorage.setItem(I18N_STORAGE_KEY, "de");
    return render(
      <I18nProvider>
        <GovernedPullRequestCard projectId={PROJECT} client={client} />
      </I18nProvider>,
    );
  }

  it("renders the action buttons in German", async () => {
    await loadLocaleMessages("de");
    renderDescriptionPanelInGerman(makeDescriptionClient());

    expect(
      await screen.findByRole("button", { name: "Beschreibung als Vorschau anzeigen" }),
    ).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Genehmigen" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Übernehmen" })).toBeInTheDocument();
    // The EN wording must not leak through once German is selected.
    expect(screen.queryByRole("button", { name: "Preview description" })).not.toBeInTheDocument();
  });

  it("renders the 'current' state label in German after preview -> approve -> apply", async () => {
    await loadLocaleMessages("de");
    const client = makeDescriptionClient();
    renderDescriptionPanelInGerman(client);

    fireEvent.change(await screen.findByLabelText("Beschreibung Repository (Besitzer/Repo)"), {
      target: { value: "oscharko-dev/Keiko" },
    });
    fireEvent.change(screen.getByLabelText("Beschreibung Pull-Request-Nummer"), {
      target: { value: "1499" },
    });

    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    await screen.findByTestId("gpr-description-preview");
    fireEvent.click(screen.getByTestId("gpr-description-approve-button"));
    await waitFor(() =>
      expect(screen.getByTestId("gpr-description-apply-button")).not.toBeDisabled(),
    );
    fireEvent.click(screen.getByTestId("gpr-description-apply-button"));

    expect(await screen.findByTestId("gpr-description-state")).toHaveTextContent(
      "Übernommen und bestätigt",
    );
  });

  it.each([
    ["stale", "Veraltet — Vorschau aktualisieren"],
    ["partial", "Übernommen — teilweise generiert"],
    ["fallback", "Übernommen — ohne Modell generiert"],
    ["failed", "Fehlgeschlagen — nicht übernommen"],
  ] as const)("renders the distinct '%s' status label in German", async (state, label) => {
    await loadLocaleMessages("de");
    const client = makeDescriptionClient({
      prDescriptionApply: vi.fn(async () =>
        descriptionObservedResult({
          state,
          reason:
            state === "stale"
              ? "stale-pr"
              : state === "partial"
                ? "partial-applied"
                : state === "fallback"
                  ? "fallback-applied"
                  : "provider-failed",
          completeness: state === "partial" || state === "fallback" ? state : "complete",
          effect: state === "partial" || state === "fallback" ? "confirmed" : "none",
        }),
      ),
    });
    renderDescriptionPanelInGerman(client);

    fireEvent.change(await screen.findByLabelText("Beschreibung Repository (Besitzer/Repo)"), {
      target: { value: "oscharko-dev/Keiko" },
    });
    fireEvent.change(screen.getByLabelText("Beschreibung Pull-Request-Nummer"), {
      target: { value: "1499" },
    });
    fireEvent.click(screen.getByTestId("gpr-description-preview-button"));
    await screen.findByTestId("gpr-description-preview");
    fireEvent.click(screen.getByTestId("gpr-description-approve-button"));
    await waitFor(() =>
      expect(screen.getByTestId("gpr-description-apply-button")).not.toBeDisabled(),
    );
    fireEvent.click(screen.getByTestId("gpr-description-apply-button"));

    expect(await screen.findByTestId("gpr-description-state")).toHaveTextContent(label);
  });
});
