// Re-export shim: harness contract types live in @oscharko-dev/keiko-contracts (issue #158).
// `verbatimModuleSyntax` is on, so type-only names use `export type` and value-emitting frozen
// tables use `export`.

export type {
  HarnessStateName,
  TerminalState,
  StateTransition,
  HarnessLimits,
  TaskType,
  GenerateUnitTestsInput,
  InvestigateBugInput,
  ExplainPlanInput,
  VerifyInput,
  TaskInput,
  RunCounters,
  RunOutcome,
  RunResult,
  RunManifest,
  HarnessCode,
  HarnessFailure,
  RunStartedEvent,
  StateTransitionEvent,
  ModelCallStartedEvent,
  ModelCallCompletedEvent,
  ModelCallFailedEvent,
  ToolCallStartedEvent,
  ToolCallCompletedEvent,
  ToolCallFailedEvent,
  CommandExecutedEvent,
  SandboxConfiguredEvent,
  PatchAppliedEvent,
  ReasoningTraceEvent,
  PatchProposedEvent,
  VerificationResultEvent,
  RunCompletedEvent,
  RunCancelledEvent,
  RunFailedEvent,
  BrowserSessionCloseReason,
  BrowserSessionOpenedEvent,
  BrowserNavigatedEvent,
  BrowserScreenshotCapturedEvent,
  BrowserPageContentCapturedEvent,
  BrowserSessionClosedEvent,
  BrowserTrustWarningEvent,
  BrowserErrorEvent,
  BrowserEvent,
  HarnessEvent,
  OrchestrationRunKind,
  OrchestrationExecutionMode,
  OrchestrationState,
  OrchestrationChildRole,
  OrchestrationChildOutcome,
  OrchestrationStateTransition,
  OrchestrationAuthorityBoundary,
  OrchestrationRunIdentity,
  OrchestrationChildPlan,
  OrchestrationPlan,
  OrchestrationChildSettlement,
  OrchestrationSettlementOutcome,
  OrchestrationSettlementStrategy,
  OrchestrationSettlementReason,
  OrchestrationSettlementDecision,
  OrchestrationInvalidTransition,
} from "@oscharko-dev/keiko-contracts";
export {
  TERMINAL_STATES,
  DEFAULT_LIMITS,
  HARNESS_CODES,
  ORCHESTRATION_SCHEMA_VERSION,
  ORCHESTRATION_RUN_KINDS,
  ORCHESTRATION_EXECUTION_MODES,
  ORCHESTRATION_STATES,
  ORCHESTRATION_TERMINAL_STATES,
  ORCHESTRATION_CHILD_ROLES,
  ORCHESTRATION_CHILD_OUTCOMES,
  ORCHESTRATION_SETTLEMENT_OUTCOMES,
  ORCHESTRATION_SETTLEMENT_STRATEGIES,
  ORCHESTRATION_ALLOWED_STATE_TRANSITIONS,
  isOrchestrationStateTransitionAllowed,
  assertOrchestrationStateTransition,
} from "@oscharko-dev/keiko-contracts";
