// Compatibility surface for the long-standing server subpath. The implementation moved to the
// Activity Log package; keep this module as re-exports only so there is still one writer/store.
export {
  activityLogStorageHealth,
  appendDurableServerLogBatch,
  closeFileServerLogSinks,
  closeReasonVocabulary,
  createFileServerLogSink,
  errorKindOf,
  formatRegisteredServerLogLine,
  formatServerLogLine,
  isDeniedLogFieldName,
  isServerLogLevel,
  isServerLogThreshold,
  listActivityLogFiles,
  normalizeLogFieldName,
  nullServerLogSink,
  parseServerLogThreshold,
  pinActivityLogWindow,
  redactLogFields,
  redactLogLabel,
  redactLogString,
  releaseActivityLogPin,
  reportServerLogFailure,
  resolveActivityLogStorageConfig,
  resolveServerLogThreshold,
  serverLogInstanceId,
  serverLogLevelEnabled,
  serverLogLevelRank,
  serverLogLineBytes,
  serverLogLineWithinCap,
  serverLogProcessIdentity,
  ACTIVITY_LOG_PIN_QUOTA_BYTES_ENV,
  ACTIVITY_LOG_RETENTION_BYTES_ENV,
  ACTIVITY_LOG_RETENTION_DAYS_ENV,
  ACTIVITY_LOG_SEGMENT_BYTES_ENV,
  ACTIVITY_LOG_SEGMENT_SECONDS_ENV,
  ACTIVITY_LOG_STORAGE_OPERATIONS,
  DEFAULT_ACTIVITY_LOG_PIN_QUOTA_BYTES,
  DEFAULT_ACTIVITY_LOG_RETENTION_BYTES,
  DEFAULT_ACTIVITY_LOG_RETENTION_DAYS,
  DEFAULT_ACTIVITY_LOG_SEGMENT_BYTES,
  DEFAULT_ACTIVITY_LOG_SEGMENT_SECONDS,
  DEFAULT_SERVER_LOG_LEVEL,
  DROPPED_DEPTH,
  DROPPED_LENGTH,
  LOG_FAILURE_NOTICE_WINDOW_MS,
  MAX_ACTIVITY_LOG_PINS,
  MAX_ACTIVITY_LOG_PIN_DURATION_MS,
  MAX_ACTIVITY_LOG_PIN_SEGMENTS,
  MAX_ACTIVITY_LOG_PIN_WINDOW_MS,
  MAX_LOG_ARRAY_LENGTH,
  MAX_LOG_FIELD_COUNT,
  MAX_LOG_FIELD_DEPTH,
  MAX_LOG_LINE_BYTES,
  MAX_LOG_STRING_LENGTH,
  MIN_ACTIVITY_LOG_RETENTION_BYTES,
  MIN_ACTIVITY_LOG_SEGMENT_BYTES,
  REDACTED_KEY,
  REDACTED_LENGTH,
  REDACTED_PATH,
  REDACTED_PERSONAL,
  REDACTED_SECRET,
  REDACTED_SHAPE,
  SERVER_LOG_LEVELS,
  SERVER_LOG_LEVEL_ENV,
  SERVER_LOG_SCHEMA_VERSION,
  ActivityLogWriterOwnershipError,
  type ActivityLogFileInfo,
  type ActivityLogPinReason,
  type ActivityLogPinReleaseRequest,
  type ActivityLogPinReleaseResult,
  type ActivityLogPinRejection,
  type ActivityLogPinRequest,
  type ActivityLogPinResult,
  type ActivityLogPinScope,
  type ActivityLogPressureSeverity,
  type ActivityLogPressureState,
  type ActivityLogStorageConfig,
  type ActivityLogStoreHealth,
  type DurableServerLogBatchInspection,
  type DurableServerLogBatchOptions,
  type DurableServerLogBatchResult,
  type FileServerLogSinkOptions,
  type ServerLogCategory,
  type ServerLogEnv,
  type ServerLogEvent,
  type ServerLogFailureContext,
  type ServerLogIdentity,
  type ServerLogLevel,
  type ServerLogSink,
  type ServerLogThreshold,
} from "./index.js";
export { redactRoutePath } from "./route-template.js";
