// Generated by scripts/generate-op-catalog.mjs. Do not edit by hand.
export const ACTIVITY_LOG_REGISTRY_VERSION = 1 as const;
export const ACTIVITY_LOG_SCHEMA_DIGEST = "205b1dc41337fe3b2841dca3dee729eb51c7027de380f8bf8b1f1391d61fd2a3" as const;
export const ACTIVITY_LOG_CATALOG_DIGEST = "9d3aa567bfedcc965beddeb0f6a550208070948a6f770a1da95c810e58165041" as const;
