// Generated by scripts/generate-op-catalog.mjs. Do not edit by hand.
export const ACTIVITY_LOG_REGISTRY_VERSION = 1 as const;
export const ACTIVITY_LOG_SCHEMA_DIGEST = "205b1dc41337fe3b2841dca3dee729eb51c7027de380f8bf8b1f1391d61fd2a3" as const;
export const ACTIVITY_LOG_CATALOG_DIGEST = "1dd6813220c00d78c7e2df73160e4bc01a4525c05a012fc1ac30e7d7f45c816c" as const;
