// Generated by scripts/generate-op-catalog.mjs. Do not edit by hand.
export const ACTIVITY_LOG_REGISTRY_VERSION = 1 as const;
export const ACTIVITY_LOG_SCHEMA_DIGEST = "205b1dc41337fe3b2841dca3dee729eb51c7027de380f8bf8b1f1391d61fd2a3" as const;
export const ACTIVITY_LOG_CATALOG_DIGEST = "50bf57ac6aa8bb297df54798b3f938127e5e125a451eba6db6d146c535ee1bb6" as const;
