import { lstatSync, mkdtempSync, readFileSync, realpathSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import {
  deriveDebugRuntimeMountIdentityDigest,
  deriveDebugSpawnEnvelopeIdentityDigest,
  sha256Json,
} from "./debugIdentityDigest.js";

const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function temporaryDirectory(): string {
  const path = realpathSync(mkdtempSync(join(tmpdir(), "debug-identity-digest-")));
  roots.push(path);
  return path;
}

function productionSource(basename: string): string {
  return readFileSync(fileURLToPath(new URL(`./${basename}`, import.meta.url)), "utf8");
}

// Golden vectors below are frozen compatibility vectors: fixed literal inputs paired with a
// literal hex digest computed ONCE, by hand, from the current production formula. They must never
// be regenerated by calling `sha256Json` / `deriveDebugRuntimeMountIdentityDigest` themselves --
// doing so would make the test recompute the very formula it exists to pin, so a change to that
// formula could never turn it red (the fixture-derivation antipattern AGENTS.md bans).
const GOLDEN_SHA256_JSON_VALUE = { a: 1, b: [2, 3], c: "x" };
const GOLDEN_SHA256_JSON_HEX = "05821054c91d7de7ada20697a6d3aa60700a98f7bb811ce84bd3d3f13b10a310";

describe("sha256Json", () => {
  it("is exactly sha256(JSON.stringify(value)) -- the formula every call site previously re-typed", () => {
    expect(sha256Json(GOLDEN_SHA256_JSON_VALUE)).toBe(GOLDEN_SHA256_JSON_HEX);
  });

  it("is order-sensitive, matching JSON.stringify's own field-order sensitivity", () => {
    expect(sha256Json([1, 2, 3])).not.toBe(sha256Json([3, 2, 1]));
  });
});

// Fixed, made-up stat fields (not a real filesystem's dev/ino/mode/uid) keep this golden vector
// deterministic across hosts and CI runners. See the comment on GOLDEN_SHA256_JSON_HEX above --
// the same rule applies here: this hex string is frozen and must never be regenerated from
// `deriveDebugRuntimeMountIdentityDigest` itself.
const GOLDEN_RUNTIME_MOUNT_REAL_PATH = "/keiko/fixtures/debug-runtime/mount";
const GOLDEN_RUNTIME_MOUNT_STAT = { dev: 16_777_233, ino: 8_592_712, mode: 33_188, uid: 501 };
const GOLDEN_RUNTIME_MOUNT_HEX = "1971aabdfa4502eedd4c4eac16b8995d8241e7eb7166972cf71f3f861c93f139";

describe("deriveDebugRuntimeMountIdentityDigest", () => {
  it("reproduces the exact byte-for-byte formula sha256(JSON.stringify([real, dev, ino, mode, uid]))", () => {
    expect(
      deriveDebugRuntimeMountIdentityDigest(
        GOLDEN_RUNTIME_MOUNT_REAL_PATH,
        GOLDEN_RUNTIME_MOUNT_STAT,
      ),
    ).toBe(GOLDEN_RUNTIME_MOUNT_HEX);
  });

  it("derives an identical digest from the producer's full Stats object and a validator's bare field record", () => {
    const runtime = temporaryDirectory();
    const stat = lstatSync(runtime);
    const fromFullStat = deriveDebugRuntimeMountIdentityDigest(runtime, stat);
    const fromBareFields = deriveDebugRuntimeMountIdentityDigest(runtime, {
      dev: stat.dev,
      ino: stat.ino,
      mode: stat.mode,
      uid: stat.uid,
    });
    expect(fromFullStat).toBe(fromBareFields);
  });

  it("changes when any single identity field changes", () => {
    const runtime = temporaryDirectory();
    const stat = lstatSync(runtime);
    const baseline = deriveDebugRuntimeMountIdentityDigest(runtime, stat);
    const mutatedIno = {
      dev: stat.dev,
      ino: stat.ino + 1,
      mode: stat.mode,
      uid: stat.uid,
    };
    expect(deriveDebugRuntimeMountIdentityDigest(runtime, mutatedIno)).not.toBe(baseline);
    expect(deriveDebugRuntimeMountIdentityDigest(`${runtime}-other`, stat)).not.toBe(baseline);
  });
});

describe("deriveDebugSpawnEnvelopeIdentityDigest", () => {
  it("is a no-op filter when identityDigest/planId are absent -- the pre-signing call shape", () => {
    const values = { a: 1, b: 2, c: "keep" };
    expect(deriveDebugSpawnEnvelopeIdentityDigest(values)).toBe(sha256Json(values));
  });

  it("excludes identityDigest and planId so re-deriving from an already-signed envelope reproduces the same digest", () => {
    const values = { a: 1, b: 2, c: "keep" };
    const identityDigest = deriveDebugSpawnEnvelopeIdentityDigest(values);
    const signed = { ...values, planId: identityDigest, identityDigest };
    expect(deriveDebugSpawnEnvelopeIdentityDigest(signed)).toBe(identityDigest);
  });
});

describe("producer/validator formula centralization (KEIKO-0168)", () => {
  // This is the load-bearing regression guard: it is a static proof, over the real source text,
  // that the runtime-mount and spawn-envelope digest formulas are each written exactly once and
  // imported everywhere else, not independently re-typed per file. A value-level equality check
  // between call sites cannot catch this defect class -- three authors typing the identical
  // formula by hand agree on every value comparison right up until one of them is edited alone,
  // which is exactly how issue #2643 broke every Linux debug launch with the suite green.
  const producerAndValidatorFiles = [
    "debugLaunchContext.ts",
    "debugLaunchPlan.ts",
    "dapNodeCapsuleLauncher.ts",
  ] as const;

  it("no producer/validator file re-types a local generic sha256(JSON.stringify(...)) hash helper", () => {
    for (const basename of producerAndValidatorFiles) {
      const source = productionSource(basename);
      expect(source, `${basename} must not re-type a local hash()/digest() helper`).not.toMatch(
        /function (hash|digest)\(value: unknown\): string \{/u,
      );
    }
  });

  it("every producer/validator file imports the shared digest module instead", () => {
    for (const basename of producerAndValidatorFiles) {
      const source = productionSource(basename);
      expect(source, `${basename} must import from ./debugIdentityDigest.js`).toMatch(
        /from "\.\/debugIdentityDigest\.js"/u,
      );
    }
  });

  it("debugLaunchCatalog.ts's unrelated catalog-target digest also reuses the shared sha256Json instead of a local copy", () => {
    const source = productionSource("debugLaunchCatalog.ts");
    expect(source).not.toMatch(/function digest\(value: unknown\): string \{/u);
    expect(source).toMatch(/from "\.\/debugIdentityDigest\.js"/u);
  });
});
