/* Ported 1:1 from the Claude-Design handoff (project/icons.jsx), then upgraded to
   the Keiko "Lift" icon signature (design/Keiko Icon System.html · design/lift-icons.jsx).

   THE LIFT: every closed contour carries exactly one fine open seam — the lifted
   pen. The Ico wrapper (viewBox 24, stroke 1.6, round caps/joins, currentColor,
   no fill) is unchanged; only the path geometry of glyphs that have a Lift
   counterpart was swapped to the seam'd version. Geometry for arcs/seam-boxes is
   generated byte-identically to design/lift-glyphs.js (the design's own generator).
   Open/gestural glyphs (plus, check, chevron, arrowUp/send, bolt) carry no forced
   seam and are left unchanged. Glyphs without a Lift counterpart keep their shape.

   Welle-2/3/4 components rely on the full set being present here — do not prune. */
import type { CSSProperties, ReactNode } from "react";

interface IcoProps {
  size?: number;
  sw?: number;
  vb?: number;
  fill?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
  d?: string;
  "aria-hidden"?: boolean | "true" | "false";
}

function Ico({
  size = 18,
  sw = 1.6,
  vb = 24,
  fill,
  className,
  style,
  children,
  d,
}: IcoProps): ReactNode {
  const useFill = fill !== undefined;
  return (
    <svg
      className={className}
      width={size}
      height={size}
      viewBox={`0 0 ${String(vb)} ${String(vb)}`}
      fill={useFill ? fill : "none"}
      stroke={useFill ? "none" : "currentColor"}
      strokeWidth={sw}
      strokeLinecap="round"
      strokeLinejoin="round"
      style={style}
      aria-hidden="true"
    >
      {d !== undefined ? <path d={d} /> : children}
    </svg>
  );
}

export const Icons = {
  /* Lift: compose — open paper lines + pen, no forced seam (gestural). */
  newChat: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M4 6 H12.5" />
      <path d="M4 9.5 H9.5" />
      <path d="M14.4 13.6 l4-4 a1.6 1.6 0 0 1 2.3 2.3 l-6.2 6.2 -3 .7 .7 -3 z" />
    </Ico>
  ),
  /* Lift: ring open at the top pen-start + handle. */
  search: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M12.25 4.76 A6 6 0 1 1 8.75 4.76" />
      <path d="M14.7 14.7 L20 20" />
    </Ico>
  ),
  plugins: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <rect x="4" y="4" width="6.5" height="6.5" rx="1.5" />
      <rect x="13.5" y="4" width="6.5" height="6.5" rx="1.5" />
      <rect x="4" y="13.5" width="6.5" height="6.5" rx="1.5" />
      <rect x="13.5" y="13.5" width="6.5" height="6.5" rx="1.5" />
    </Ico>
  ),
  automations: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="12" cy="12" r="8" />
      <path d="M12 7.5V12l3 2" />
    </Ico>
  ),
  mobile: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <rect x="7" y="3" width="10" height="18" rx="2.5" />
      <path d="M11 18h2" />
    </Ico>
  ),
  /* Lift: open folder lid + seam'd body box. */
  folder: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M3.6 7.4 V6.3 a1.5 1.5 0 0 1 1.5-1.5 H8 a1.5 1.5 0 0 1 1.1 .48 L10.3 7.4" />
      <path d="M13.50 7.40 H18.00 A2.4 2.4 0 0 1 20.40 9.80 V16.00 A2.4 2.4 0 0 1 18.00 18.40 H6.00 A2.4 2.4 0 0 1 3.60 16.00 V9.80 A2.4 2.4 0 0 1 6.00 7.40 H10.50" />
    </Ico>
  ),
  /* Lift: gear ring with one seam + eight spokes. */
  settings: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.25 9.83 A2.5 2.5 0 1 1 10.75 9.83" />
      <path d="M16.00 12.00 L18.60 12.00 M14.83 14.83 L16.67 16.67 M12.00 16.00 L12.00 18.60 M9.17 14.83 L7.33 16.67 M8.00 12.00 L5.40 12.00 M9.17 9.17 L7.33 7.33 M12.00 8.00 L12.00 5.40 M14.83 9.17 L16.67 7.33" />
    </Ico>
  ),
  /* Lift: document with folded corner; outline opens at the top seam. */
  files: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M5.5 8 V5.5 a1.9 1.9 0 0 1 1.9-1.9 H12.8 L18.5 8.8 V18.5 a1.9 1.9 0 0 1-1.9 1.9 H7.4 a1.9 1.9 0 0 1-1.9-1.9 V11" />
      <path d="M12.8 3.6 V7.4 a1.4 1.4 0 0 0 1.4 1.4 H18.5" />
    </Ico>
  ),
  browser: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="12" cy="12" r="8.5" />
      <path d="M3.5 12h17M12 3.5c2.3 2.3 2.3 14.7 0 17M12 3.5c-2.3 2.3-2.3 14.7 0 17" />
    </Ico>
  ),
  review: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M9 12l2 2 4-4" />
      <rect x="3.5" y="4.5" width="17" height="15" rx="2.5" />
    </Ico>
  ),
  /* Lift: terminal frame with one top seam + prompt + line. */
  terminal: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.70 5.00 H17.50 A2.5 2.5 0 0 1 20.00 7.50 V16.50 A2.5 2.5 0 0 1 17.50 19.00 H6.50 A2.5 2.5 0 0 1 4.00 16.50 V7.50 A2.5 2.5 0 0 1 6.50 5.00 H10.30" />
      <path d="M8 9.6 L11 12.6 L8 15.6" />
      <path d="M12.8 15.6 H16.4" />
    </Ico>
  ),
  agents: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <rect x="5" y="7" width="14" height="11" rx="3" />
      <path d="M12 7V4M9 12h.01M15 12h.01M2.5 12.5v2M21.5 12.5v2" />
    </Ico>
  ),
  git: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="6" cy="6" r="2.5" />
      <circle cx="6" cy="18" r="2.5" />
      <circle cx="17" cy="9" r="2.5" />
      <path d="M6 8.5v7M17 11.5c0 3-3 3.5-6 4" />
    </Ico>
  ),
  plus: (p: IcoProps): ReactNode => <Ico {...p} d="M12 5v14M5 12h14" />,
  chevron: (p: IcoProps): ReactNode => <Ico {...p} d="M6 9l6 6 6-6" />,
  chevronR: (p: IcoProps): ReactNode => <Ico {...p} d="M9 6l6 6-6 6" />,
  /* Lift: mic capsule open at the top seam + stand. */
  mic: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M12 3.2 a3 3 0 0 1 3 3 V11 a3 3 0 0 1 -6 0 V6.2 a3 3 0 0 1 2 -2.8" />
      <path d="M5.5 11.5 a6.5 6.5 0 0 0 13 0 M12 18 v3" />
    </Ico>
  ),
  arrowUp: (p: IcoProps): ReactNode => <Ico {...p} d="M12 19V5M6 11l6-6 6 6" />,
  /* Lift: four-point star, traced from the top pen-start. */
  spark: (p: IcoProps): ReactNode => (
    <Ico {...p} d="M13.2 3.6 L19 10 l-5.2 1.4 L12 17 l-1.8 -5.6 L5 10 l5.2 -1.4 z" />
  ),
  pin: (p: IcoProps): ReactNode => <Ico {...p} d="M9 3h6l-1 5 3 3-5 1-1 8-1-8-5-1 3-3z" />,
  brain: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z" />
      <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z" />
    </Ico>
  ),
  brainSlash: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z" />
      <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z" />
      <path d="M3.2 20.4 20.8 3.6" />
    </Ico>
  ),
  /* Lift: archive lid box with one seam + body + handle. */
  archive: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.20 5.00 H19.50 A1 1 0 0 1 20.50 6.00 V8.00 A1 1 0 0 1 19.50 9.00 H4.50 A1 1 0 0 1 3.50 8.00 V6.00 A1 1 0 0 1 4.50 5.00 H10.80" />
      <path d="M5 9 v8 a2 2 0 0 0 2 2 h10 a2 2 0 0 0 2-2 V9" />
      <path d="M10 13 h4" />
    </Ico>
  ),
  /* Lift: panel frame with one top seam + left divider. */
  sidebar: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.50 4.50 H18.00 A2.5 2.5 0 0 1 20.50 7.00 V17.00 A2.5 2.5 0 0 1 18.00 19.50 H6.00 A2.5 2.5 0 0 1 3.50 17.00 V7.00 A2.5 2.5 0 0 1 6.00 4.50 H10.50" />
      <path d="M9.5 5 V19" />
    </Ico>
  ),
  /* Lift: minimize — a broken bar, the lift seam at centre. */
  minimize: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M7 14 H10.4" />
      <path d="M13.6 14 H17" />
    </Ico>
  ),
  expand: (p: IcoProps): ReactNode => <Ico {...p} d="M4 9V4h5M20 15v5h-5M20 9V4h-5M4 15v5h5" />,
  back: (p: IcoProps): ReactNode => <Ico {...p} d="M15 6l-6 6 6 6" />,
  fwd: (p: IcoProps): ReactNode => <Ico {...p} d="M9 6l6 6-6 6" />,
  drag: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="9" cy="6" r="1.1" fill="currentColor" stroke="none" />
      <circle cx="15" cy="6" r="1.1" fill="currentColor" stroke="none" />
      <circle cx="9" cy="12" r="1.1" fill="currentColor" stroke="none" />
      <circle cx="15" cy="12" r="1.1" fill="currentColor" stroke="none" />
      <circle cx="9" cy="18" r="1.1" fill="currentColor" stroke="none" />
      <circle cx="15" cy="18" r="1.1" fill="currentColor" stroke="none" />
    </Ico>
  ),
  /* Lift: close — a broken cross, four corner strokes meeting at the seam. */
  close: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M7 7 L10.4 10.4" />
      <path d="M17 7 L13.6 10.4" />
      <path d="M7 17 L10.4 13.6" />
      <path d="M17 17 L13.6 13.6" />
    </Ico>
  ),
  dots: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="6" cy="12" r="1.3" fill="currentColor" stroke="none" />
      <circle cx="12" cy="12" r="1.3" fill="currentColor" stroke="none" />
      <circle cx="18" cy="12" r="1.3" fill="currentColor" stroke="none" />
    </Ico>
  ),
  check: (p: IcoProps): ReactNode => <Ico {...p} d="M5 12.5l4.5 4.5L19 6.5" />,
  reset: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M4 12a8 8 0 1 1 2.3 5.6" />
      <path d="M4 20v-4h4" />
    </Ico>
  ),
  /* Lift: document with folded corner; outline opens at the top seam (alias of files). */
  file: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M5.5 8 V5.5 a1.9 1.9 0 0 1 1.9-1.9 H12.8 L18.5 8.8 V18.5 a1.9 1.9 0 0 1-1.9 1.9 H7.4 a1.9 1.9 0 0 1-1.9-1.9 V11" />
      <path d="M12.8 3.6 V7.4 a1.4 1.4 0 0 0 1.4 1.4 H18.5" />
    </Ico>
  ),
  diff: (p: IcoProps): ReactNode => <Ico {...p} d="M12 4v6M9 7h6M5 17h14" />,
  /* Lift: top node is an open ring (seam); the two child nodes stay closed. */
  branch: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M7.63 4.97 A2.3 2.3 0 1 1 4.37 4.97" />
      <circle cx="6" cy="17.4" r="2.3" />
      <circle cx="17.4" cy="8.6" r="2.3" />
      <path d="M6 8.9 V15.1" />
      <path d="M17.4 10.9 c0 4 -4 3.7 -7 4.7" />
    </Ico>
  ),
  cube: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M12 3l8 4.5v9L12 21l-8-4.5v-9z" />
      <path d="M12 12l8-4.5M12 12v9M12 12L4 7.5" />
    </Ico>
  ),
  /* Lift: full-screen — square ring with one seam on top. */
  maximize: (p: IcoProps): ReactNode => (
    <Ico
      {...p}
      d="M13.50 7.00 H15.00 A2 2 0 0 1 17.00 9.00 V15.00 A2 2 0 0 1 15.00 17.00 H9.00 A2 2 0 0 1 7.00 15.00 V9.00 A2 2 0 0 1 9.00 7.00 H10.50"
    />
  ),
  /* Lift: restore — back square corner + a seam'd front box. */
  restore: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M9 9 V8 a2 2 0 0 1 2 -2 h6 a2 2 0 0 1 2 2 v6 a2 2 0 0 1 -2 2 h-1" />
      <path d="M11.50 9.00 H13.00 A2 2 0 0 1 15.00 11.00 V17.00 A2 2 0 0 1 13.00 19.00 H7.00 A2 2 0 0 1 5.00 17.00 V11.00 A2 2 0 0 1 7.00 9.00 H8.50" />
    </Ico>
  ),
  /* Lift: panel frame with one top seam + centre divider. */
  split: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.50 4.50 H18.00 A2.5 2.5 0 0 1 20.50 7.00 V17.00 A2.5 2.5 0 0 1 18.00 19.50 H6.00 A2.5 2.5 0 0 1 3.50 17.00 V7.00 A2.5 2.5 0 0 1 6.00 4.50 H10.50" />
      <path d="M12 5 V19" />
    </Ico>
  ),
  /* Lift: four tiles; the top-left carries the single seam. */
  tile: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M8.10 4.50 H9.00 A1.5 1.5 0 0 1 10.50 6.00 V10.00 A1.5 1.5 0 0 1 9.00 11.50 H5.00 A1.5 1.5 0 0 1 3.50 10.00 V6.00 A1.5 1.5 0 0 1 5.00 4.50 H5.90" />
      <path d="M15.00 4.50 H19.00 A1.5 1.5 0 0 1 20.50 6.00 V10.00 A1.5 1.5 0 0 1 19.00 11.50 H15.00 A1.5 1.5 0 0 1 13.50 10.00 V6.00 A1.5 1.5 0 0 1 15.00 4.50 Z" />
      <path d="M5.00 13.50 H9.00 A1.5 1.5 0 0 1 10.50 15.00 V19.00 A1.5 1.5 0 0 1 9.00 20.50 H5.00 A1.5 1.5 0 0 1 3.50 19.00 V15.00 A1.5 1.5 0 0 1 5.00 13.50 Z" />
      <path d="M15.00 13.50 H19.00 A1.5 1.5 0 0 1 20.50 15.00 V19.00 A1.5 1.5 0 0 1 19.00 20.50 H15.00 A1.5 1.5 0 0 1 13.50 19.00 V15.00 A1.5 1.5 0 0 1 15.00 13.50 Z" />
    </Ico>
  ),
  cascade: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <rect x="4" y="4" width="12" height="12" rx="2" />
      <path d="M20 8v10a2 2 0 0 1-2 2H8" />
    </Ico>
  ),
  editor: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M8 9l-3 3 3 3M16 9l3 3-3 3M13.5 6l-3 12" />
    </Ico>
  ),
  gear: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="12" cy="12" r="2.6" />
      <path d="M12 3.5v2M12 18.5v2M20.5 12h-2M5.5 12h-2M18 6l-1.4 1.4M7.4 16.6 6 18M18 18l-1.4-1.4M7.4 7.4 6 6" />
    </Ico>
  ),
  /* Lift: panel frame with one top seam + right divider. */
  panelRight: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.50 4.50 H18.00 A2.5 2.5 0 0 1 20.50 7.00 V17.00 A2.5 2.5 0 0 1 18.00 19.50 H6.00 A2.5 2.5 0 0 1 3.50 17.00 V7.00 A2.5 2.5 0 0 1 6.00 4.50 H10.50" />
      <path d="M14.5 5 V19" />
    </Ico>
  ),
  /* Lift: open top diamond (seam) + two stacked sheets. */
  layers: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.4 4.55 L19.6 8 L12 12.2 L4.4 8 L10.6 4.55" />
      <path d="M4.4 12 L12 16.2 L19.6 12" />
      <path d="M4.4 16 L12 20.2 L19.6 16" />
    </Ico>
  ),
  tokens: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="9" cy="9" r="4.5" />
      <path d="M14 9.5a4.5 4.5 0 1 1-4 6.9" />
    </Ico>
  ),
  bolt: (p: IcoProps): ReactNode => <Ico {...p} d="M13 3 5 13h5l-1 8 8-10h-5z" />,
  add: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <rect x="3.5" y="3.5" width="17" height="17" rx="3.5" />
      <path d="M12 8.5v7M8.5 12h7" />
    </Ico>
  ),
  /* Lift: bell dome open at the top seam + clapper. */
  bell: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M9.8 4.6 a5.5 5.5 0 0 1 7.7 4.4 c0 4.5 2 5.5 2 5.5 H4.5 s2 -1 2 -5.5 a5.5 5.5 0 0 1 1.1 -3.3" />
      <path d="M10 19 a2 2 0 0 0 4 0" />
    </Ico>
  ),
  /* Lift: sun disc open at the top seam + rays. */
  sun: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.17 8.17 A4 4 0 1 1 10.83 8.17" />
      <path d="M12 2.5 V5 M12 19 V21.5 M2.5 12 H5 M19 12 H21.5 M5.1 5.1 L6.9 6.9 M17.1 17.1 l1.8 1.8 M18.9 5.1 L17.1 6.9 M6.9 17.1 L5.1 18.9" />
    </Ico>
  ),
  /* Lift: crescent — a single open stroke (gestural). */
  moon: (p: IcoProps): ReactNode => (
    <Ico {...p} d="M19.5 13.5 A8 8 0 1 1 10.5 4.2 a6.5 6.5 0 0 0 9.3 9.1" />
  ),
  zoomOut: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="11" cy="11" r="6.5" />
      <path d="M20 20l-4.2-4.2M8.3 11h5.4" />
    </Ico>
  ),
  zoomIn: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <circle cx="11" cy="11" r="6.5" />
      <path d="M20 20l-4.2-4.2M11 8.3v5.4M8.3 11h5.4" />
    </Ico>
  ),
  activity: (p: IcoProps): ReactNode => <Ico {...p} d="M3 12h3l2.5-7 5 14 2.5-7H21" />,
  /* Lift: head ring open at the top seam + shoulders. The previous hardcoded "M"
     initial was wrong for any real user (uiux-fix F011 C293). */
  user: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.35 4.66 A3.6 3.6 0 1 1 10.65 4.66" />
      <path d="M5.5 20 c.9 -3.7 3.4 -5.5 6.5 -5.5 s5.6 1.8 6.5 5.5" />
    </Ico>
  ),
  localKnowledge: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M4 19V7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12" />
      <path d="M4 19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2" />
      <path d="M9 7v14M9 11h6" />
    </Ico>
  ),
  /* Lift: top rack has one seam; the lower rack stays closed + status dots. */
  server: (p: IcoProps): ReactNode => (
    <Ico {...p}>
      <path d="M13.30 4.50 H18.30 A1.7 1.7 0 0 1 20.00 6.20 V8.80 A1.7 1.7 0 0 1 18.30 10.50 H5.70 A1.7 1.7 0 0 1 4.00 8.80 V6.20 A1.7 1.7 0 0 1 5.70 4.50 H10.70" />
      <path d="M5.70 13.50 H18.30 A1.7 1.7 0 0 1 20.00 15.20 V17.80 A1.7 1.7 0 0 1 18.30 19.50 H5.70 A1.7 1.7 0 0 1 4.00 17.80 V15.20 A1.7 1.7 0 0 1 5.70 13.50 Z" />
      <path d="M7.4 7.5 h.01 M7.4 16.5 h.01 M12 7.5 H16 M12 16.5 H16" />
    </Ico>
  ),
} as const;

export type IconName = keyof typeof Icons;
