import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import {
  checkToolCatalogConformance,
  checkToolCatalogConformanceNegatives,
  checkToolCatalogMigrationCloseout,
  checkToolCatalogSemanticNegatives,
  checkH1HandoffEvidence,
  h1ProvenanceShapeFailures,
  realProducerIdentityFailures,
  realSourceHeadFailures,
  ownedSourceDigestAt,
  isAncestorOfDev,
  H1_PROVENANCE_PATH,
  H1_OWNED_SOURCE_PATHS,
  activeToolCatalogMigrations,
  retiredBridgeMigrations,
  generatedToolCatalogManifest,
  legacyProjectionDiffers,
  loadToolCatalogProducer,
  toolCatalogManifestBytes,
  TOOL_CATALOG_MANIFEST_PATH,
  TOOL_CATALOG_MIGRATION_PATH,
  toolCatalogMigrationBytes,
} from "../check-tool-catalog-conformance.mjs";
import { scanToolRegistrySource } from "../lib/tool-catalog-inventory.mjs";
import { resolveHostExecutable } from "../lib/host-executable.mjs";
import {
  buildToolCatalogPerformanceDocument,
  buildSyntheticRegistrationSet,
  evaluateToolCatalogPerformanceEvidence,
  deriveLookupIterations,
  measureToolCatalogOverflowRejection,
  measureToolCatalogPerformance,
  measureToolCatalogPerformanceInFreshProcess,
  toolCatalogPerformanceBudgets,
  TOOL_CATALOG_OVERFLOW_TOOL_COUNT,
  TOOL_CATALOG_SYNTHETIC_TOOL_COUNT,
  validateToolCatalogPerformanceSamples,
} from "../check-tool-catalog-performance.mjs";
import * as sharedNegativeFixture from "../../tests/architecture/fixtures/tool-catalog-negatives/_shared.mjs";

const ROOT = process.cwd();
const PROBE = "packages/keiko-server/src/gateway-tool-calling-probe.ts";
const NEGATIVE_FIXTURES_DIR = "tests/architecture/fixtures/tool-catalog-negatives";
const gitExecutable = resolveHostExecutable("git");
// Hermetic Git helper for building throwaway H1-handoff repositories (no network, no shared
// state): every caller below creates its own mkdtempSync directory and removes it afterward.
function git(cwd, args) {
  return execFileSync(gitExecutable, args, { cwd, encoding: "utf8" }).trim();
}
function initHermeticRepo(cwd) {
  git(cwd, ["init", "--quiet", "--initial-branch=dev"]);
  git(cwd, ["config", "user.email", "h1-evidence@example.invalid"]);
  git(cwd, ["config", "user.name", "H1 Evidence Test"]);
}
describe("initial compiler and finite migration conformance gate", () => {
  // CI head 02785dbd (run 33983984303): this test does real producer/legacy-table compilation and
  // regeneration work (~1.8s locally) and was timing out at the shared 15s default on GitHub's
  // slower/shared runners. Never a wall-clock assertion inside the test itself (ADR-0156 D6 notes
  // the D12 reference machine is a developer container, not CI) -- only the harness's own budget
  // for how long the real work below may take before vitest gives up on it.
  it("checks the actual producer, legacy owner, generated bytes and finite inventory", async () => {
    expect(await checkToolCatalogConformance(ROOT)).toEqual([]);
    expect(checkToolCatalogConformanceNegatives()).toEqual([]);
    expect(await toolCatalogManifestBytes(ROOT)).toBe(await toolCatalogManifestBytes(ROOT));
    expect(readFileSync(join(ROOT, TOOL_CATALOG_MIGRATION_PATH), "utf8")).toBe(
      await toolCatalogMigrationBytes(ROOT),
    );
    const migration = JSON.parse(await toolCatalogMigrationBytes(ROOT));
    expect(migration.inventory).toEqual([]);
    expect(migration.historicalInventory).toEqual({
      rowCount: 43,
      digest: expect.stringMatching(/^[a-f0-9]{64}$/u),
    });
    expect(migration.nonDispatchProbes).toHaveLength(1);
    expect(
      migration.inventory.some((entry) => entry.id === migration.nonDispatchProbes[0].id),
    ).toBe(false);
    expect(JSON.parse(readFileSync(join(ROOT, TOOL_CATALOG_MANIFEST_PATH), "utf8"))).toEqual(
      await generatedToolCatalogManifest(ROOT),
    );
  }, 30_000);

  // #3406/#3414 (F6): the non-authorizing pending-H1 handoff record for #3386's H1 local
  // repository-search handler. Fails-before: prior to this record's addition, the generated
  // migration document carried no `pendingH1` field at all, so #3406's acceptance criterion
  // (owner, canonical tool reference, prerequisite #3411 merge identity, removal issue #3414,
  // initially-empty landedDevCommit/landedTreeDigest) existed only as prose in
  // governed-tool-migration.md, never as an actual record.
  it("carries the non-authorizing pending-H1 handoff record with exactly its six fields", async () => {
    const migration = JSON.parse(await toolCatalogMigrationBytes(ROOT));
    expect(Object.keys(migration.pendingH1).sort()).toEqual(
      [
        "owner",
        "canonicalTool",
        "prerequisiteMerge",
        "removalIssue",
        "landedDevCommit",
        "landedTreeDigest",
      ].sort(),
    );
    expect(migration.pendingH1.owner).toBe(3386);
    expect(migration.pendingH1.canonicalTool).toEqual({
      canonicalId: "keiko.repo.search",
      contractVersion: 1,
    });
    expect(migration.pendingH1.prerequisiteMerge.issue).toBe(3411);
    expect(migration.pendingH1.prerequisiteMerge.contractDigest).toBe(
      migration.sourceContractDigest,
    );
    expect(migration.pendingH1.removalIssue).toBe(3414);
    // Initially empty: no code path may treat this record as an authorization while these are
    // null -- only #3414 may populate them once H1 actually reaches dev.
    expect(migration.pendingH1.landedDevCommit).toBeNull();
    expect(migration.pendingH1.landedTreeDigest).toBeNull();
  });
  it("pins the one non-dispatch readiness probe without granting a path exception", () => {
    const source = readFileSync(join(ROOT, PROBE), "utf8");
    expect(scanToolRegistrySource(PROBE, source, new Set())).toEqual([]);
    for (const mutation of [
      source.replaceAll("report_readiness", "read_file"),
      source.replace('enum: ["ok"]', 'enum: ["ok", "write"]'),
      source.replace("additionalProperties: false", "additionalProperties: true"),
      source.replaceAll("toolCallingBody", "workspaceToolBody"),
      source + '\nconst tool = {name: "keiko_repo_search", parameters: {}};',
    ])
      expect(scanToolRegistrySource(PROBE, mutation, new Set()).length).toBeGreaterThan(0);
    expect(
      scanToolRegistrySource("packages/keiko-server/src/copied-probe.ts", source, new Set()).length,
    ).toBeGreaterThan(0);
  });
  it("accepts projection consumers and text samples, but rejects concrete schema and ID rows", () => {
    const file = "packages/keiko-server/src/new-consumer.ts";
    expect(
      scanToolRegistrySource(
        file,
        'const tools = gatewayToolDefinitions(catalog, profile); const sample = "name: read_file, parameters: {}";',
        new Set(),
      ),
    ).toEqual([]);
    for (const source of [
      'const tools = [{name: "new_alias", parameters: {}}];',
      'const tools = [{"name": "new_alias", inputSchema: {}}];',
      'const ref = {canonicalId: "keiko.repo.search", contractVersion: 1};',
    ])
      expect(scanToolRegistrySource(file, source, new Set()).length).toBeGreaterThan(0);
    expect(
      scanToolRegistrySource(
        file,
        'const tool = {name: "new_alias", parameters: {}};',
        new Set([file]),
      ),
    ).toEqual([]);
  });
});
describe("closeout enforcement", () => {
  it("requires the producer checkpoint even before the final dev merge exists", async () => {
    const errors = await checkToolCatalogMigrationCloseout(ROOT, {
      checkpointPath: "docs/architecture/absent-h1-checkpoint.json",
    });
    expect(errors).toContain(
      "H1 handoff evidence missing: no docs/architecture/absent-h1-checkpoint.json",
    );
  });
  it("passes only after the source-derived active migration inventory reaches zero", async () => {
    const migration = JSON.parse(await toolCatalogMigrationBytes(ROOT));
    expect(activeToolCatalogMigrations(ROOT)).toEqual([]);
    expect(migration.inventory).toEqual([]);
    // The repository scan owns the active inventory. Producer qualification is independently
    // covered by real, hermetic Git histories in h1-producer-checkpoint.test.mjs; a fresh dev
    // clone after squash need not contain the original PR's private source objects for this unit.
    expect(
      await checkToolCatalogMigrationCloseout(
        ROOT,
        {},
        { producerCheckpointFailures: async () => [] },
      ),
    ).toEqual([]);
  });
  it.each([
    [
      "packages/keiko-contracts/src/gateway.ts",
      "readonly tools?: readonly ToolDefinition[]",
      "generic-gateway",
    ],
    [
      "packages/keiko-contracts/src/governed-tool-bridge.ts",
      "LegacyNamedToolInvocation",
      "generic-tool-port",
    ],
    [
      "packages/keiko-tool-catalog/src/invocation.ts",
      'value.kind === "legacy-name"',
      "generic-tool-port",
    ],
    ["packages/keiko-model-gateway/src/toolCatalogBridge.ts", "legacySession", "generic-gateway"],
    [
      "packages/keiko-model-gateway/src/realtime-voice-adapter.ts",
      "RealtimeSessionTool",
      "realtime-compatibility",
    ],
  ])("restores migration %s when retired bridge source %s returns", (path, probe, id) => {
    expect(retiredBridgeMigrations({ [path]: probe })).toEqual([id]);
  });
});
describe("compiler measurements reuse the existing sample and percentile convention", () => {
  // CI head 02785dbd (run 33983984303): 30 real compile/lookup samples across both the
  // legacy-native and largest-synthetic-catalog cases (~6.5-7s locally) was timing out at the
  // shared 15s default on GitHub's slower/shared runners. Bounded by real OPERATION counts, never
  // a wall-clock threshold (see check-tool-catalog-performance.mjs's own header comment) -- only
  // the harness's own budget for how long that bounded real work may take before vitest gives up.
  it("measures real fixture work per case with a deterministic clock and rejects incomplete work", async () => {
    let now = 0;
    const evidence = await measureToolCatalogPerformance(ROOT, () => ++now);
    expect(Object.keys(evidence.cases)).toEqual([
      "legacy-native-6-tool",
      `synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool`,
    ]);
    expect(evidence.overflow).toEqual({
      attemptedToolCount: TOOL_CATALOG_OVERFLOW_TOOL_COUNT,
      rejected: true,
      reason: "input-bound",
    });
    for (const testCase of Object.values(evidence.cases)) {
      expect(testCase.samples).toHaveLength(30);
      expect(testCase.aggregates.coldCompileMs).toEqual({
        minimum: 1,
        maximum: 1,
        p50: 1,
        p95: 1,
      });
      expect(validateToolCatalogPerformanceSamples(testCase.samples)).toEqual([]);
    }
    // Never a hardcoded "6": the legacy case's expected tool count is read back from its own
    // first sample, and the synthetic case is a completely different, much larger count.
    const legacyCase = evidence.cases["legacy-native-6-tool"];
    const syntheticCase =
      evidence.cases[`synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool`];
    expect(legacyCase.toolCount).toBe(6);
    expect(syntheticCase.toolCount).toBe(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT);
    expect(syntheticCase.toolCount).toBeGreaterThan(legacyCase.toolCount * 10);
    expect(validateToolCatalogPerformanceSamples([])).not.toEqual([]);
    for (const change of [
      { coldCompileMs: NaN },
      { lookupBatchMs: 0 },
      { toolCount: 0 },
      { toolCount: legacyCase.samples[0].toolCount + 1 },
      { lookups: 0 },
      { projectionDigest: "bad" },
    ]) {
      const samples = structuredClone(legacyCase.samples);
      samples[0] = { ...samples[0], ...change };
      expect(validateToolCatalogPerformanceSamples(samples).length).toBeGreaterThan(0);
    }
  }, 45_000);
  it("isolates calibration and candidate measurements in separate fresh processes", async () => {
    const source = readFileSync(join(ROOT, "scripts/check-tool-catalog-performance.mjs"), "utf8");
    expect(source).toContain(
      "const calibrationRaw = await measureToolCatalogPerformanceInFreshProcess(root);",
    );
    expect(source).toContain(
      "const measurementRaw = await measureToolCatalogPerformanceInFreshProcess(root);",
    );

    const evidence = await measureToolCatalogPerformanceInFreshProcess(ROOT);
    expect(evidence.environment).toEqual({
      platform: process.platform,
      architecture: process.arch,
      nodeVersion: process.version,
    });
    expect(Object.values(evidence.cases).every(({ samples }) => samples.length === 30)).toBe(true);
  }, 45_000);
  it("derives lookup iteration counts from a fixed operation budget, never a wall-clock duration", () => {
    expect(deriveLookupIterations(6)).toBeGreaterThan(
      deriveLookupIterations(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT),
    );
    expect(deriveLookupIterations(6) * 6).toBeLessThanOrEqual(6_000 + 6);
    expect(deriveLookupIterations(1_000_000)).toBe(1);
  });
  it("proves bounded construction: the largest synthetic catalog compiles, one past it is rejected closed", async () => {
    const producer = await loadToolCatalogProducer(ROOT);
    const catalog = producer.createKeikoToolCatalog([
      buildSyntheticRegistrationSet(producer, TOOL_CATALOG_SYNTHETIC_TOOL_COUNT),
    ]);
    expect(catalog.descriptors).toHaveLength(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT);
    // Fails-before: without the overflow guard, a caller could construct an unbounded catalog
    // (or the byte-budget check could silently regress) with nothing proving the ceiling holds.
    expect(measureToolCatalogOverflowRejection(producer)).toEqual({
      attemptedToolCount: TOOL_CATALOG_OVERFLOW_TOOL_COUNT,
      rejected: true,
      reason: "input-bound",
    });
  });
  it("separates calibrated reference verdicts from deterministic CI work validation", async () => {
    let calibrationClock = 0;
    const calibrationRaw = await measureToolCatalogPerformance(ROOT, () => ++calibrationClock);
    // This test owns verdict semantics. Derive a slower input from real producer output rather
    // than executing another complete benchmark under coverage just to advance its fake clock.
    // Scaling preserves the producer's sample/aggregate relation without restating percentiles.
    const measurementRaw = structuredClone(calibrationRaw);
    for (const testCase of Object.values(measurementRaw.cases)) {
      for (const metric of ["coldCompileMs", "lookupBatchMs"]) {
        for (const sample of testCase.samples) sample[metric] *= 10;
        for (const key of Object.keys(testCase.aggregates[metric]))
          testCase.aggregates[metric][key] *= 10;
      }
    }
    const environment = {
      platform: "linux",
      architecture: "arm64",
      nodeVersion: "v24.18.0",
      logicalCores: 16,
      totalMemoryBytes: 24_000_000_000,
      containerImage:
        "node:24.18.0-bookworm@sha256:5711a0d445a1af54af9589066c646df387d1831a608226f4cd694fc59e745059",
    };
    const calibration = buildToolCatalogPerformanceDocument(calibrationRaw, {
      role: "calibration",
      measuredAtIso: "2026-09-06T00:00:00.000Z",
      measurementHarnessSha256: "a".repeat(64),
      environment,
    });
    const budget = toolCatalogPerformanceBudgets(calibration);
    const measurement = buildToolCatalogPerformanceDocument(measurementRaw, {
      role: "measurement",
      measuredAtIso: "2026-09-06T00:01:00.000Z",
      measurementHarnessSha256: "a".repeat(64),
      calibrationSha256: calibration.documentSha256,
      environment,
    });
    expect(evaluateToolCatalogPerformanceEvidence(measurement, calibration, budget)).toEqual({
      defects: [],
      verdicts: [
        "legacy-native-6-tool coldCompileMs exceeds the calibrated p95 budget",
        "legacy-native-6-tool lookupBatchMs exceeds the calibrated p95 budget",
        `synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool coldCompileMs exceeds the calibrated p95 budget`,
        `synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool lookupBatchMs exceeds the calibrated p95 budget`,
      ],
    });
    const withinBudget = buildToolCatalogPerformanceDocument(calibrationRaw, {
      role: "measurement",
      measuredAtIso: "2026-09-06T00:01:00.000Z",
      measurementHarnessSha256: "a".repeat(64),
      calibrationSha256: calibration.documentSha256,
      environment,
    });
    expect(evaluateToolCatalogPerformanceEvidence(withinBudget, calibration, budget)).toEqual({
      defects: [],
      verdicts: [],
    });
    const alteredBudget = structuredClone(budget);
    alteredBudget.maximumP95Ms["legacy-native-6-tool"].coldCompileMs += 1;
    expect(
      evaluateToolCatalogPerformanceEvidence(withinBudget, calibration, alteredBudget).defects,
    ).toEqual(["catalog performance budget differs from calibration"]);
    const renamedRaw = structuredClone(calibrationRaw);
    renamedRaw.cases = {
      renamed: renamedRaw.cases["legacy-native-6-tool"],
      [`synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool`]:
        renamedRaw.cases[`synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool`],
    };
    expect(() =>
      buildToolCatalogPerformanceDocument(renamedRaw, {
        role: "calibration",
        measuredAtIso: "2026-09-06T00:00:00.000Z",
        measurementHarnessSha256: "a".repeat(64),
        environment,
      }),
    ).toThrow("catalog performance cases has unexpected fields");
    const mismatchedCountRaw = structuredClone(calibrationRaw);
    mismatchedCountRaw.cases["legacy-native-6-tool"].toolCount += 1;
    expect(() =>
      buildToolCatalogPerformanceDocument(mismatchedCountRaw, {
        role: "calibration",
        measuredAtIso: "2026-09-06T00:00:00.000Z",
        measurementHarnessSha256: "a".repeat(64),
        environment,
      }),
    ).toThrow("catalog performance case tool count differs from its samples");
    const wrongOverflowRaw = structuredClone(calibrationRaw);
    wrongOverflowRaw.overflow.attemptedToolCount -= 1;
    expect(() =>
      buildToolCatalogPerformanceDocument(wrongOverflowRaw, {
        role: "calibration",
        measuredAtIso: "2026-09-06T00:00:00.000Z",
        measurementHarnessSha256: "a".repeat(64),
        environment,
      }),
    ).toThrow("catalog overflow fixture count differs");
    const driftedRaw = structuredClone(calibrationRaw);
    driftedRaw.subject.sourceTreeSha256 = "b".repeat(64);
    const sourceDrift = buildToolCatalogPerformanceDocument(driftedRaw, {
      role: "measurement",
      measuredAtIso: "2026-09-06T00:01:00.000Z",
      measurementHarnessSha256: "a".repeat(64),
      calibrationSha256: calibration.documentSha256,
      environment,
    });
    expect(
      evaluateToolCatalogPerformanceEvidence(sourceDrift, calibration, budget).defects,
    ).toContain("catalog performance subject differs from calibration");
    const rulerDrift = buildToolCatalogPerformanceDocument(calibrationRaw, {
      role: "measurement",
      measuredAtIso: "2026-09-06T00:01:00.000Z",
      measurementHarnessSha256: "b".repeat(64),
      calibrationSha256: calibration.documentSha256,
      environment,
    });
    expect(
      evaluateToolCatalogPerformanceEvidence(rulerDrift, calibration, budget).defects,
    ).toContain("catalog performance subject differs from calibration");
    const environmentDrift = buildToolCatalogPerformanceDocument(calibrationRaw, {
      role: "measurement",
      measuredAtIso: "2026-09-06T00:01:00.000Z",
      measurementHarnessSha256: "a".repeat(64),
      calibrationSha256: calibration.documentSha256,
      environment: { ...environment, totalMemoryBytes: environment.totalMemoryBytes + 1 },
    });
    expect(
      evaluateToolCatalogPerformanceEvidence(environmentDrift, calibration, budget).defects,
    ).toContain("catalog performance environment differs from calibration");
    const substitutionRaw = structuredClone(calibrationRaw);
    substitutionRaw.cases[`synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool`] =
      structuredClone(substitutionRaw.cases["legacy-native-6-tool"]);
    const substitutedMeasurement = buildToolCatalogPerformanceDocument(substitutionRaw, {
      role: "measurement",
      measuredAtIso: "2026-09-06T00:01:00.000Z",
      measurementHarnessSha256: "a".repeat(64),
      calibrationSha256: calibration.documentSha256,
      environment,
    });
    expect(
      evaluateToolCatalogPerformanceEvidence(substitutedMeasurement, calibration, budget),
    ).toEqual({
      defects: [
        `synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool case identity differs from calibration`,
      ],
      verdicts: [],
    });
  }, 45_000);
});
describe("#3415 catalog-semantic negative-fixture matrix", () => {
  const fixtureFiles = readdirSync(join(ROOT, NEGATIVE_FIXTURES_DIR)).filter(
    (name) => name !== "_shared.mjs",
  );
  it("covers one fixture file per attack class named by issue #3415 AC2", () => {
    expect(fixtureFiles.sort()).toEqual(
      [
        "alias-collision-or-confusable.mjs",
        "duplicate-handler.mjs",
        "implicit-latest-resolution.mjs",
        "legacy-table-reintroduction.mjs",
        "missing-handler.mjs",
        "orphan-handler.mjs",
        "policy-effect-mismatch.mjs",
        "projection-drift.mjs",
        "stale-downgraded-compatibility.mjs",
        "version-mismatched-handler.mjs",
      ].sort(),
    );
  });
  it("is not reachable from any production source root", () => {
    // The AST inventory scanner only walks packages/*/src and src/; this asserts the stronger,
    // literal claim that no such file contains the fixture directory's specifier at all.
    const needle = "tool-catalog-negatives";
    const productionRoots = [
      join(ROOT, "src"),
      ...readdirSync(join(ROOT, "packages"), { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => join(ROOT, "packages", entry.name, "src")),
    ];
    const offenders = [];
    for (const directory of productionRoots) {
      let entries;
      try {
        entries = readdirSync(directory, { withFileTypes: true, recursive: true });
      } catch {
        continue;
      }
      for (const entry of entries) {
        if (!entry.isFile() || !/\.[cm]?[jt]sx?$/u.test(entry.name)) continue;
        const filePath = join(entry.parentPath ?? directory, entry.name);
        if (readFileSync(filePath, "utf8").includes(needle)) offenders.push(filePath);
      }
    }
    expect(offenders).toEqual([]);
  });
  it("rejects every fixture with the real producer's own failure reason, one class at a time", async () => {
    const producer = await loadToolCatalogProducer(ROOT);
    const fixture = (name) => import(pathToFileURL(join(ROOT, NEGATIVE_FIXTURES_DIR, name)).href);

    const missingHandler = await fixture("missing-handler.mjs");
    expect(sharedNegativeFixture.expectRejection(() => missingHandler.attempt(producer))).toEqual({
      rejected: true,
      reason: missingHandler.EXPECTED_REASON,
    });

    const orphanHandler = await fixture("orphan-handler.mjs");
    expect(sharedNegativeFixture.expectRejection(() => orphanHandler.attempt(producer))).toEqual({
      rejected: true,
      reason: orphanHandler.EXPECTED_REASON,
    });

    const duplicateHandler = await fixture("duplicate-handler.mjs");
    expect(sharedNegativeFixture.expectRejection(() => duplicateHandler.attempt(producer))).toEqual(
      { rejected: true, reason: duplicateHandler.EXPECTED_REASON },
    );

    const versionMismatched = await fixture("version-mismatched-handler.mjs");
    expect(
      sharedNegativeFixture.expectRejection(() => versionMismatched.attempt(producer)),
    ).toEqual({ rejected: true, reason: versionMismatched.EXPECTED_REASON });

    const alias = await fixture("alias-collision-or-confusable.mjs");
    expect(sharedNegativeFixture.expectRejection(() => alias.attemptCollision(producer))).toEqual({
      rejected: true,
      reason: alias.EXPECTED_REASONS.collision,
    });
    expect(sharedNegativeFixture.expectRejection(() => alias.attemptConfusable(producer))).toEqual({
      rejected: true,
      reason: alias.EXPECTED_REASONS.confusable,
    });

    const drift = await fixture("projection-drift.mjs");
    expect(sharedNegativeFixture.expectRejection(() => drift.attempt(producer))).toEqual({
      rejected: true,
      reason: drift.EXPECTED_REASON,
    });

    const policyEffect = await fixture("policy-effect-mismatch.mjs");
    expect(sharedNegativeFixture.expectRejection(() => policyEffect.attempt(producer))).toEqual({
      rejected: true,
      reason: policyEffect.EXPECTED_REASON,
    });

    const compatibility = await fixture("stale-downgraded-compatibility.mjs");
    expect(
      sharedNegativeFixture.expectRejection(() => compatibility.attemptStale(producer)),
    ).toEqual({ rejected: true, reason: compatibility.EXPECTED_REASONS.stale });
    expect(
      sharedNegativeFixture.expectRejection(() => compatibility.attemptDowngraded(producer)),
    ).toEqual({ rejected: true, reason: compatibility.EXPECTED_REASONS.downgraded });

    const implicitLatest = await fixture("implicit-latest-resolution.mjs");
    expect(
      sharedNegativeFixture.expectRejection(() =>
        implicitLatest.attemptOmittedContractVersion(producer),
      ),
    ).toEqual({ rejected: true, reason: implicitLatest.EXPECTED_REASON });
    expect(
      sharedNegativeFixture.expectRejection(() => implicitLatest.attemptLatestLiteral(producer)),
    ).toEqual({ rejected: true, reason: implicitLatest.EXPECTED_REASON });

    const legacyTable = await fixture("legacy-table-reintroduction.mjs");
    const legacyResult = await legacyTable.attempt(producer, ROOT, legacyProjectionDiffers);
    expect(sharedNegativeFixture.expectRejection(() => legacyResult)).toEqual({
      rejected: true,
      reason: legacyTable.EXPECTED_REASON,
    });
    // The comparator must actually distinguish drift from no-drift, not just always report true.
    const catalog = producer.createInitialToolCatalog();
    const realDefinitions = producer.gatewayToolDefinitions(catalog, {
      id: "legacy-native",
      version: 1,
    });
    const legacy = await import(
      pathToFileURL(join(ROOT, "packages/keiko-tools/dist/schemas.js")).href
    );
    expect(legacyProjectionDiffers(realDefinitions, legacy.TOOL_DEFINITIONS)).toBe(false);
  });
  it("wires every fixture into the packaged gate via checkToolCatalogSemanticNegatives", async () => {
    // Fails-before: before this function existed, none of the above fixtures were exercised by
    // `npm run check:tool-catalog-conformance` or `npm run arch:check:negative` at all.
    expect(await checkToolCatalogSemanticNegatives(ROOT)).toEqual([]);
  });
});

// Shared by both the recheck describe block below and the sourceHead-binding describe block
// (review 3941891302) further down -- one well-formed fixture record, never restated per file.
const VALID_RECORD = Object.freeze({
  schemaVersion: 1,
  integrationPr: 3394,
  sourceHead: "a".repeat(40),
  treeDigest: "b".repeat(64),
  verificationRef: "https://example.invalid/verification",
  reviewRef: "https://example.invalid/review",
  catalogRevision: "revision-1",
  profile: { id: "legacy-native", version: 1 },
  projectionDigest: "c".repeat(64),
  handlerSetDigest: "d".repeat(64),
  currentHead: "e".repeat(40),
});

describe("#3414 AC7 / #3415 AC5-AC6: H1 dev-handoff evidence recheck", () => {
  let workDir;
  afterEach(() => {
    if (workDir !== undefined) rmSync(workDir, { recursive: true, force: true });
    workDir = undefined;
  });
  it.each([
    { integrationPr: 0 },
    { sourceHead: "not-hex" },
    { currentHead: "short" },
    { treeDigest: "not-hex" },
    { projectionDigest: "too-short" },
    { handlerSetDigest: "not-hex" },
    { profile: { id: "legacy-native" } },
    { profile: "legacy-native" },
    { catalogRevision: "" },
    { verificationRef: "" },
    { reviewRef: "" },
  ])("rejects a malformed durable record %j", (patch) => {
    expect(h1ProvenanceShapeFailures({ ...VALID_RECORD, ...patch }).length).toBeGreaterThan(0);
  });
  it("rejects a record missing or adding a field beyond the exact H1Provenance shape", () => {
    const withoutSchemaVersion = { ...VALID_RECORD };
    delete withoutSchemaVersion.schemaVersion;
    expect(h1ProvenanceShapeFailures(withoutSchemaVersion)).toEqual([
      "H1 handoff evidence malformed: durable record does not carry exactly the H1Provenance fields",
    ]);
    expect(h1ProvenanceShapeFailures({ ...VALID_RECORD, extraField: "x" })).toEqual([
      "H1 handoff evidence malformed: durable record does not carry exactly the H1Provenance fields",
    ]);
  });
  it("accepts a fully well-formed durable record", () => {
    expect(h1ProvenanceShapeFailures(VALID_RECORD)).toEqual([]);
  });
  it("passes while H1 has not landed to dev (both fields honestly null)", async () => {
    expect(
      await checkH1HandoffEvidence(ROOT, { landedDevCommit: null, landedTreeDigest: null }),
    ).toEqual([]);
  });
  it("fails closed on a partially populated pending record", async () => {
    expect(
      await checkH1HandoffEvidence(ROOT, {
        landedDevCommit: "a".repeat(40),
        landedTreeDigest: null,
      }),
    ).toEqual([
      "H1 handoff evidence partially populated: landedDevCommit and landedTreeDigest must be set together",
    ]);
  });
  it("fails closed on a malformed landedDevCommit/landedTreeDigest shape", async () => {
    expect(
      await checkH1HandoffEvidence(ROOT, {
        landedDevCommit: "not-a-sha",
        landedTreeDigest: "b".repeat(64),
      }),
    ).toEqual([
      "H1 handoff evidence malformed: pendingH1.landedDevCommit is not a 40-hex commit SHA",
    ]);
    expect(
      await checkH1HandoffEvidence(ROOT, {
        landedDevCommit: "a".repeat(40),
        landedTreeDigest: "not-a-digest",
      }),
    ).toEqual(["H1 handoff evidence malformed: pendingH1.landedTreeDigest is not a 64-hex digest"]);
  });
  it("fails closed when no durable H1Provenance record exists", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    const errors = await checkH1HandoffEvidence(root, {
      landedDevCommit: "a".repeat(40),
      landedTreeDigest: "b".repeat(64),
    });
    expect(errors).toEqual([`H1 handoff evidence missing: no ${H1_PROVENANCE_PATH}`]);
  });
  it("validates an external postmerge receipt through the same reachability and identity gates", async () => {
    workDir = mkdtempSync(join(tmpdir(), "keiko-h1-external-"));
    const root = join(workDir, "source");
    mkdirSync(root);
    writeFileSync(join(workDir, "handoff.json"), JSON.stringify(VALID_RECORD));
    const pending = {
      landedDevCommit: VALID_RECORD.currentHead,
      landedTreeDigest: VALID_RECORD.treeDigest,
    };
    const visited = [];
    const deps = {
      provenancePath: "../handoff.json",
      execute: () => "",
      sourceHeadFailures: async (_root, record) => {
        visited.push(record.sourceHead);
        return [];
      },
      identityFailures: async (_root, record) => {
        visited.push(record.projectionDigest);
        return [];
      },
    };
    expect(await checkH1HandoffEvidence(root, pending, deps)).toEqual([]);
    expect(visited).toEqual([VALID_RECORD.sourceHead, VALID_RECORD.projectionDigest]);
    expect(
      await checkH1HandoffEvidence(root, pending, {
        ...deps,
        identityFailures: async () => ["fixture projection mismatch"],
      }),
    ).toEqual(["fixture projection mismatch"]);
    expect(await checkH1HandoffEvidence(root, pending)).toEqual([
      `H1 handoff evidence missing: no ${H1_PROVENANCE_PATH}`,
    ]);
  });
  it("fails closed when the durable record exists but is malformed JSON", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    writeFileSync(join(root, H1_PROVENANCE_PATH), "{not json");
    expect(
      await checkH1HandoffEvidence(root, {
        landedDevCommit: "a".repeat(40),
        landedTreeDigest: "b".repeat(64),
      }),
    ).toEqual(["H1 handoff evidence malformed: not valid JSON"]);
  });
  it("fails closed on a stale record (treeDigest/currentHead do not match pendingH1)", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(VALID_RECORD));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: "f".repeat(40), landedTreeDigest: "b".repeat(64) },
      { execute: () => "", identityFailures: async () => [] },
    );
    expect(errors).toContain(
      "H1 handoff evidence stale: durable record's currentHead does not match pendingH1.landedDevCommit",
    );
  });
  it("fails closed when landedDevCommit is not reachable from dev", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD, currentHead: VALID_RECORD.currentHead };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: record.currentHead, landedTreeDigest: record.treeDigest },
      {
        execute: () => {
          throw new Error("not an ancestor");
        },
        identityFailures: async () => [],
        sourceHeadFailures: async () => [],
      },
    );
    expect(errors).toEqual([
      `H1 handoff evidence unreachable: landedDevCommit ${record.currentHead} is not an ancestor of dev`,
    ]);
  });
  it("passes when the durable record is fresh, reachable, and identity-agreeing", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: record.currentHead, landedTreeDigest: record.treeDigest },
      { execute: () => "", identityFailures: async () => [], sourceHeadFailures: async () => [] },
    );
    expect(errors).toEqual([]);
  });
  it("fails closed on an identity mismatch against the current producer", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: record.currentHead, landedTreeDigest: record.treeDigest },
      {
        execute: () => "",
        identityFailures: async () => [
          "H1 handoff evidence identity mismatch: catalogRevision does not match the current producer",
        ],
        sourceHeadFailures: async () => [],
      },
    );
    expect(errors).toEqual([
      "H1 handoff evidence identity mismatch: catalogRevision does not match the current producer",
    ]);
  });
  it("retains the independent final-landing phase while producer qualification is injected", async () => {
    expect(
      await checkToolCatalogMigrationCloseout(
        ROOT,
        {},
        { producerCheckpointFailures: async () => [] },
      ),
    ).toEqual([]);
  });
  // The stubbed `execute` above proves the recheck's own control flow. This proves the REAL,
  // unstubbed git-reachability check against this actual repository: `dev`'s own current tip is
  // trivially its own ancestor, and a well-formed but nonexistent commit SHA is not. Skips (rather
  // than failing) in a checkout with no local `dev` ref -- this pins real behavior, not the
  // presence of that ref, which this test does not control.
  it("the real (unstubbed) ancestor check agrees with this repository's actual git history", () => {
    let devTip;
    try {
      devTip = execFileSync("git", ["rev-parse", "--verify", "dev"], {
        cwd: ROOT,
        encoding: "utf8",
      }).trim();
    } catch {
      return;
    }
    expect(isAncestorOfDev(devTip, ROOT, execFileSync)).toBe(true);
    expect(isAncestorOfDev("f".repeat(40), ROOT, execFileSync)).toBe(false);
  });
  // The tests above stub `identityFailures` to isolate the recheck's own control flow. This proves
  // the REAL, unstubbed identity cross-check actually agrees with the real producer, and actually
  // detects a mismatch -- not just that a stub was called. Calls it directly against ROOT (never
  // through a fake temp root, which has no packages/keiko-tool-catalog/dist to load).
  it("the real (unstubbed) producer identity check agrees with itself and catches a real mismatch", async () => {
    const producer = await loadToolCatalogProducer(ROOT);
    const catalog = producer.createInitialToolCatalog();
    const projection = producer.compileToolProjection(catalog, { id: "legacy-native", version: 1 });
    const matching = {
      ...VALID_RECORD,
      profile: { id: "legacy-native", version: 1 },
      catalogRevision: projection.catalogRevision,
      projectionDigest: projection.projectionDigest,
    };
    expect(await realProducerIdentityFailures(ROOT, matching)).toEqual([]);
    expect(
      await realProducerIdentityFailures(ROOT, { ...matching, catalogRevision: "wrong-revision" }),
    ).toContain(
      "H1 handoff evidence identity mismatch: catalogRevision does not match the current producer",
    );
    expect(
      await realProducerIdentityFailures(ROOT, { ...matching, projectionDigest: "e".repeat(64) }),
    ).toContain(
      "H1 handoff evidence identity mismatch: projectionDigest does not match the current producer",
    );
  });
});

// Review 3941891302 [P2]: the recheck compared only two caller-declared tree digests and never
// resolved `sourceHead` against Git or verified its tree/owned-source content against the
// consuming commit -- the reviewer demonstrated this with a nonexistent `sourceHead` and a
// fabricated `treeDigest` repeated in both records, which passed with zero failures. Every test
// below uses a hermetic, throwaway `git init` repository (no network, no shared state).
describe("review 3941891302: sourceHead must resolve against real Git and bind to the consuming commit", () => {
  let workDir;
  afterEach(() => {
    if (workDir !== undefined) rmSync(workDir, { recursive: true, force: true });
    workDir = undefined;
  });

  it("H1_OWNED_SOURCE_PATHS derives from the canonical implementation annex and names real, existing files", () => {
    expect(H1_OWNED_SOURCE_PATHS.length).toBeGreaterThan(0);
    expect(H1_OWNED_SOURCE_PATHS).toEqual([...H1_OWNED_SOURCE_PATHS].sort());
    for (const path of H1_OWNED_SOURCE_PATHS) {
      expect(() => readFileSync(join(ROOT, path), "utf8")).not.toThrow();
    }
  });

  it("invalidates H1 evidence when shared deadline or regex execution dependencies change", () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-execution-dependencies-"));
    workDir = root;
    initHermeticRepo(root);
    const dependencies = [
      "packages/keiko-workspace/src/structuralExecution.ts",
      "packages/keiko-workspace/src/repoSearchRegexSafety.ts",
    ];
    for (const path of new Set([...H1_OWNED_SOURCE_PATHS, ...dependencies])) {
      mkdirSync(dirname(join(root, path)), { recursive: true });
      writeFileSync(join(root, path), `// initial ${path}\n`);
    }
    git(root, ["add", "."]);
    git(root, ["commit", "-m", "H1 execution closure"]);
    const sourceDigest = ownedSourceDigestAt("HEAD", root, execFileSync);
    for (const path of dependencies) writeFileSync(join(root, path), "// changed runtime guard\n");
    git(root, ["add", "."]);
    git(root, ["commit", "-m", "change execution guards"]);
    expect(ownedSourceDigestAt("HEAD", root, execFileSync)).not.toBe(sourceDigest);
    expect(H1_OWNED_SOURCE_PATHS).toEqual(expect.arrayContaining(dependencies));
  });

  // Fails before the ownership-annex fix: changing the actual H1 request/authority handler left
  // the default owned-source digest unchanged because the historical 43-row migration census
  // named only four older integration helpers. The census remains immutable; the canonical pins
  // now carry a separate complete implementation annex used by this production digest helper.
  it("binds the default owned-source digest to the actual H1 handler implementation", () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-owned-handler-"));
    workDir = root;
    initHermeticRepo(root);
    const handlerPath = "packages/keiko-server/src/coding-runtime/codingRepositorySearchHandler.ts";
    for (const path of new Set([...H1_OWNED_SOURCE_PATHS, handlerPath])) {
      mkdirSync(dirname(join(root, path)), { recursive: true });
      writeFileSync(join(root, path), `// initial ${path}\n`);
    }
    git(root, ["add", "."]);
    git(root, ["commit", "-m", "H1 implementation"]);
    const sourceHead = git(root, ["rev-parse", "HEAD"]);
    const sourceDigest = ownedSourceDigestAt(sourceHead, root, execFileSync);
    writeFileSync(join(root, handlerPath), "// changed handler authority guard\n");
    git(root, ["add", handlerPath]);
    git(root, ["commit", "-m", "change H1 handler"]);
    const changedHead = git(root, ["rev-parse", "HEAD"]);
    expect(ownedSourceDigestAt(changedHead, root, execFileSync)).not.toBe(sourceDigest);
    expect(H1_OWNED_SOURCE_PATHS).toContain(handlerPath);
  });

  // Fails before the fix: the reviewer's exact repro (real dev tip, current producer projection,
  // a nonexistent 40-`f` sourceHead, a fabricated treeDigest repeated in both records) returned
  // `[]`. Uses checkH1HandoffEvidence's real, unstubbed `execute`/`sourceHeadFailures` defaults --
  // only `identityFailures` is stubbed, to isolate this from the unrelated producer-projection
  // dimension.
  it("reproduces the reviewed exploit (nonexistent sourceHead + fabricated repeated treeDigest) and now fails closed", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-exploit-"));
    workDir = root;
    initHermeticRepo(root);
    git(root, ["commit", "--allow-empty", "-m", "dev tip"]);
    const devTip = git(root, ["rev-parse", "HEAD"]);
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const forgedDigest = "1".repeat(64);
    const record = {
      ...VALID_RECORD,
      sourceHead: "f".repeat(40),
      currentHead: devTip,
      treeDigest: forgedDigest,
    };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: devTip, landedTreeDigest: forgedDigest },
      { identityFailures: async () => [] },
    );
    expect(errors).toEqual([
      `H1 handoff evidence unverifiable: sourceHead ${record.sourceHead} is not a resolvable Git commit`,
    ]);
  });

  it("passes a genuine H1 handoff end-to-end: sourceHead resolves and its owned-source digest matches at both sourceHead and the consuming commit", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-real-"));
    workDir = root;
    initHermeticRepo(root);
    const ownedPaths = ["owned/a.ts", "owned/b.ts"];
    mkdirSync(join(root, "owned"), { recursive: true });
    writeFileSync(join(root, "owned", "a.ts"), "export const a = 1;\n");
    writeFileSync(join(root, "owned", "b.ts"), "export const b = 2;\n");
    git(root, ["add", "."]);
    git(root, ["commit", "-m", "H1 producer commit"]);
    const sourceHead = git(root, ["rev-parse", "HEAD"]);
    // Real formula, derived from the exported production helper -- never restated (AGENTS.md §7).
    const treeDigest = ownedSourceDigestAt(sourceHead, root, execFileSync, ownedPaths);
    // The consuming commit lands on dev without touching the owned paths: a different commit,
    // identical owned-source content.
    writeFileSync(join(root, "unrelated.txt"), "noise\n");
    git(root, ["add", "unrelated.txt"]);
    git(root, ["commit", "-m", "unrelated dev change"]);
    const currentHead = git(root, ["rev-parse", "HEAD"]);
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD, sourceHead, currentHead, treeDigest };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: currentHead, landedTreeDigest: treeDigest },
      {
        identityFailures: async () => [],
        sourceHeadFailures: (r, rec, exec) => realSourceHeadFailures(r, rec, exec, ownedPaths),
      },
    );
    expect(errors).toEqual([]);
  });

  it("fails closed when the consuming commit's owned-source content diverges from the reviewed sourceHead", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-drift-"));
    workDir = root;
    initHermeticRepo(root);
    const ownedPaths = ["owned/a.ts"];
    mkdirSync(join(root, "owned"), { recursive: true });
    writeFileSync(join(root, "owned", "a.ts"), "export const a = 1;\n");
    git(root, ["add", "."]);
    git(root, ["commit", "-m", "H1 producer commit"]);
    const sourceHead = git(root, ["rev-parse", "HEAD"]);
    const treeDigest = ownedSourceDigestAt(sourceHead, root, execFileSync, ownedPaths);
    // The consuming commit silently swaps the owned file's content after review.
    writeFileSync(join(root, "owned", "a.ts"), "export const a = 999;\n");
    git(root, ["add", "owned/a.ts"]);
    git(root, ["commit", "-m", "swapped after review"]);
    const currentHead = git(root, ["rev-parse", "HEAD"]);
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD, sourceHead, currentHead, treeDigest };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: currentHead, landedTreeDigest: treeDigest },
      {
        identityFailures: async () => [],
        sourceHeadFailures: (r, rec, exec) => realSourceHeadFailures(r, rec, exec, ownedPaths),
      },
    );
    expect(errors).toEqual([
      "H1 handoff evidence identity mismatch: the consuming commit's owned source content does not match the reviewed treeDigest",
    ]);
  });

  it("fails closed when the declared treeDigest does not match the real owned source content at sourceHead", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-wrong-digest-"));
    workDir = root;
    initHermeticRepo(root);
    mkdirSync(join(root, "owned"), { recursive: true });
    writeFileSync(join(root, "owned", "a.ts"), "export const a = 1;\n");
    git(root, ["add", "."]);
    git(root, ["commit", "-m", "producer commit"]);
    const sourceHead = git(root, ["rev-parse", "HEAD"]);
    const errors = await realSourceHeadFailures(
      root,
      { sourceHead, currentHead: sourceHead, treeDigest: "0".repeat(64) },
      execFileSync,
      ["owned/a.ts"],
    );
    expect(errors).toEqual([
      "H1 handoff evidence identity mismatch: treeDigest does not match the real owned source content at sourceHead",
    ]);
  });

  it("fails closed when a declared H1-owned source path is missing at sourceHead", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-missing-"));
    workDir = root;
    initHermeticRepo(root);
    git(root, ["commit", "--allow-empty", "-m", "producer commit without the owned path"]);
    const sourceHead = git(root, ["rev-parse", "HEAD"]);
    const errors = await realSourceHeadFailures(
      root,
      { sourceHead, currentHead: sourceHead, treeDigest: "0".repeat(64) },
      execFileSync,
      ["owned/does-not-exist.ts"],
    );
    expect(errors).toEqual([
      `H1 handoff evidence unverifiable: an H1-owned source path is missing from sourceHead ${sourceHead}`,
    ]);
  });

  it("fails closed when sourceHead does not resolve to a real Git commit", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-nonexistent-"));
    workDir = root;
    initHermeticRepo(root);
    git(root, ["commit", "--allow-empty", "-m", "unrelated"]);
    const forgedSha = "f".repeat(40);
    const errors = await realSourceHeadFailures(
      root,
      { sourceHead: forgedSha, currentHead: forgedSha, treeDigest: "0".repeat(64) },
      execFileSync,
      [],
    );
    expect(errors).toEqual([
      `H1 handoff evidence unverifiable: sourceHead ${forgedSha} is not a resolvable Git commit`,
    ]);
  });

  it("fails closed when currentHead (the consuming commit) does not resolve to a real Git commit", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-current-nonexistent-"));
    workDir = root;
    initHermeticRepo(root);
    git(root, ["commit", "--allow-empty", "-m", "producer commit"]);
    const sourceHead = git(root, ["rev-parse", "HEAD"]);
    // Empty ownedPaths makes the digest a stable constant, letting this isolate the currentHead
    // resolution step alone using the real exported helper (never a restated formula).
    const emptyDigest = ownedSourceDigestAt(sourceHead, root, execFileSync, []);
    const forgedSha = "f".repeat(40);
    const errors = await realSourceHeadFailures(
      root,
      { sourceHead, currentHead: forgedSha, treeDigest: emptyDigest },
      execFileSync,
      [],
    );
    expect(errors).toEqual([
      `H1 handoff evidence unverifiable: currentHead ${forgedSha} is not a resolvable Git commit`,
    ]);
  });

  // The tests above use custom ownedPaths (a hermetic repo cannot host this repository's real
  // directory structure). This proves the REAL production default (H1_OWNED_SOURCE_PATHS, this
  // repository's actual owned files) computes a stable, well-formed digest against this
  // repository's own real Git history -- not just that the DI seam works.
  it("the real (unstubbed) owned-source digest agrees with itself against this repository's actual HEAD", () => {
    let headSha;
    try {
      headSha = git(ROOT, ["rev-parse", "HEAD"]);
    } catch {
      return;
    }
    const digest = ownedSourceDigestAt(headSha, ROOT, execFileSync);
    expect(digest).toMatch(/^[a-f0-9]{64}$/u);
    expect(ownedSourceDigestAt(headSha, ROOT, execFileSync)).toBe(digest);
  });
});
