import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  checkToolCatalogConformance,
  checkToolCatalogConformanceNegatives,
  generatedToolCatalogManifest,
  toolCatalogManifestBytes,
  TOOL_CATALOG_MANIFEST_PATH,
  TOOL_CATALOG_MIGRATION_PATH,
  toolCatalogMigrationBytes,
} from "../check-tool-catalog-conformance.mjs";
import { scanToolRegistrySource } from "../lib/tool-catalog-inventory.mjs";
import {
  measureToolCatalogPerformance,
  validateToolCatalogPerformanceSamples,
} from "../check-tool-catalog-performance.mjs";

const ROOT = process.cwd();
const PROBE = "packages/keiko-server/src/gateway-tool-calling-probe.ts";
describe("initial compiler and finite migration conformance gate", () => {
  it("checks the actual producer, legacy owner, generated bytes and finite inventory", async () => {
    expect(await checkToolCatalogConformance(ROOT)).toEqual([]);
    expect(checkToolCatalogConformanceNegatives()).toEqual([]);
    expect(await toolCatalogManifestBytes(ROOT)).toBe(await toolCatalogManifestBytes(ROOT));
    expect(readFileSync(join(ROOT, TOOL_CATALOG_MIGRATION_PATH), "utf8")).toBe(
      await toolCatalogMigrationBytes(ROOT),
    );
    const migration = JSON.parse(await toolCatalogMigrationBytes(ROOT));
    expect(migration.inventory).toHaveLength(43);
    expect(migration.nonDispatchProbes).toHaveLength(1);
    expect(
      migration.inventory.some((entry) => entry.id === migration.nonDispatchProbes[0].id),
    ).toBe(false);
    expect(JSON.parse(readFileSync(join(ROOT, TOOL_CATALOG_MANIFEST_PATH), "utf8"))).toEqual(
      await generatedToolCatalogManifest(ROOT),
    );
  });
  it("pins the one non-dispatch readiness probe without granting a path exception", () => {
    const source = readFileSync(join(ROOT, PROBE), "utf8");
    expect(scanToolRegistrySource(PROBE, source, new Set())).toEqual([]);
    for (const mutation of [
      source.replaceAll("report_readiness", "read_file"),
      source.replace('enum: ["ok"]', 'enum: ["ok", "write"]'),
      source.replace("additionalProperties: false", "additionalProperties: true"),
      source.replaceAll("toolCallingBody", "workspaceToolBody"),
      source + '\nconst tool = {name: "keiko_repo_search", parameters: {}};',
    ])
      expect(scanToolRegistrySource(PROBE, mutation, new Set()).length).toBeGreaterThan(0);
    expect(
      scanToolRegistrySource("packages/keiko-server/src/copied-probe.ts", source, new Set()).length,
    ).toBeGreaterThan(0);
  });
  it("accepts projection consumers and text samples, but rejects concrete schema and ID rows", () => {
    const file = "packages/keiko-server/src/new-consumer.ts";
    expect(
      scanToolRegistrySource(
        file,
        'const tools = gatewayToolDefinitions(catalog, profile); const sample = "name: read_file, parameters: {}";',
        new Set(),
      ),
    ).toEqual([]);
    for (const source of [
      'const tools = [{name: "new_alias", parameters: {}}];',
      'const tools = [{"name": "new_alias", inputSchema: {}}];',
      'const ref = {canonicalId: "keiko.repo.search", contractVersion: 1};',
    ])
      expect(scanToolRegistrySource(file, source, new Set()).length).toBeGreaterThan(0);
    expect(
      scanToolRegistrySource(
        file,
        'const tool = {name: "new_alias", parameters: {}};',
        new Set([file]),
      ),
    ).toEqual([]);
  });
});
describe("compiler measurements reuse the existing sample and percentile convention", () => {
  it("measures real fixture work with a deterministic clock and rejects incomplete work", async () => {
    let now = 0;
    const evidence = await measureToolCatalogPerformance(ROOT, () => ++now);
    expect(evidence.samples).toHaveLength(30);
    expect(evidence.aggregates.coldCompileMs).toEqual({ minimum: 1, maximum: 1, p50: 1, p95: 1 });
    expect(validateToolCatalogPerformanceSamples(evidence.samples)).toEqual([]);
    expect(validateToolCatalogPerformanceSamples([]).length).toBeGreaterThan(0);
    for (const change of [
      { coldCompileMs: NaN },
      { lookupBatchMs: 0 },
      { toolCount: 0 },
      { lookups: 0 },
      { projectionDigest: "bad" },
    ]) {
      const samples = structuredClone(evidence.samples);
      samples[0] = { ...samples[0], ...change };
      expect(validateToolCatalogPerformanceSamples(samples).length).toBeGreaterThan(0);
    }
  });
});
