import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import {
  checkToolCatalogConformance,
  checkToolCatalogConformanceNegatives,
  checkToolCatalogMigrationCloseout,
  checkToolCatalogSemanticNegatives,
  checkH1HandoffEvidence,
  h1ProvenanceShapeFailures,
  H1_PROVENANCE_PATH,
  activeToolCatalogMigrations,
  retiredBridgeMigrations,
  generatedToolCatalogManifest,
  legacyProjectionDiffers,
  loadToolCatalogProducer,
  toolCatalogManifestBytes,
  TOOL_CATALOG_MANIFEST_PATH,
  TOOL_CATALOG_MIGRATION_PATH,
  toolCatalogMigrationBytes,
} from "../check-tool-catalog-conformance.mjs";
import { scanToolRegistrySource } from "../lib/tool-catalog-inventory.mjs";
import {
  buildSyntheticRegistrationSet,
  deriveLookupIterations,
  measureToolCatalogOverflowRejection,
  measureToolCatalogPerformance,
  TOOL_CATALOG_OVERFLOW_TOOL_COUNT,
  TOOL_CATALOG_SYNTHETIC_TOOL_COUNT,
  validateToolCatalogPerformanceSamples,
} from "../check-tool-catalog-performance.mjs";
import * as sharedNegativeFixture from "../../tests/architecture/fixtures/tool-catalog-negatives/_shared.mjs";

const ROOT = process.cwd();
const PROBE = "packages/keiko-server/src/gateway-tool-calling-probe.ts";
const NEGATIVE_FIXTURES_DIR = "tests/architecture/fixtures/tool-catalog-negatives";
describe("initial compiler and finite migration conformance gate", () => {
  it("checks the actual producer, legacy owner, generated bytes and finite inventory", async () => {
    expect(await checkToolCatalogConformance(ROOT)).toEqual([]);
    expect(checkToolCatalogConformanceNegatives()).toEqual([]);
    expect(await toolCatalogManifestBytes(ROOT)).toBe(await toolCatalogManifestBytes(ROOT));
    expect(readFileSync(join(ROOT, TOOL_CATALOG_MIGRATION_PATH), "utf8")).toBe(
      await toolCatalogMigrationBytes(ROOT),
    );
    const migration = JSON.parse(await toolCatalogMigrationBytes(ROOT));
    expect(migration.inventory).toEqual([]);
    expect(migration.historicalInventory).toEqual({
      rowCount: 43,
      digest: expect.stringMatching(/^[a-f0-9]{64}$/u),
    });
    expect(migration.nonDispatchProbes).toHaveLength(1);
    expect(
      migration.inventory.some((entry) => entry.id === migration.nonDispatchProbes[0].id),
    ).toBe(false);
    expect(JSON.parse(readFileSync(join(ROOT, TOOL_CATALOG_MANIFEST_PATH), "utf8"))).toEqual(
      await generatedToolCatalogManifest(ROOT),
    );
  });

  // #3406/#3414 (F6): the non-authorizing pending-H1 handoff record for #3386's H1 local
  // repository-search handler. Fails-before: prior to this record's addition, the generated
  // migration document carried no `pendingH1` field at all, so #3406's acceptance criterion
  // (owner, canonical tool reference, prerequisite #3411 merge identity, removal issue #3414,
  // initially-empty landedDevCommit/landedTreeDigest) existed only as prose in
  // governed-tool-migration.md, never as an actual record.
  it("carries the non-authorizing pending-H1 handoff record with exactly its six fields", async () => {
    const migration = JSON.parse(await toolCatalogMigrationBytes(ROOT));
    expect(Object.keys(migration.pendingH1).sort()).toEqual(
      [
        "owner",
        "canonicalTool",
        "prerequisiteMerge",
        "removalIssue",
        "landedDevCommit",
        "landedTreeDigest",
      ].sort(),
    );
    expect(migration.pendingH1.owner).toBe(3386);
    expect(migration.pendingH1.canonicalTool).toEqual({
      canonicalId: "keiko.repo.search",
      contractVersion: 1,
    });
    expect(migration.pendingH1.prerequisiteMerge.issue).toBe(3411);
    expect(migration.pendingH1.prerequisiteMerge.contractDigest).toBe(
      migration.sourceContractDigest,
    );
    expect(migration.pendingH1.removalIssue).toBe(3414);
    // Initially empty: no code path may treat this record as an authorization while these are
    // null -- only #3414 may populate them once H1 actually reaches dev.
    expect(migration.pendingH1.landedDevCommit).toBeNull();
    expect(migration.pendingH1.landedTreeDigest).toBeNull();
  });
  it("pins the one non-dispatch readiness probe without granting a path exception", () => {
    const source = readFileSync(join(ROOT, PROBE), "utf8");
    expect(scanToolRegistrySource(PROBE, source, new Set())).toEqual([]);
    for (const mutation of [
      source.replaceAll("report_readiness", "read_file"),
      source.replace('enum: ["ok"]', 'enum: ["ok", "write"]'),
      source.replace("additionalProperties: false", "additionalProperties: true"),
      source.replaceAll("toolCallingBody", "workspaceToolBody"),
      source + '\nconst tool = {name: "keiko_repo_search", parameters: {}};',
    ])
      expect(scanToolRegistrySource(PROBE, mutation, new Set()).length).toBeGreaterThan(0);
    expect(
      scanToolRegistrySource("packages/keiko-server/src/copied-probe.ts", source, new Set()).length,
    ).toBeGreaterThan(0);
  });
  it("accepts projection consumers and text samples, but rejects concrete schema and ID rows", () => {
    const file = "packages/keiko-server/src/new-consumer.ts";
    expect(
      scanToolRegistrySource(
        file,
        'const tools = gatewayToolDefinitions(catalog, profile); const sample = "name: read_file, parameters: {}";',
        new Set(),
      ),
    ).toEqual([]);
    for (const source of [
      'const tools = [{name: "new_alias", parameters: {}}];',
      'const tools = [{"name": "new_alias", inputSchema: {}}];',
      'const ref = {canonicalId: "keiko.repo.search", contractVersion: 1};',
    ])
      expect(scanToolRegistrySource(file, source, new Set()).length).toBeGreaterThan(0);
    expect(
      scanToolRegistrySource(
        file,
        'const tool = {name: "new_alias", parameters: {}};',
        new Set([file]),
      ),
    ).toEqual([]);
  });
});
describe("closeout enforcement", () => {
  it("passes only after the source-derived active migration inventory reaches zero", async () => {
    const migration = JSON.parse(await toolCatalogMigrationBytes(ROOT));
    expect(activeToolCatalogMigrations(ROOT)).toEqual([]);
    expect(migration.inventory).toEqual([]);
    expect(await checkToolCatalogMigrationCloseout(ROOT)).toEqual([]);
  });
  it.each([
    [
      "packages/keiko-contracts/src/gateway.ts",
      "readonly tools?: readonly ToolDefinition[]",
      "generic-gateway",
    ],
    [
      "packages/keiko-contracts/src/governed-tool-bridge.ts",
      "LegacyNamedToolInvocation",
      "generic-tool-port",
    ],
    [
      "packages/keiko-tool-catalog/src/invocation.ts",
      'value.kind === "legacy-name"',
      "generic-tool-port",
    ],
    ["packages/keiko-model-gateway/src/toolCatalogBridge.ts", "legacySession", "generic-gateway"],
    [
      "packages/keiko-model-gateway/src/realtime-voice-adapter.ts",
      "RealtimeSessionTool",
      "realtime-compatibility",
    ],
  ])("restores migration %s when retired bridge source %s returns", (path, probe, id) => {
    expect(retiredBridgeMigrations({ [path]: probe })).toEqual([id]);
  });
});
describe("compiler measurements reuse the existing sample and percentile convention", () => {
  it("measures real fixture work per case with a deterministic clock and rejects incomplete work", async () => {
    let now = 0;
    const evidence = await measureToolCatalogPerformance(ROOT, () => ++now);
    expect(Object.keys(evidence.cases)).toEqual([
      "legacy-native-6-tool",
      `synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool`,
    ]);
    expect(evidence.overflow).toEqual({
      attemptedToolCount: TOOL_CATALOG_OVERFLOW_TOOL_COUNT,
      rejected: true,
      reason: "input-bound",
    });
    for (const testCase of Object.values(evidence.cases)) {
      expect(testCase.samples).toHaveLength(30);
      expect(testCase.aggregates.coldCompileMs).toEqual({
        minimum: 1,
        maximum: 1,
        p50: 1,
        p95: 1,
      });
      expect(validateToolCatalogPerformanceSamples(testCase.samples)).toEqual([]);
    }
    // Never a hardcoded "6": the legacy case's expected tool count is read back from its own
    // first sample, and the synthetic case is a completely different, much larger count.
    const legacyCase = evidence.cases["legacy-native-6-tool"];
    const syntheticCase =
      evidence.cases[`synthetic-${String(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT)}-tool`];
    expect(legacyCase.toolCount).toBe(6);
    expect(syntheticCase.toolCount).toBe(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT);
    expect(syntheticCase.toolCount).toBeGreaterThan(legacyCase.toolCount * 10);
    expect(validateToolCatalogPerformanceSamples([])).not.toEqual([]);
    for (const change of [
      { coldCompileMs: NaN },
      { lookupBatchMs: 0 },
      { toolCount: 0 },
      { toolCount: legacyCase.samples[0].toolCount + 1 },
      { lookups: 0 },
      { projectionDigest: "bad" },
    ]) {
      const samples = structuredClone(legacyCase.samples);
      samples[0] = { ...samples[0], ...change };
      expect(validateToolCatalogPerformanceSamples(samples).length).toBeGreaterThan(0);
    }
  });
  it("derives lookup iteration counts from a fixed operation budget, never a wall-clock duration", () => {
    expect(deriveLookupIterations(6)).toBeGreaterThan(
      deriveLookupIterations(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT),
    );
    expect(deriveLookupIterations(6) * 6).toBeLessThanOrEqual(6_000 + 6);
    expect(deriveLookupIterations(1_000_000)).toBe(1);
  });
  it("proves bounded construction: the largest synthetic catalog compiles, one past it is rejected closed", async () => {
    const producer = await loadToolCatalogProducer(ROOT);
    const catalog = producer.createKeikoToolCatalog([
      buildSyntheticRegistrationSet(producer, TOOL_CATALOG_SYNTHETIC_TOOL_COUNT),
    ]);
    expect(catalog.descriptors).toHaveLength(TOOL_CATALOG_SYNTHETIC_TOOL_COUNT);
    // Fails-before: without the overflow guard, a caller could construct an unbounded catalog
    // (or the byte-budget check could silently regress) with nothing proving the ceiling holds.
    expect(measureToolCatalogOverflowRejection(producer)).toEqual({
      attemptedToolCount: TOOL_CATALOG_OVERFLOW_TOOL_COUNT,
      rejected: true,
      reason: "input-bound",
    });
  });
});
describe("#3415 catalog-semantic negative-fixture matrix", () => {
  const fixtureFiles = readdirSync(join(ROOT, NEGATIVE_FIXTURES_DIR)).filter(
    (name) => name !== "_shared.mjs",
  );
  it("covers one fixture file per attack class named by issue #3415 AC2", () => {
    expect(fixtureFiles.sort()).toEqual(
      [
        "alias-collision-or-confusable.mjs",
        "duplicate-handler.mjs",
        "implicit-latest-resolution.mjs",
        "legacy-table-reintroduction.mjs",
        "missing-handler.mjs",
        "orphan-handler.mjs",
        "policy-effect-mismatch.mjs",
        "projection-drift.mjs",
        "stale-downgraded-compatibility.mjs",
        "version-mismatched-handler.mjs",
      ].sort(),
    );
  });
  it("is not reachable from any production source root", () => {
    // The AST inventory scanner only walks packages/*/src and src/; this asserts the stronger,
    // literal claim that no such file contains the fixture directory's specifier at all.
    const needle = "tool-catalog-negatives";
    const productionRoots = [
      join(ROOT, "src"),
      ...readdirSync(join(ROOT, "packages"), { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => join(ROOT, "packages", entry.name, "src")),
    ];
    const offenders = [];
    for (const directory of productionRoots) {
      let entries;
      try {
        entries = readdirSync(directory, { withFileTypes: true, recursive: true });
      } catch {
        continue;
      }
      for (const entry of entries) {
        if (!entry.isFile() || !/\.[cm]?[jt]sx?$/u.test(entry.name)) continue;
        const filePath = join(entry.parentPath ?? directory, entry.name);
        if (readFileSync(filePath, "utf8").includes(needle)) offenders.push(filePath);
      }
    }
    expect(offenders).toEqual([]);
  });
  it("rejects every fixture with the real producer's own failure reason, one class at a time", async () => {
    const producer = await loadToolCatalogProducer(ROOT);
    const fixture = (name) => import(pathToFileURL(join(ROOT, NEGATIVE_FIXTURES_DIR, name)).href);

    const missingHandler = await fixture("missing-handler.mjs");
    expect(sharedNegativeFixture.expectRejection(() => missingHandler.attempt(producer))).toEqual({
      rejected: true,
      reason: missingHandler.EXPECTED_REASON,
    });

    const orphanHandler = await fixture("orphan-handler.mjs");
    expect(sharedNegativeFixture.expectRejection(() => orphanHandler.attempt(producer))).toEqual({
      rejected: true,
      reason: orphanHandler.EXPECTED_REASON,
    });

    const duplicateHandler = await fixture("duplicate-handler.mjs");
    expect(sharedNegativeFixture.expectRejection(() => duplicateHandler.attempt(producer))).toEqual(
      { rejected: true, reason: duplicateHandler.EXPECTED_REASON },
    );

    const versionMismatched = await fixture("version-mismatched-handler.mjs");
    expect(
      sharedNegativeFixture.expectRejection(() => versionMismatched.attempt(producer)),
    ).toEqual({ rejected: true, reason: versionMismatched.EXPECTED_REASON });

    const alias = await fixture("alias-collision-or-confusable.mjs");
    expect(sharedNegativeFixture.expectRejection(() => alias.attemptCollision(producer))).toEqual({
      rejected: true,
      reason: alias.EXPECTED_REASONS.collision,
    });
    expect(sharedNegativeFixture.expectRejection(() => alias.attemptConfusable(producer))).toEqual({
      rejected: true,
      reason: alias.EXPECTED_REASONS.confusable,
    });

    const drift = await fixture("projection-drift.mjs");
    expect(sharedNegativeFixture.expectRejection(() => drift.attempt(producer))).toEqual({
      rejected: true,
      reason: drift.EXPECTED_REASON,
    });

    const policyEffect = await fixture("policy-effect-mismatch.mjs");
    expect(sharedNegativeFixture.expectRejection(() => policyEffect.attempt(producer))).toEqual({
      rejected: true,
      reason: policyEffect.EXPECTED_REASON,
    });

    const compatibility = await fixture("stale-downgraded-compatibility.mjs");
    expect(
      sharedNegativeFixture.expectRejection(() => compatibility.attemptStale(producer)),
    ).toEqual({ rejected: true, reason: compatibility.EXPECTED_REASONS.stale });
    expect(
      sharedNegativeFixture.expectRejection(() => compatibility.attemptDowngraded(producer)),
    ).toEqual({ rejected: true, reason: compatibility.EXPECTED_REASONS.downgraded });

    const implicitLatest = await fixture("implicit-latest-resolution.mjs");
    expect(
      sharedNegativeFixture.expectRejection(() =>
        implicitLatest.attemptOmittedContractVersion(producer),
      ),
    ).toEqual({ rejected: true, reason: implicitLatest.EXPECTED_REASON });
    expect(
      sharedNegativeFixture.expectRejection(() => implicitLatest.attemptLatestLiteral(producer)),
    ).toEqual({ rejected: true, reason: implicitLatest.EXPECTED_REASON });

    const legacyTable = await fixture("legacy-table-reintroduction.mjs");
    const legacyResult = await legacyTable.attempt(producer, ROOT, legacyProjectionDiffers);
    expect(sharedNegativeFixture.expectRejection(() => legacyResult)).toEqual({
      rejected: true,
      reason: legacyTable.EXPECTED_REASON,
    });
    // The comparator must actually distinguish drift from no-drift, not just always report true.
    const catalog = producer.createInitialToolCatalog();
    const realDefinitions = producer.gatewayToolDefinitions(catalog, {
      id: "legacy-native",
      version: 1,
    });
    const legacy = await import(
      pathToFileURL(join(ROOT, "packages/keiko-tools/dist/schemas.js")).href
    );
    expect(legacyProjectionDiffers(realDefinitions, legacy.TOOL_DEFINITIONS)).toBe(false);
  });
  it("wires every fixture into the packaged gate via checkToolCatalogSemanticNegatives", async () => {
    // Fails-before: before this function existed, none of the above fixtures were exercised by
    // `npm run check:tool-catalog-conformance` or `npm run arch:check:negative` at all.
    expect(await checkToolCatalogSemanticNegatives(ROOT)).toEqual([]);
  });
});

describe("#3414 AC7 / #3415 AC5-AC6: H1 dev-handoff evidence recheck", () => {
  const VALID_RECORD = Object.freeze({
    schemaVersion: 1,
    integrationPr: 3394,
    sourceHead: "a".repeat(40),
    treeDigest: "b".repeat(64),
    verificationRef: "https://example.invalid/verification",
    reviewRef: "https://example.invalid/review",
    catalogRevision: "revision-1",
    profile: { id: "legacy-native", version: 1 },
    projectionDigest: "c".repeat(64),
    handlerSetDigest: "d".repeat(64),
    currentHead: "e".repeat(40),
  });
  let workDir;
  afterEach(() => {
    if (workDir !== undefined) rmSync(workDir, { recursive: true, force: true });
    workDir = undefined;
  });
  it.each([
    { integrationPr: 0 },
    { sourceHead: "not-hex" },
    { currentHead: "short" },
    { treeDigest: "not-hex" },
    { projectionDigest: "too-short" },
    { handlerSetDigest: "not-hex" },
    { profile: { id: "legacy-native" } },
    { profile: "legacy-native" },
    { catalogRevision: "" },
    { verificationRef: "" },
    { reviewRef: "" },
  ])("rejects a malformed durable record %j", (patch) => {
    expect(h1ProvenanceShapeFailures({ ...VALID_RECORD, ...patch }).length).toBeGreaterThan(0);
  });
  it("rejects a record missing or adding a field beyond the exact H1Provenance shape", () => {
    const { schemaVersion: _schemaVersion, ...withoutSchemaVersion } = VALID_RECORD;
    expect(h1ProvenanceShapeFailures(withoutSchemaVersion)).toEqual([
      "H1 handoff evidence malformed: durable record does not carry exactly the H1Provenance fields",
    ]);
    expect(
      h1ProvenanceShapeFailures({ ...VALID_RECORD, extraField: "x" }),
    ).toEqual([
      "H1 handoff evidence malformed: durable record does not carry exactly the H1Provenance fields",
    ]);
  });
  it("accepts a fully well-formed durable record", () => {
    expect(h1ProvenanceShapeFailures(VALID_RECORD)).toEqual([]);
  });
  it("passes while H1 has not landed to dev (both fields honestly null)", async () => {
    expect(
      await checkH1HandoffEvidence(ROOT, { landedDevCommit: null, landedTreeDigest: null }),
    ).toEqual([]);
  });
  it("fails closed on a partially populated pending record", async () => {
    expect(
      await checkH1HandoffEvidence(ROOT, {
        landedDevCommit: "a".repeat(40),
        landedTreeDigest: null,
      }),
    ).toEqual([
      "H1 handoff evidence partially populated: landedDevCommit and landedTreeDigest must be set together",
    ]);
  });
  it("fails closed on a malformed landedDevCommit/landedTreeDigest shape", async () => {
    expect(
      await checkH1HandoffEvidence(ROOT, {
        landedDevCommit: "not-a-sha",
        landedTreeDigest: "b".repeat(64),
      }),
    ).toEqual([
      "H1 handoff evidence malformed: pendingH1.landedDevCommit is not a 40-hex commit SHA",
    ]);
    expect(
      await checkH1HandoffEvidence(ROOT, {
        landedDevCommit: "a".repeat(40),
        landedTreeDigest: "not-a-digest",
      }),
    ).toEqual([
      "H1 handoff evidence malformed: pendingH1.landedTreeDigest is not a 64-hex digest",
    ]);
  });
  it("fails closed when no durable H1Provenance record exists", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    const errors = await checkH1HandoffEvidence(root, {
      landedDevCommit: "a".repeat(40),
      landedTreeDigest: "b".repeat(64),
    });
    expect(errors).toEqual([`H1 handoff evidence missing: no ${H1_PROVENANCE_PATH}`]);
  });
  it("fails closed when the durable record exists but is malformed JSON", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    writeFileSync(join(root, H1_PROVENANCE_PATH), "{not json");
    expect(
      await checkH1HandoffEvidence(root, {
        landedDevCommit: "a".repeat(40),
        landedTreeDigest: "b".repeat(64),
      }),
    ).toEqual(["H1 handoff evidence malformed: not valid JSON"]);
  });
  it("fails closed on a stale record (treeDigest/currentHead do not match pendingH1)", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(VALID_RECORD));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: "f".repeat(40), landedTreeDigest: "b".repeat(64) },
      { execute: () => "", identityFailures: async () => [] },
    );
    expect(errors).toContain(
      "H1 handoff evidence stale: durable record's currentHead does not match pendingH1.landedDevCommit",
    );
  });
  it("fails closed when landedDevCommit is not reachable from dev", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD, currentHead: VALID_RECORD.currentHead };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: record.currentHead, landedTreeDigest: record.treeDigest },
      {
        execute: () => {
          throw new Error("not an ancestor");
        },
        identityFailures: async () => [],
      },
    );
    expect(errors).toEqual([
      `H1 handoff evidence unreachable: landedDevCommit ${record.currentHead} is not an ancestor of dev`,
    ]);
  });
  it("passes when the durable record is fresh, reachable, and identity-agreeing", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: record.currentHead, landedTreeDigest: record.treeDigest },
      { execute: () => "", identityFailures: async () => [] },
    );
    expect(errors).toEqual([]);
  });
  it("fails closed on an identity mismatch against the current producer", async () => {
    const root = mkdtempSync(join(tmpdir(), "keiko-h1-evidence-"));
    workDir = root;
    mkdirSync(join(root, "docs", "architecture"), { recursive: true });
    const record = { ...VALID_RECORD };
    writeFileSync(join(root, H1_PROVENANCE_PATH), JSON.stringify(record));
    const errors = await checkH1HandoffEvidence(
      root,
      { landedDevCommit: record.currentHead, landedTreeDigest: record.treeDigest },
      {
        execute: () => "",
        identityFailures: async () => ["H1 handoff evidence identity mismatch: catalogRevision does not match the current producer"],
      },
    );
    expect(errors).toEqual([
      "H1 handoff evidence identity mismatch: catalogRevision does not match the current producer",
    ]);
  });
  it("checkToolCatalogMigrationCloseout stays green on the real repo (H1 not yet landed)", async () => {
    expect(await checkToolCatalogMigrationCloseout(ROOT)).toEqual([]);
  });
});
