// Public Activity Log surface. Keep this list explicit: the store modules also contain raw
// filesystem mutation primitives, and the writer module contains an in-memory test sink. Neither
// belongs in the packaged entry point where it could bypass process writer ownership or become a
// compatibility promise.

export {
  activityLogLossSummaryEvent,
  persistActivityLogLossSummary,
  type ActivityLogLossSummaryOptions,
  type ActivityLogLossSummaryOutcome,
  type ActivityLogLossSummaryTrigger,
} from "./activity-log-loss-summary.js";
export {
  persistActivityLogEvents,
  type ActivityLogEventPersister,
} from "./activity-log-persistence.js";
export {
  checkActivityLogReadiness,
  currentActivityLogReadiness,
  refreshActivityLogReadiness,
  type ActivityLogReadinessOptions,
  type ActivityLogReadinessScope,
  type ActivityLogStorageHealthProvider,
} from "./activity-log-readiness.js";
export {
  contentFreeErrorClass,
  declaredErrorClassName,
  machineToken,
  safeProperty,
  DECLARED_ERROR_CLASS_SHAPE,
  MACHINE_TOKEN_SHAPE,
  SPECIFIC_BUILT_IN_ERROR_NAMES,
} from "./error-classification.js";
export {
  configureActivityLogRouteRedactor,
  type ActivityLogRouteRedactor,
} from "./log-redaction.js";
export {
  configuredRuntimeStateDir,
  resolveRuntimeStateDir,
  DEFAULT_RUNTIME_STATE_DIR_NAME,
  type RuntimeStateDirEnv,
} from "./runtime-state-dir.js";
export {
  activityLogStorageHealth,
  appendDurableServerLogBatch,
  closeFileServerLogSinks,
  closeReasonVocabulary,
  createFileServerLogSink,
  errorKindOf,
  formatRegisteredServerLogLine,
  formatServerLogLine,
  isDeniedLogFieldName,
  isServerLogLevel,
  isServerLogThreshold,
  listActivityLogFiles,
  normalizeLogFieldName,
  nullServerLogSink,
  parseServerLogThreshold,
  pinActivityLogWindow,
  redactLogFields,
  redactLogLabel,
  redactLogString,
  releaseActivityLogPin,
  reportServerLogFailure,
  resolveActivityLogStorageConfig,
  resolveServerLogThreshold,
  serverLogInstanceId,
  serverLogLevelEnabled,
  serverLogLevelRank,
  serverLogLineBytes,
  serverLogLineWithinCap,
  serverLogProcessIdentity,
  ACTIVITY_LOG_PIN_QUOTA_BYTES_ENV,
  ACTIVITY_LOG_RETENTION_BYTES_ENV,
  ACTIVITY_LOG_RETENTION_DAYS_ENV,
  ACTIVITY_LOG_SEGMENT_BYTES_ENV,
  ACTIVITY_LOG_SEGMENT_SECONDS_ENV,
  ACTIVITY_LOG_STORAGE_OPERATIONS,
  DEFAULT_ACTIVITY_LOG_PIN_QUOTA_BYTES,
  DEFAULT_ACTIVITY_LOG_RETENTION_BYTES,
  DEFAULT_ACTIVITY_LOG_RETENTION_DAYS,
  DEFAULT_ACTIVITY_LOG_SEGMENT_BYTES,
  DEFAULT_ACTIVITY_LOG_SEGMENT_SECONDS,
  DEFAULT_SERVER_LOG_LEVEL,
  DROPPED_DEPTH,
  DROPPED_LENGTH,
  LOG_FAILURE_NOTICE_WINDOW_MS,
  MAX_ACTIVITY_LOG_PINS,
  MAX_ACTIVITY_LOG_PIN_DURATION_MS,
  MAX_ACTIVITY_LOG_PIN_SEGMENTS,
  MAX_ACTIVITY_LOG_PIN_WINDOW_MS,
  MAX_LOG_ARRAY_LENGTH,
  MAX_LOG_FIELD_COUNT,
  MAX_LOG_FIELD_DEPTH,
  MAX_LOG_LINE_BYTES,
  MAX_LOG_STRING_LENGTH,
  MIN_ACTIVITY_LOG_RETENTION_BYTES,
  MIN_ACTIVITY_LOG_SEGMENT_BYTES,
  REDACTED_KEY,
  REDACTED_LENGTH,
  REDACTED_PATH,
  REDACTED_PERSONAL,
  REDACTED_SECRET,
  REDACTED_SHAPE,
  SERVER_LOG_LEVELS,
  SERVER_LOG_LEVEL_ENV,
  SERVER_LOG_SCHEMA_VERSION,
  ActivityLogWriterOwnershipError,
  type ActivityLogFileInfo,
  type ActivityLogPinReason,
  type ActivityLogPinReleaseRequest,
  type ActivityLogPinReleaseResult,
  type ActivityLogPinRejection,
  type ActivityLogPinRequest,
  type ActivityLogPinResult,
  type ActivityLogPinScope,
  type ActivityLogPressureSeverity,
  type ActivityLogPressureState,
  type ActivityLogStorageConfig,
  type ActivityLogStoreHealth,
  type DurableServerLogBatchInspection,
  type DurableServerLogBatchOptions,
  type DurableServerLogBatchResult,
  type FileServerLogSinkOptions,
  type ServerLogCategory,
  type ServerLogEnv,
  type ServerLogEvent,
  type ServerLogFailureContext,
  type ServerLogIdentity,
  type ServerLogLevel,
  type ServerLogSink,
  type ServerLogThreshold,
} from "./server-log.js";
export {
  activityLogWriterState,
  createActivityLogSink,
  createServerLogger,
  getServerLogger,
  isMandatoryActivityLogEvent,
  nullServerLogger,
  resolveActivityLogStateDir,
  setServerLogger,
  shutdownServerLogging,
  startLogTimer,
  type ActivityLogSinkOptions,
  type ActivityLogWriterState,
  type ServerLogContext,
  type ServerLogEventInput,
  type ServerLogEventSource,
  type ServerLogger,
  type ServerLoggerOptions,
} from "./server-logger.js";
export {
  causeChain,
  keikoStackFrames,
  FRAME_SHAPE_PATTERN,
  PACKAGE_DIR_NAMES,
} from "./stack-frames.js";
export {
  computeDefectFingerprint,
  dismissSupportIncident,
  listSupportIncidents,
  readSupportIncident,
  recordRegisteredFailureIncident,
  recordUserReportedIncident,
  supportIncidentEligibleOperation,
  supportIncidentSegmentFiles,
  MAX_REGISTERED_FAILURE_INCIDENTS,
  MAX_SUPPORT_INCIDENTS,
  MAX_SUPPORT_INCIDENT_EVALUATIONS_PER_MINUTE,
  SUPPORT_INCIDENT_IN_FLIGHT_GRACE_MS,
  SUPPORT_INCIDENT_OPERATIONS,
  SUPPORT_INCIDENT_SUPPRESSION_MS,
  SUPPORT_INCIDENT_TTL_MS,
  SUPPORT_INCIDENT_WINDOW_AFTER_MS,
  SUPPORT_INCIDENT_WINDOW_BEFORE_MS,
  type SupportIncidentCreation,
  type SupportIncidentDismissal,
  type SupportIncidentFailureEvidence,
  type SupportIncidentOptions,
  type SupportIncidentPinRelease,
  type SupportIncidentRejection,
  type SupportIncidentSegmentFile,
} from "./support-incident.js";
