/**
 * Parses an uploaded `keiko.config.json` into the gateway-setup form fields (owner-directed,
 * 0.3.0-beta.2): teams that already maintain a model-gateway configuration file load it instead of
 * retyping every field. The parser is fail-closed — any structural violation, connection-scalar
 * conflict, or provider kind this form cannot represent refuses the whole file rather than
 * applying a distorted half of it — and it runs entirely in the browser: the file is never
 * uploaded anywhere, and the parsed values flow into the exact same form state and validation
 * path as manual entry.
 *
 * Voice providers (`kind: "voice"`) map onto the dedicated voice setup fields: the file this
 * feature exists for is a persisted product configuration, and its voice endpoint details
 * (endpoint style, API version, voice profiles) are regenerated by the voice setup route itself,
 * so only the connection scalars and role model ids need to travel through the form.
 */

export const MAX_GATEWAY_CONFIG_BYTES = 256 * 1024;

/** Mirrors the setup route's MAX_DEPLOYMENT_NAMES so an oversized file fails here, not at Test & Save. */
const MAX_IMPORT_PROVIDERS = 100;
/** Mirrors the setup route's model-id bound so an unusable id fails here, not at Test & Save. */
const MAX_IMPORT_MODEL_ID_LENGTH = 160;
/**
 * Generic provider settings the setup form has no field for — importing a chat or embedding
 * provider that carries one would silently change runtime behavior (review finding on #3031).
 * Voice providers are exempt: the voice setup route regenerates their endpoint details itself.
 * Retry tuning (maxRetries, retryBaseDelayMs) stays tolerated everywhere: the form has no field
 * for it either, but it does not change which endpoint or protocol the connection speaks.
 */
const UNSUPPORTED_GENERIC_PROVIDER_SETTINGS = [
  "endpointStyle",
  "apiVersion",
  "outputTokenParameter",
  "realtimeAuthMode",
  "voiceProfiles",
] as const;
const KNOWN_KINDS = new Set(["chat", "embedding", "ocr-vision", "voice"]);
/** The provider kinds SOME setup field can represent; `ocr-vision` has none. */
const REPRESENTABLE_KINDS = new Set(["chat", "embedding", "voice"]);
const CAPABILITY_FLAG_KEYS = [
  "supportsImageInput",
  "workflowEligible",
  "supportsSpeechInput",
  "supportsSpeechOutput",
  "supportsRealtimeVoice",
  "supportsSemanticTurnDetection",
] as const;

export interface GatewayConfigUploadFields {
  readonly baseUrl: string | undefined;
  readonly apiKey: string | undefined;
  readonly apiKeyHeaderName: string | undefined;
  readonly timeoutMs: string | undefined;
  readonly deploymentNames: readonly string[];
  /**
   * `undefined` when the file never speaks about the flag (no chat/embedding capability record
   * anywhere); an EMPTY list when it speaks and declares no model eligible — which must clear
   * the form field exactly like manually emptying it would.
   */
  readonly imageInputModelIds: readonly string[] | undefined;
  readonly workflowEligibleModelIds: readonly string[] | undefined;
  readonly voiceBaseUrl: string | undefined;
  readonly voiceApiKey: string | undefined;
  readonly voiceApiKeyHeaderName: string | undefined;
  readonly voiceTimeoutMs: string | undefined;
  /** The speech-to-text deployment id. */
  readonly voiceModelId: string | undefined;
  readonly voiceSpeechOutputModelId: string | undefined;
  readonly voiceRealtimeModelId: string | undefined;
  readonly voiceRealtimeTranscriptionModelId: string | undefined;
  /** `undefined` when the file carries no realtime voice capability to speak about it. */
  readonly voiceSemanticTurnDetection: boolean | undefined;
  /**
   * True when the file carries a realtime voice provider on a DIFFERENT connection than the
   * speech providers. The form holds one voice connection per submit, so that provider cannot
   * be imported alongside them — the upload states the skip instead of silently dropping it or
   * refusing the whole file (the persisted product configuration this feature exists for has
   * exactly this shape: realtime on the gateway endpoint, speech on a dedicated one).
   */
  readonly voiceRealtimeSkipped: boolean;
  readonly figmaAccessToken: string | undefined;
}

export type GatewayConfigUploadResult =
  | { readonly outcome: "fields"; readonly fields: GatewayConfigUploadFields }
  | { readonly outcome: "invalid" }
  | { readonly outcome: "unsupportedKind" }
  | { readonly outcome: "unsupportedSetting" };

interface ParsedProvider {
  readonly modelId: string;
  readonly baseUrl: string | undefined;
  readonly apiKey: string | undefined;
  readonly apiKeyHeaderName: string | undefined;
  readonly timeoutMs: number | undefined;
  readonly capability: ParsedCapability | undefined;
}

interface ParsedCapability {
  readonly kind: string;
  readonly supportsImageInput: boolean;
  readonly workflowEligible: boolean;
  readonly speechInput: boolean;
  readonly speechOutput: boolean;
  readonly realtime: boolean;
  readonly semanticTurnDetection: boolean;
  readonly realtimeTranscriptionModel: string | undefined;
}

function objectRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Mirrors the setup route's model-id constraints (length bound, no control characters). */
function usableModelId(id: string): boolean {
  if (id.length === 0 || id.length > MAX_IMPORT_MODEL_ID_LENGTH) return false;
  for (const character of id) {
    const code = character.codePointAt(0) ?? 0;
    if (code <= 31 || code === 127) return false;
  }
  return true;
}

/**
 * An ABSENT field reads as `undefined`; a PRESENT field must be a non-blank string or the whole
 * file refuses. Converting a malformed present value to silence would report a hostile or
 * corrupted file as successfully loaded (review finding on #3031).
 */
function readString(value: unknown): { readonly ok: boolean; readonly value: string | undefined } {
  if (value === undefined) return { ok: true, value: undefined };
  if (typeof value !== "string" || value.trim() === "") return { ok: false, value: undefined };
  return { ok: true, value: value.trim() };
}

function readTimeout(value: unknown): { readonly ok: boolean; readonly value: number | undefined } {
  if (value === undefined) return { ok: true, value: undefined };
  if (typeof value !== "number" || !Number.isInteger(value) || value <= 0) {
    return { ok: false, value: undefined };
  }
  return { ok: true, value };
}

function capabilityFlagsAreBooleans(value: Record<string, unknown>): boolean {
  return CAPABILITY_FLAG_KEYS.every(
    (key) => value[key] === undefined || typeof value[key] === "boolean",
  );
}

/**
 * A capability must carry a known string `kind` and boolean-or-absent flags; coercing a corrupted
 * declaration to `false` could clear stored image or workflow eligibility during an update while
 * reporting the file as loaded (review finding on #3031). Metadata fields the form does not read
 * (context window, cost class, …) stay tolerated — the persisted product configuration carries
 * them.
 */
function parsedCapability(value: unknown): ParsedCapability | undefined {
  if (!objectRecord(value) || !capabilityFlagsAreBooleans(value)) return undefined;
  const kind = typeof value.kind === "string" ? value.kind : undefined;
  if (kind === undefined || !KNOWN_KINDS.has(kind)) return undefined;
  const transcription = readString(value.realtimeTranscriptionModel);
  if (!transcription.ok) return undefined;
  if (transcription.value !== undefined && !usableModelId(transcription.value)) return undefined;
  return {
    kind,
    supportsImageInput: value.supportsImageInput === true,
    workflowEligible: value.workflowEligible === true,
    speechInput: value.supportsSpeechInput === true,
    speechOutput: value.supportsSpeechOutput === true,
    realtime: value.supportsRealtimeVoice === true,
    semanticTurnDetection: value.supportsSemanticTurnDetection === true,
    realtimeTranscriptionModel: transcription.value,
  };
}

function providerConnectionScalars(value: Record<string, unknown>): ConnectionScalars | undefined {
  const baseUrl = readString(value.baseUrl);
  const apiKey = readString(value.apiKey);
  const header = readString(value.apiKeyHeaderName);
  const timeout = readTimeout(value.timeoutMs);
  if (!baseUrl.ok || !apiKey.ok || !header.ok || !timeout.ok) return undefined;
  return {
    baseUrl: baseUrl.value,
    apiKey: apiKey.value,
    apiKeyHeaderName: header.value,
    timeoutMs: timeout.value,
  };
}

function parsedProvider(value: unknown): ParsedProvider | undefined {
  if (!objectRecord(value)) return undefined;
  const modelId = readString(value.modelId);
  if (modelId.value === undefined || !usableModelId(modelId.value)) return undefined;
  const scalars = providerConnectionScalars(value);
  if (scalars === undefined) return undefined;
  // A capability that is PRESENT but malformed is corrupted input, not an absent field — the
  // production parser rejects the same shape (review finding on #3031).
  const capability =
    value.capability === undefined ? undefined : parsedCapability(value.capability);
  if (value.capability !== undefined && capability === undefined) return undefined;
  return { modelId: modelId.value, ...scalars, capability };
}

function parsedProviders(value: unknown): readonly ParsedProvider[] | undefined {
  if (!Array.isArray(value) || value.length === 0) return undefined;
  const providers: ParsedProvider[] = [];
  for (const entry of value) {
    const provider = parsedProvider(entry);
    // Fail closed on the whole file: silently dropping a malformed provider would present a
    // half-applied configuration as a fully loaded one.
    if (provider === undefined) return undefined;
    providers.push(provider);
  }
  return providers;
}

function parsedTopLevelCapabilities(
  value: unknown,
): ReadonlyMap<string, ParsedCapability> | undefined {
  const byId = new Map<string, ParsedCapability>();
  if (value === undefined) return byId;
  if (!Array.isArray(value)) return undefined;
  for (const entry of value) {
    // Same fail-closed policy as the provider list: a malformed capability record refuses the
    // whole file instead of being silently skipped (review finding on #3031).
    if (!objectRecord(entry)) return undefined;
    const id = readString(entry.id);
    const capability = parsedCapability(entry);
    if (id.value === undefined || capability === undefined) return undefined;
    byId.set(id.value, capability);
  }
  return byId;
}

/**
 * One connection per provider group: the form holds a single base URL, token, header, and timeout
 * for the generic providers and a single set for voice. Providers that disagree — including a MIX
 * of a stated value and an omitted one — cannot be represented: applying one provider's value to
 * the others would silently rewrite them (review findings on #3031).
 */
function uniformScalar<T>(values: readonly (T | undefined)[]): {
  readonly ok: boolean;
  readonly value: T | undefined;
} {
  const distinct = [...new Set(values)];
  return distinct.length > 1 ? { ok: false, value: undefined } : { ok: true, value: distinct[0] };
}

function unique(values: readonly string[]): readonly string[] {
  return [...new Set(values)];
}

/**
 * Top-level capability records are authoritative, mirroring the production configuration parser:
 * they override inline provider declarations for the same model id (review finding on #3031).
 */
function effectiveCapabilities(
  providers: readonly ParsedProvider[],
  topLevel: ReadonlyMap<string, ParsedCapability>,
): ReadonlyMap<string, ParsedCapability> | undefined {
  const byId = new Map<string, ParsedCapability>();
  const providerIds = new Set(providers.map((provider) => provider.modelId));
  for (const provider of providers) {
    if (provider.capability !== undefined) byId.set(provider.modelId, provider.capability);
  }
  for (const [id, capability] of topLevel) {
    // A capability for a model no provider imports would put an untestable id into the flag
    // lists and fail Test & Save AFTER a reported success (review finding on #3031).
    if (!providerIds.has(id)) return undefined;
    byId.set(id, capability);
  }
  return byId;
}

interface PartitionedProviders {
  readonly generic: readonly ParsedProvider[];
  readonly voice: readonly ParsedProvider[];
  readonly capabilities: ReadonlyMap<string, ParsedCapability>;
}

function partitionProviders(
  providers: readonly ParsedProvider[],
  capabilities: ReadonlyMap<string, ParsedCapability>,
): PartitionedProviders {
  const voiceIds = new Set(
    [...capabilities.entries()]
      .filter(([, capability]) => capability.kind === "voice")
      .map(([id]) => id),
  );
  return {
    generic: providers.filter((provider) => !voiceIds.has(provider.modelId)),
    voice: providers.filter((provider) => voiceIds.has(provider.modelId)),
    capabilities,
  };
}

function carriesUnsupportedGenericSetting(
  rawProviders: unknown,
  genericIds: ReadonlySet<string>,
): boolean {
  if (!Array.isArray(rawProviders)) return false;
  return rawProviders.some(
    (entry) =>
      objectRecord(entry) &&
      typeof entry.modelId === "string" &&
      genericIds.has(entry.modelId.trim()) &&
      UNSUPPORTED_GENERIC_PROVIDER_SETTINGS.some((setting) => entry[setting] !== undefined),
  );
}

/** Flag lists derive from CHAT capabilities only: the setup route smoke-tests chat candidates and
 * rejects non-chat ids in either list AFTER a reported upload success (review finding on #3031). */
function chatFlaggedIds(
  capabilities: ReadonlyMap<string, ParsedCapability>,
  flag: "supportsImageInput" | "workflowEligible",
): readonly string[] {
  return unique(
    [...capabilities.entries()]
      .filter(([, capability]) => capability.kind === "chat" && capability[flag])
      .map(([id]) => id),
  );
}

interface VoiceRoleProvider {
  readonly provider: ParsedProvider;
  readonly capability: ParsedCapability;
}

interface VoiceRoles {
  readonly speech: readonly VoiceRoleProvider[];
  readonly stt: VoiceRoleProvider | undefined;
  readonly tts: VoiceRoleProvider | undefined;
  readonly realtime: VoiceRoleProvider | undefined;
}

function singleRole(entries: readonly VoiceRoleProvider[]): {
  readonly ok: boolean;
  readonly value: VoiceRoleProvider | undefined;
} {
  // Two providers claiming the same voice role cannot both fill the one form field — refuse
  // rather than silently dropping one of them.
  return entries.length > 1 ? { ok: false, value: undefined } : { ok: true, value: entries.at(0) };
}

function voiceRoles(partition: PartitionedProviders): VoiceRoles | undefined {
  const withCapability = partition.voice.flatMap((provider) => {
    const capability = partition.capabilities.get(provider.modelId);
    return capability === undefined ? [] : [{ provider, capability }];
  });
  // A voice provider with no role flag at all cannot fill any field — refuse rather than
  // silently dropping it from a "successful" load.
  const roleless = withCapability.some(
    (entry) =>
      !entry.capability.speechInput && !entry.capability.speechOutput && !entry.capability.realtime,
  );
  if (roleless) return undefined;
  const stt = singleRole(
    withCapability.filter((entry) => entry.capability.speechInput && !entry.capability.realtime),
  );
  const tts = singleRole(
    withCapability.filter((entry) => entry.capability.speechOutput && !entry.capability.realtime),
  );
  const realtime = singleRole(withCapability.filter((entry) => entry.capability.realtime));
  if (!stt.ok || !tts.ok || !realtime.ok) return undefined;
  const speech = [...new Set([stt.value, tts.value])].filter(
    (entry): entry is VoiceRoleProvider => entry !== undefined,
  );
  return { speech, stt: stt.value, tts: tts.value, realtime: realtime.value };
}

interface VoiceFields {
  readonly connection: ConnectionScalars;
  readonly voiceModelId: string | undefined;
  readonly voiceSpeechOutputModelId: string | undefined;
  readonly voiceRealtimeModelId: string | undefined;
  readonly voiceRealtimeTranscriptionModelId: string | undefined;
  readonly voiceSemanticTurnDetection: boolean | undefined;
  readonly voiceRealtimeSkipped: boolean;
}

function realtimeVoiceFields(realtime: VoiceRoleProvider | undefined): {
  readonly voiceRealtimeModelId: string | undefined;
  readonly voiceRealtimeTranscriptionModelId: string | undefined;
  readonly voiceSemanticTurnDetection: boolean | undefined;
} {
  return {
    voiceRealtimeModelId: realtime?.provider.modelId,
    voiceRealtimeTranscriptionModelId: realtime?.capability.realtimeTranscriptionModel,
    voiceSemanticTurnDetection: realtime?.capability.semanticTurnDetection,
  };
}

/**
 * The form holds ONE voice connection per submit. The speech (STT/TTS) providers must agree on
 * it or the file refuses; a realtime provider on a different connection is skipped with an
 * explicit flag — see {@link GatewayConfigUploadFields.voiceRealtimeSkipped}.
 */
/**
 * The one voice connection a submit can hold. The speech (STT/TTS) providers must agree on it or
 * the file refuses; a realtime provider is included when it shares that connection (trivially so
 * when it is the only voice provider) and skipped otherwise.
 */
function resolvedVoiceConnection(
  roles: VoiceRoles,
): { readonly connection: ConnectionScalars; readonly realtimeSkipped: boolean } | undefined {
  const speechProviders = roles.speech.map((entry) => entry.provider);
  const speechConnection = uniformConnectionScalars(speechProviders);
  if (speechConnection === undefined) return undefined;
  if (roles.realtime === undefined) {
    return { connection: speechConnection, realtimeSkipped: false };
  }
  const combined = uniformConnectionScalars([...speechProviders, roles.realtime.provider]);
  if (combined !== undefined) return { connection: combined, realtimeSkipped: false };
  return { connection: speechConnection, realtimeSkipped: true };
}

function voiceFields(partition: PartitionedProviders): VoiceFields | undefined {
  const roles = voiceRoles(partition);
  if (roles === undefined) return undefined;
  const resolved = resolvedVoiceConnection(roles);
  if (resolved === undefined) return undefined;
  return {
    connection: resolved.connection,
    voiceModelId: roles.stt?.provider.modelId,
    voiceSpeechOutputModelId: roles.tts?.provider.modelId,
    ...realtimeVoiceFields(resolved.realtimeSkipped ? undefined : roles.realtime),
    voiceRealtimeSkipped: resolved.realtimeSkipped,
  };
}

interface ConnectionScalars {
  readonly baseUrl: string | undefined;
  readonly apiKey: string | undefined;
  readonly apiKeyHeaderName: string | undefined;
  readonly timeoutMs: number | undefined;
}

function uniformConnectionScalars(
  providers: readonly ParsedProvider[],
): ConnectionScalars | undefined {
  const baseUrl = uniformScalar(providers.map((provider) => provider.baseUrl));
  const apiKey = uniformScalar(providers.map((provider) => provider.apiKey));
  const header = uniformScalar(providers.map((provider) => provider.apiKeyHeaderName));
  const timeout = uniformScalar(providers.map((provider) => provider.timeoutMs));
  if (!baseUrl.ok || !apiKey.ok || !header.ok || !timeout.ok) return undefined;
  return {
    baseUrl: baseUrl.value,
    apiKey: apiKey.value,
    apiKeyHeaderName: header.value,
    timeoutMs: timeout.value,
  };
}

function timeoutField(timeoutMs: number | undefined): string | undefined {
  return timeoutMs === undefined ? undefined : String(timeoutMs);
}

function fieldsFrom(
  partition: PartitionedProviders,
  generic: ConnectionScalars,
  voice: VoiceFields,
  figmaAccessToken: string | undefined,
): GatewayConfigUploadFields {
  // A file with no chat/embedding capability record never speaks about the flags; a file with
  // any speaks — and an empty result must clear the form field like manual emptying would
  // (review finding on #3031).
  const speaksAboutFlags = [...partition.capabilities.values()].some(
    (capability) => capability.kind !== "voice",
  );
  return {
    figmaAccessToken,
    baseUrl: generic.baseUrl,
    apiKey: generic.apiKey,
    apiKeyHeaderName: generic.apiKeyHeaderName,
    timeoutMs: timeoutField(generic.timeoutMs),
    deploymentNames: unique(partition.generic.map((provider) => provider.modelId)),
    imageInputModelIds: speaksAboutFlags
      ? chatFlaggedIds(partition.capabilities, "supportsImageInput")
      : undefined,
    workflowEligibleModelIds: speaksAboutFlags
      ? chatFlaggedIds(partition.capabilities, "workflowEligible")
      : undefined,
    voiceBaseUrl: voice.connection.baseUrl,
    voiceApiKey: voice.connection.apiKey,
    voiceApiKeyHeaderName: voice.connection.apiKeyHeaderName,
    voiceTimeoutMs: timeoutField(voice.connection.timeoutMs),
    voiceModelId: voice.voiceModelId,
    voiceSpeechOutputModelId: voice.voiceSpeechOutputModelId,
    voiceRealtimeModelId: voice.voiceRealtimeModelId,
    voiceRealtimeTranscriptionModelId: voice.voiceRealtimeTranscriptionModelId,
    voiceSemanticTurnDetection: voice.voiceSemanticTurnDetection,
    voiceRealtimeSkipped: voice.voiceRealtimeSkipped,
  };
}

function capabilitiesForUpload(
  root: Record<string, unknown>,
  providers: readonly ParsedProvider[],
):
  | { readonly outcome: "capabilities"; readonly partition: PartitionedProviders }
  | { readonly outcome: "invalid" }
  | { readonly outcome: "unsupportedKind" } {
  const topLevel = parsedTopLevelCapabilities(root.capabilities);
  if (topLevel === undefined) return { outcome: "invalid" };
  const capabilities = effectiveCapabilities(providers, topLevel);
  if (capabilities === undefined) return { outcome: "invalid" };
  // `ocr-vision` has no setup field at all — importing it as a generic deployment would persist
  // the wrong capability kind (review finding on #3031).
  const unrepresentable = [...capabilities.values()].some(
    (capability) => !REPRESENTABLE_KINDS.has(capability.kind),
  );
  if (unrepresentable) return { outcome: "unsupportedKind" };
  return { outcome: "capabilities", partition: partitionProviders(providers, capabilities) };
}

function uploadRoot(serialized: string): Record<string, unknown> | undefined {
  let root: unknown;
  try {
    root = JSON.parse(serialized);
  } catch {
    return undefined;
  }
  return objectRecord(root) ? root : undefined;
}

function assembledFields(
  root: Record<string, unknown>,
  partition: PartitionedProviders,
): GatewayConfigUploadResult {
  const generic = uniformConnectionScalars(partition.generic);
  const voice = voiceFields(partition);
  if (generic === undefined || voice === undefined) {
    return { outcome: "invalid" };
  }
  const figma = readString(objectRecord(root.figma) ? root.figma.accessToken : undefined);
  if (!figma.ok) return { outcome: "invalid" };
  return {
    outcome: "fields",
    fields: fieldsFrom(partition, generic, voice, figma.value),
  };
}

export function parseGatewayConfigUpload(serialized: string): GatewayConfigUploadResult {
  const root = uploadRoot(serialized);
  if (root === undefined) return { outcome: "invalid" };
  const providers = parsedProviders(root.providers);
  if (providers === undefined || providers.length > MAX_IMPORT_PROVIDERS) {
    return { outcome: "invalid" };
  }
  const resolved = capabilitiesForUpload(root, providers);
  if (resolved.outcome !== "capabilities") return resolved;
  const genericIds = new Set(resolved.partition.generic.map((provider) => provider.modelId));
  if (carriesUnsupportedGenericSetting(root.providers, genericIds)) {
    return { outcome: "unsupportedSetting" };
  }
  return assembledFields(root, resolved.partition);
}

/** How many form fields an upload fills — the number the status line reports. */
export function appliedGatewayConfigFieldCount(fields: GatewayConfigUploadFields): number {
  const scalars = [
    fields.baseUrl,
    fields.apiKey,
    fields.apiKeyHeaderName,
    fields.timeoutMs,
    fields.figmaAccessToken,
    fields.voiceBaseUrl,
    fields.voiceApiKey,
    fields.voiceApiKeyHeaderName,
    fields.voiceTimeoutMs,
    fields.voiceModelId,
    fields.voiceSpeechOutputModelId,
    fields.voiceRealtimeModelId,
    fields.voiceRealtimeTranscriptionModelId,
  ];
  // A defined-but-empty flag list clears its field, which is an applied change too.
  const flagLists = [fields.imageInputModelIds, fields.workflowEligibleModelIds];
  return (
    scalars.filter((value) => value !== undefined).length +
    (fields.deploymentNames.length > 0 ? 1 : 0) +
    flagLists.filter((list) => list !== undefined).length
  );
}
