import { DEFAULT_LARGE_DOCUMENT_RESOURCE_POLICY } from "@oscharko-dev/keiko-contracts";

export const LOCAL_KNOWLEDGE_MAX_FILE_BYTES =
  DEFAULT_LARGE_DOCUMENT_RESOURCE_POLICY.maxRawFileBytes;
export const LOCAL_KNOWLEDGE_MAX_OBJECTS_PER_DOCUMENT =
  DEFAULT_LARGE_DOCUMENT_RESOURCE_POLICY.maxParserObjects;
export const LOCAL_KNOWLEDGE_PARSER_TIMEOUT_MS =
  DEFAULT_LARGE_DOCUMENT_RESOURCE_POLICY.maxWallClockMs;
